import { toGlobId } from 'rw-lib/index'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th13: DLoc.ILocItem = {
  'en-gb': 'CHARACTER SEQUENCING',
  'de-de': 'EINORDNUNG DER SCHRIFTZEICHEN',
  'sp-sp': 'SECUENCIA DE LETRAS',
  'cs-cz': 'ŘAZENÍ PÍSMEN',
  'sk-sk': 'RADENIE PÍSMEN',
  'ru-ru': 'ПОРЯДОК БУКВ',
  'fr-fr': 'CLASSEMENT DE LETTRES',
  'it-it': 'SEQUENZA DELLE LETTERE',
  'pl-pl': 'UKŁADANIE LITER',
  'vi-vn': 'SẮP XẾP KÝ TỰ',
  'tr-tr': 'KARAKTER SIRALAMA',
  'lt-lt': 'POBŪDŽIO SEKOS',
  'zh-cn': '字符排序',
  'bg-bg': 'ПОСЛЕДОВАТЕЛНОСТ НА БУКВИТЕ',
  'bs': 'CHARACTER SEQUENCING',
  'ar-sa': 'ترتيب حروف',
};
const tp3: DLoc.ILocItem = {
  'en-gb': 'Your task is to put the characters into correct order. Proceed as follows:',
  'de-de': 'Ihre Aufgabe ist es, die Schriftzeichen in die richtige Reihenfolge zu setzen. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea es ordenar las letras en el orden correcto y formar la palabra. Proceda de la siguiente manera:',
  'cs-cz': 'Vaším úkolem je seřadit písmena do správného pořadí, aby tvořila slovo. Postupujte následovně:',
  'sk-sk': 'Vašou úlohou je zoradiť písmená do správneho poradia, aby tvorili slovo. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - расставить буквы в правильном порядке, чтобы получилось слово. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici placer les lettres dans le bon ordre.',
  'it-it': 'Il tuo compito è mettere le lettere nell’ordine corretto in modo da formare una parola. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest ułożenie liter w odpowiedniej kolejności. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy sắp xếp các ký tự theo đúng thứ tự. Cách làm như sau:',
  'tr-tr': 'Göreviniz karakterleri dogru siraya sokmaktir. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra sudėti simbolius teisinga tvarka. Darykite taip:',
  'zh-cn': '您的任务是将字符排列为正确的顺序. 操作如下:',
  'bg-bg': 'Вашата задача е да поставите буквите в правилния ред. Действайте по следния начин:',
  'bs': 'Your task is to put the characters into correct order. Proceed as follows:',
  'ar-sa': 'مهمتك هي أن تضع الأحرف بالترتيب الصحيح. قم بما يلي:',
};
const tli12: DLoc.ILocItem = {
  'en-gb': 'Click on the character you wish to move. The character will be highlighted.',
  'de-de': 'Klicken Sie auf das Schriftzeichen, das Sie bewegen möchten. Das Schriftzeichen wird hervorgehoben.',
  'sp-sp': 'Haga clic en la letra que desea mover. Esta aparecerá resaltada',
  'cs-cz': 'Klikněte na písmeno, které chcete přesunout. Písmeno se zvýrazní.',
  'sk-sk': 'Kliknite na písmeno, ktoré chcete presunúť. Písmeno sa zvýrazní.',
  'ru-ru': 'Кликнете на букву, которую вы хотите переместить. Буква выделится.',
  'fr-fr': 'Cliquez sur la lettre que vous voulez déplacer.',
  'it-it': 'Clicca sulla lettera da trascinare. La lettera viene marcata.',
  'pl-pl': 'Kliknij na literę, którą chcesz przesunąć. Litera zostanie wyróżniona.',
  'vi-vn': 'Nhấn chuột lên ký tự bạn muốn di chuyển. Ký tự đó sẽ được đánh dấu.',
  'tr-tr': 'Kaldırmak istediğiniz karakterin üstüne tıklayın. Karekter renkli olarak vurgulanacaktır.',
  'lt-lt': 'Spustelėkite simbolį, kurį norite perkelti. Simbolis bus paryškintas.',
  'zh-cn': '点击您想要移动的字符. 字符将被突出显示.',
  'bg-bg': 'Кликнете върху буквата, която искате да преместите. Буквата ще бъде засветена.',
  'bs': 'Click on the character you wish to move. The character will be highlighted.',
  'ar-sa': 'إضغط على الحرف الذي تشاء للإنتقال إليه. سيتم تحديد الحرف.',
};
const tli13: DLoc.ILocItem = {
  'en-gb': 'Hold the left mouse button down and drag the character to the right place.',
  'de-de': 'Halten Sie die linke Maustaste gedrückt und ziehen Sie den Schriftzeichen auf die richtige Stelle.',
  'sp-sp': 'Mantenga presionado el botón izquierdo del ratón y arrastre la letra a su posición correcta.',
  'cs-cz': 'Držte tlačítko myši stisknuté a přesuňte písmeno (pohybem myši) na nové místo.',
  'sk-sk': 'Držte tlačidlo myši stlačené a presuňte písmeno (pohybom myši) na nové miesto.',
  'ru-ru': 'Держите нажатой кнопку мыши и перетяните букву (движением мыши) на новое место.',
  'fr-fr': 'Maintenez le bouton de la souris enfoncé et glissez la lettre à l’endroit souhaité.',
  'it-it': 'Tieni premuto il pulsante del mouse e trascina la lettera (muovendo il mouse) al posto nuovo.',
  'pl-pl': 'Przytrzymaj lewy przycisk myszki i przeciągnij literę w odpowiednie miejsce.',
  'vi-vn': 'Nhấn, giữ chuột trái và kéo ký tự đó vào đúng vị trí.',
  'tr-tr': 'Mouse\u0027un sol tuşuna basılı tutun ve karakteri doğru yere sürükleyin.',
  'lt-lt': 'Laikydami kairįjį pelės mygtuką, vilkite simbolį į tinkamą vietą.',
  'zh-cn': '按住鼠标左键并拖曳字符至正确位置.',
  'bg-bg': 'Натиснете продължително левия бутон на мишката и влачете буквата до правилното място.',
  'bs': 'Hold the left mouse button down and drag the character to the right place.',
  'ar-sa': 'استمر في الضغط على الزر الأيسر للفارة و اسحب الحرف إلى المكان الصحيح',
};
const tli14: DLoc.ILocItem = {
  'en-gb': 'When the mouse arrow points to the right place, release the left mouse button.',
  'de-de': 'Wenn der Pfeil auf die richtige Stelle zeigt, lassen Sie die linke Maustaste los.',
  'sp-sp': 'Cuando el puntero señale el lugar correcto, suelte el botón izquierdo del ratón.',
  'cs-cz': 'Až bude kurzor myši nad místem, na které chcete písmeno přesunout, uvolněte kurzor myši.',
  'sk-sk': 'Keď bude kurzor myši nad miestom, na ktoré chcete písmeno presunúť, uvoľnite kurzor myši.',
  'ru-ru': 'Когда курсор мыши будет на том месте, куда вы хотите букву переместить, отпустите кнопку мыши.',
  'fr-fr': 'Relâchez le bouton pour placer la lettre.',
  'it-it': 'Nel momento in cui il cursore del mouse sarà impostato sul posto dove desideri impostare la lettera, rilascia il cursore del mouse.',
  'pl-pl': 'Jeżeli strzałka wskazuje na odpowiednie miejsce, puść przycisk myszki.',
  'vi-vn': 'Khi mũi tên con trỏ chuột chỉ đúng vị trí, hãy thả nút trái chuột.',
  'tr-tr': 'Mouse oku dogru yeri gösterdiginde, sol mouse tuşunu birakin.',
  'lt-lt': 'Kai pelės strelytė bus reikiamoje vietoje, atleiskite kairįjį pelės mygtuką.',
  'zh-cn': '当鼠标箭头指向正确的位置, 即放开鼠标左键.',
  'bg-bg': 'Когато стрелката на мишката покаже правилното място, отпуснете левия бутон на мишката.',
  'bs': 'When the mouse arrow points to the right place, release the left mouse button.',
  'ar-sa': 'عندما يصبح مؤشر الفارة في المكان الصحيح أفلت زر الفارة الأيسر',
};
const tli15: DLoc.ILocItem = {
  'en-gb': 'The character will be moved.',
  'de-de': 'Das Schriftzeichen wird verschoben.',
  'sp-sp': 'La letra se moverá.',
  'cs-cz': 'Písmeno bude přesunuto.',
  'sk-sk': 'Písmeno bude presunuté.',
  'ru-ru': 'Буква будет перемещена.',
  'fr-fr': 'La lettre sera déplacée.',
  'it-it': 'La lettera sarà trascinata.',
  'pl-pl': 'Litera zostanie przeniesiona.',
  'vi-vn': 'Ký tự sẽ được chuyển chỗ.',
  'tr-tr': 'Karakter kaldırılacaktır.',
  'lt-lt': 'Simbolis bus perkeltas',
  'zh-cn': '该字符将被移动.',
  'bg-bg': 'Буквата ще се премести.',
  'bs': 'The character will be moved.',
  'ar-sa': 'سيتم نقل الحرف',
};
const res = { [globId]: { th13, tp3, tli12, tli13, tli14, tli15 } };
export default res;