import { toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th119: DLoc.ILocItem = {
  'en-gb': 'MODIFICATION (CORRECTION) OF THE TEXT',
  'de-de': 'MODIFIKATION (KORREKTUR) DES TEXTES',
  'sp-sp': 'MODIFICACIÓN (CORRECCIÓN) DEL TEXTO',
  'cs-cz': 'ÚPRAVA (OPRAVA) TEXTU',
  'sk-sk': 'ÚPRAVA (OPRAVA) TEXTU',
  'ru-ru': 'ОБРАБОТКА (ИСПРАВЛЕНИЕ) ТЕКСТА',
  'fr-fr': 'CORRECTION DE TEXTE',
  'it-it': 'MODIFICA (CORREZIONE) DEL TESTO',
  'pl-pl': 'MODYFIKACJA (KOREKTA) TEKSTU',
  'vi-vn': 'THAY ĐỔI (SỬA CHỮA) ĐOẠN VĂN BẢN',
  'tr-tr': 'METİNDE DEĞİŞİKLİK (DÜZELTME)',
  'lt-lt': 'TEKSTO PAKEITIMAS (PATAISYMAS)',
  'zh-cn': '文本修改 (订正)',
  'bg-bg': 'ПРОМЯНА (ПОПРАВКА) НА ТЕКСТА',
  'bs': 'MODIFICATION (CORRECTION) OF THE TEXT',
  'ar-sa': 'تقييد المعنى (تصحيح الخطأ حسب النص)',
};
const tp29: DLoc.ILocItem = {
  'en-gb': 'Your task is to rewrite the words in the gap into the correct form. Proceed as follows:',
  'de-de': 'Ihre Aufgabe ist es, die leeren Felder mit den Sätzen oder Wörtern, die Sie hören, zu füllen. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea es rellenar los campos vacíos con las palabras o las oraciones que escuche. Proceda de la siguiente manera:',
  'cs-cz': 'Vaším úkolem je přepsat slova v okénku do správného tvaru. Postupujte následovně:',
  'sk-sk': 'Vašou úlohou je vyplniť do prázdnych políčok slová alebo vety, ktoré počujete. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - дополнить в пустые поля слова или предложения, которые вы слышите. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici saisir dans les cellules vides le ou les mots que vous entendez.',
  'it-it': 'Il tuo compito è completare le caselle vuote con le parole o frasi sentite. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest wpisanie w puste pola wyrazów lub zdań, które słyszysz. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy điền vào chỗ trống những từ và câu mà bạn nghe được. Cách làm như sau:',
  'tr-tr': 'Göreviniz duydugunuz kelimeleri ve cümleleri boş kutulara doldurmaktir. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra užpildyti tuščius langelius žodžiais arba sakiniais, kuriuos girdite. Darykite taip:',
  'zh-cn': '您的任务是在空格填写您听到的单词或句. 操作如下:',
  'bg-bg': 'Вашата задача е да попълните празните кутийки с думите или изреченията, които чувате. Действайте по следния начин:',
  'bs': 'Your task is to rewrite the words in the gap into the correct form. Proceed as follows:',
  'ar-sa': 'مهمتك هي ملئ الصناديق الخالية بالكلمات أو الجمل التي تسمعها .قم بما يلي:',
};
const tli59: DLoc.ILocItem = {
  'en-gb': 'Click on the text you wish to change - a blinking cursor appears.',
  'de-de': 'Klicken Sie auf den Text, den Sie ändern möchten - ein blinkender Cursor wird erscheinen.',
  'sp-sp': 'Haga clic en el texto que desea cambiar - un cursor parpadeante aparecerá',
  'cs-cz': 'Klikněte na text, který chcete změnit - objeví se blikající kurzor.',
  'sk-sk': 'Kliknite na text, ktorý chcete zmeniť - objaví sa blikajúci kurzor.',
  'ru-ru': 'Кликнете на текст, который вы хотите поменять - появится мигающий курсор.',
  'fr-fr': 'Cliquez dans la cellule souhaitée.',
  'it-it': 'Clicca sul testo da modificare – verrà visualizzato il cursore lampeggiante.',
  'pl-pl': 'Kliknij na tekst, który chcesz zmienić - pojawi się migający kursor.',
  'vi-vn': 'Nhấn chuột lên đoạn văn bản bạn muốn thay đổi - con trỏ sẽ nhấp nháy.',
  'tr-tr': 'Kaldırmak istediğiniz metni tıklayın. Metin renkli olarak vurgulanacaktır.',
  'lt-lt': 'Spustelėkite tekstą, kurį norite pakeisti - atsiras mirksintis žymeklis.',
  'zh-cn': '点击您想要更改的文本 - 一个闪烁的光标将会出现.',
  'bg-bg': 'Кликнете върху текста, който искате да промените - появява се мигащ курсор.',
  'bs': 'Click on the text you wish to change - a blinking cursor appears.',
  'ar-sa': 'Click on the text you wish to change - a blinking cursor appears.',
};
const tli60: DLoc.ILocItem = {
  'en-gb': 'Rewrite the text into the correct form. It is possible, that no changes will be needed.',
  'de-de': 'Schreiben Sie den Text richtig.',
  'sp-sp': 'Rewrite the text into the correct form. It is possible, that no changes will be needed.',
  'cs-cz': 'Přepište text do správného tvaru. Může se stát, že žádné úpravy nebudou potřeba.',
  'sk-sk': 'Doplňte text správne.',
  'ru-ru': 'Дополните правильно текст.',
  'fr-fr': 'Saisissez le nouveau texte corrigé à l’aide de votre clavier.',
  'it-it': 'Completa correttamente il testo.',
  'pl-pl': 'Wpisz poprawny tekst.',
  'vi-vn': 'Rewrite the text into the correct form. It is possible, that no changes will be needed.',
  'tr-tr': 'Dogru metini yaziniz.',
  'lt-lt': 'Įveskite teisingą tekstą.',
  'zh-cn': 'Rewrite the text into the correct form. It is possible, that no changes will be needed.',
  'bg-bg': 'Напишете правилния текст.',
  'bs': 'Rewrite the text into the correct form. It is possible, that no changes will be needed.',
  'ar-sa': 'Rewrite the text into the correct form. It is possible, that no changes will be needed.',
};
const res = { [globId]: { th119, tp29, tli59, tli60 } };
export default res;