import { ILocItem, toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th118: ILocItem = {
  'en-gb': 'DICTATION',
  'de-de': 'DIKTAT',
  'sp-sp': 'DICTADO',
  'cs-cz': 'DIKTÁT',
  'sk-sk': 'DIKTÁT',
  'ru-ru': 'ДИКТАНТ',
  'fr-fr': 'DICTÉE',
  'it-it': 'DETTATO',
  'pl-pl': 'DYKTANDO',
  'vi-vn': 'BÀI CHÍNH TẢ',
  'tr-tr': 'DİKTE ETMEK',
  'lt-lt': 'DIKTANTAS',
  'zh-cn': '听写',
  'bg-bg': 'ДИКТОВКА',
  'bs': 'DICTATION',
  'ar-sa': 'DICTATION',
};
const tp27: ILocItem = {
  'en-gb': 'Your task is to fill in the empty boxes with the words or sentences you hear. Proceed as follows:',
  'de-de': 'Ihre Aufgabe ist zu entscheiden, ob die Sätze wahr oder unwahr sind. Gehen Sie wie folgt vor:',
  'sp-sp': 'Your task is to fill in the empty boxes with the words or sentences you hear. Proceed as follows:',
  'cs-cz': 'Vaším úkolem je vyplnit do prázdných políček slova nebo věty, které slyšíte. Postupujte následovně:',
  'sk-sk': 'Cvičenie so zvukovou nahrávkou poznáte podľa \"zvukových značiek\". Existujú dve rôzne zvukové značky:',
  'ru-ru': 'Упражнения с аудиозаписью можно узнать по \"звуковым значкам\". Существуют два разных звуковых значка:',
  'fr-fr': 'Vous reconnaîtrez les exercices avec extraits audio grâce aux haut-parleurs :',
  'it-it': 'Gli esercizi con l’audio sono riconoscibili attraverso il „simbolo dell\u0027audio“. Esistono i due simboli dell’audio:',
  'pl-pl': 'Ćwiczenia ze ścieżką dźwiękową mogą być rozpoznane poprzez ich \"znak dźwiękowy\". Istnieją dwa rodzaje \"znaków dźwiękowych\":',
  'vi-vn': 'Your task is to fill in the empty boxes with the words or sentences you hear. Proceed as follows:',
  'tr-tr': 'Ses kayıtlı egzersizler \"ses işaretleriyle\" tanınır. İki tip \"ses işareti\" vardır:',
  'lt-lt': 'Pratimai su garso takeliu gali būti atskirti pagal \"garso ženklus\". \"Garso ženklai\" yra dviejų tipų:',
  'zh-cn': 'Your task is to fill in the empty boxes with the words or sentences you hear. Proceed as follows:',
  'bg-bg': 'Упражнения, придружени със звук, могат да бъдат разпознати чрез \"знака за звук\". Има два вида \"знак за звук\".',
  'bs': 'Your task is to fill in the empty boxes with the words or sentences you hear. Proceed as follows:',
  'ar-sa': 'مهمتك أن تقرر فيما إذا كانت الجمل صحيحة أم خاطئة. قم بما يلي :',
};
const tli56: ILocItem = {
  'en-gb': 'Listen to the word or the sentence.',
  'de-de': 'Hören Sie das Wort oder den Satz an.',
  'sp-sp': 'Escuche la palabra u oración.',
  'cs-cz': 'Poslechněte si slovo nebo větu.',
  'sk-sk': 'Vypočujte si slovo alebo vetu.',
  'ru-ru': 'Послушайте слово или предложение.',
  'fr-fr': 'Écoutez attentivement le mot ou la phrase.',
  'it-it': 'Ascolta la parola oppure la frase.',
  'pl-pl': 'Wysłuchaj słowa lub zdania.',
  'vi-vn': 'Lắng nghe từ hoặc câu.',
  'tr-tr': 'Kelimeyi veya cümleyi dinleyin.',
  'lt-lt': 'Paklausykite žodžio arba sakinio.',
  'zh-cn': '收听单词或句子.',
  'bg-bg': 'Слушайте думата или изречението.',
  'bs': 'Listen to the word or the sentence.',
  'ar-sa': 'استمع إلى الكلمة أو الجملة',
};
const tli57: ILocItem = {
  'en-gb': 'Click on the empty space - a blinking cursor appears.',
  'de-de': 'Klicken Sie auf die leere Lücke - ein blinkender Cursor wird erscheinen.',
  'sp-sp': 'Click on the empty space - a blinking cursor appears.',
  'cs-cz': 'Klikněte do prázdného okénka - objeví se blikající kurzor.',
  'sk-sk': 'Kliknite do prázdneho okienka - objaví sa blikajúci kurzor.',
  'ru-ru': 'Кликнете в пустом окошечке - появится мигающий курсор.',
  'fr-fr': 'Cliquez dans une cellule vide. Un curseur apparaît.',
  'it-it': 'Clicca sulla casella vuota – verrà visualizzato il cursore lampeggiante.',
  'pl-pl': 'Kliknij w puste miejsce - pojawi się migający kursor.',
  'vi-vn': 'Click on the empty space - a blinking cursor appears.',
  'tr-tr': 'Boş alana tıklayın - yanıp sönen ışıklı bir gösterge ortaya çıkacaktır.',
  'lt-lt': 'Paspauskite ant tuščio tarpo - atsiras mirksintis kursorius.',
  'zh-cn': 'Click on the empty space - a blinking cursor appears.',
  'bg-bg': 'Кликнете в празното място в групата - появява се мигащ курсор.',
  'bs': 'Click on the empty space - a blinking cursor appears.',
  'ar-sa': 'Click on the empty space - a blinking cursor appears.',
};
const tli58: ILocItem = {
  'en-gb': 'Type in the text that you hear using your keyboard.',
  'de-de': 'Schreiben Sie den Text, den Sie hören.',
  'sp-sp': 'Type in the text that you hear using your keyboard.',
  'cs-cz': 'Doplňte text, který slyšíte, pomocí klávesnice.',
  'sk-sk': 'Doplňte text, ktorý počujete, pomocou klávesnice.',
  'ru-ru': 'Дополните текст, который вы слышите, с помощью клавиатуры.',
  'fr-fr': 'Saisissez le texte que vous entendez à l\u0027aide du clavier.',
  'it-it': 'Attraverso la tastiera completa il testo sentito.',
  'pl-pl': 'Wpisz tekst, który słyszysz.',
  'vi-vn': 'Type in the text that you hear using your keyboard.',
  'tr-tr': 'Duydugunuz metini yaziniz.',
  'lt-lt': 'Įveskite tekstą taip, kaip jį girdite.',
  'zh-cn': 'Type in the text that you hear using your keyboard.',
  'bg-bg': 'Напишете текста, който чувате.',
  'bs': 'Type in the text that you hear using your keyboard.',
  'ar-sa': 'Type in the text that you hear using your keyboard.',
};
const tp28: ILocItem = {
  'en-gb': 'To edit the item, select it and make correction.',
  'de-de': 'Ihre Aufgabe ist zu entscheiden, ob die Antwort auf die Frage JA oder NEIN lautet. Gehen Sie wie folgt vor:',
  'sp-sp': 'To edit the item, select it and make correction.',
  'cs-cz': 'Pokud chcete opravit již doplněnou položku, klikněte do okénka a položku opravte.',
  'sk-sk': 'Pre spustenie videa kliknite na ikonku pre prehrávanie, umiestnenú v ľavej časti ovládacej lišty. Prehrá sa tak celé video. Prehrávanie môžete kedykoľvek zastaviť, alebo prerušiť kliknutím na príslušné tlačidlá pod prehrávaným videom.',
  'ru-ru': 'To edit the item, select it and make correction.',
  'fr-fr': 'To edit the item, select it and make correction.',
  'it-it': 'To edit the item, select it and make correction.',
  'pl-pl': 'To edit the item, select it and make correction.',
  'vi-vn': 'To edit the item, select it and make correction.',
  'tr-tr': 'Video\u0027yu görüntülemek için denetim çubuğunun sol bölümündeki Oynat ikonunu tıklayın. Tüm video tekrar oynayacaktır. İstenildiğinde alttaki çubuktaki ilgili butonları tıklayarak oynaması durdurulabilinir ve kesilebilinir.',
  'lt-lt': 'Norėdami peržiūrėti vaizdo įrašą, paspauskite Play ikoną kairėje valdymo juostos pusėje. Tuomet visas vaizdo įrašas bus pakartotas. Peržiūra gali būti sustabdyta ar nutraukta bet kuriuo momentu paspaudus tiesiogiai atitinkamus mygtukus apatinėje juostoje.',
  'zh-cn': 'To edit the item, select it and make correction.',
  'bg-bg': 'За да гледате видео клип, кликнете на иконката \"пусни\" в лявата част на контролната лента. В този случай ще пуснете целия видео клип. Видео клипът може да бъде спрян или прекъснат по всяко време чрез кликване на съответния бутон от лентата с бутони.',
  'bs': 'To edit the item, select it and make correction.',
  'ar-sa': 'مهمتك أن تقرر فيما إذا كانت إجابات الأسئلة - نعم أم لا-',
};
const res = { [globId]: { th118, tp27, tli56, tli57, tli58, tp28 } };
export default res;