import { ILocItem } from "rw-lib/loc";
const th112: ILocItem = {
  "en-gb": "FILLING IN",
  "de-de": "AUSFÜLLEN",
  "sp-sp": "COMPLETAR",
  "cs-cz": "DOPLŇOVÁNÍ",
  "sk-sk": "DOPLŇOVANIE",
  "ru-ru": "ЗАПОЛНЕНИЕ ПРОПУСКОВ",
  "fr-fr": "CELLULES À COMPLÉTER",
  "it-it": "COMPLETAMENTO",
  "pl-pl": "UZUPEŁNIANIE",
  "vi-vn": "ĐIỀN VÀO CHỖ TRỐNG",
  "tr-tr": "İÇİNİ DOLDURMAK",
  "lt-lt": "PILDYMAS",
  "zh-cn": "填充",
  "bg-bg": "ПОПЪЛВАНЕ",
  "bs": "FILLING IN",
  "ar-sa": "ملء الفراغات",
};
const tp17: ILocItem = {
  "en-gb": "Your task is to fill in the empty boxes within the text. Proceed as follows:",
  "de-de": "Um das Objekt von der Gruppe zurück in die Liste zu geben, klicken Sie es an.",
  "sp-sp": "Para regresar el objeto del grupo a la lista, haga clic sobre el objeto.",
  "cs-cz": "Vaším úkolem je vyplnit prázdná okénka v textu. Postupujte následovně:",
  "sk-sk": "Pokiaľ chcete položku vrátiť zo skupiny do zoznamu, kliknite na ňu.",
  "ru-ru": "Если вы хотите пункт вернуть из группы в список, нажмите на него.",
  "fr-fr": "Si vous voulez replacer une étiquette dans la liste, cliquez dessus et glissez-déposez-la de nouveau.",
  "it-it": "Per riportare la voce dal gruppo all’elenco, clicca sulla voce stessa.",
  "pl-pl": "Aby przywrócić element z powrotem do listy, kliknij go.",
  "vi-vn": "Để chuyển một mục từ một nhóm trở lại danh sách, nhấn chuột lên mục đó.",
  "tr-tr": "Ögeyi gruptan geri çekmek için, üzerine tiklayin.",
  "lt-lt": "Norėdami grąžinti elementą iš sąrašo atgal į grupę, paspauskite ant jo.",
  "zh-cn": "从群组中将项目恢复至列表, 请点击該项目.",
  "bg-bg": "За да върнете позиция от групата обратно в списъка, кликнете върху нея.",
  "bs": "Your task is to fill in the empty boxes within the text. Proceed as follows:",
  "ar-sa": "لاستعادة العنصر من مجموعة إلى القائمة قم بالضغط عليه.",
};
const tli38: ILocItem = {
  "en-gb": "Click on the empty space - a blinking cursor appears.",
  "de-de": "Klicken Sie auf die leere Lücke - ein blinkender Cursor wird erscheinen.",
  "sp-sp": "Click on the empty space - a blinking cursor appears.",
  "cs-cz": "Klikněte do prázdného okénka - objeví se blikající kurzor.",
  "sk-sk": "Kliknite do prázdneho okienka - objaví sa blikajúci kurzor.",
  "ru-ru": "Кликнете в пустом окошечке - появится мигающий курсор.",
  "fr-fr": "Cliquez dans une cellule vide. Un curseur apparaît.",
  "it-it": "Clicca sulla casella vuota – verrà visualizzato il cursore lampeggiante.",
  "pl-pl": "Kliknij w puste miejsce - pojawi się migający kursor.",
  "vi-vn": "Click on the empty space - a blinking cursor appears.",
  "tr-tr": "Boş alana tıklayın - yanıp sönen ışıklı bir gösterge ortaya çıkacaktır.",
  "lt-lt": "Paspauskite ant tuščio tarpo - atsiras mirksintis kursorius.",
  "zh-cn": "Click on the empty space - a blinking cursor appears.",
  "bg-bg": "Кликнете в празното място в групата - появява се мигащ курсор.",
  "bs": "Click on the empty space - a blinking cursor appears.",
  "ar-sa": "Click on the empty space - a blinking cursor appears.",
};
const tli39: ILocItem = {
  "en-gb": "Type in the text using your keyboard.",
  "de-de": "Schreiben Sie den Text mit Hilfe der Tastatur ein.",
  "sp-sp": "Complete el campo con la ayuda del teclado.",
  "cs-cz": "Doplňte text pomocí klávesnice.",
  "sk-sk": "Doplňte text pomocou klávesnice.",
  "ru-ru": "Дополните текст с помощью клавиатуры.",
  "fr-fr": "Saisissez le texte demandé à l’aide de votre clavier.",
  "it-it": "Completa il testo attraverso la tastiera.",
  "pl-pl": "Wpisz tekst, używając swojej klawiatury.",
  "vi-vn": "Điền bằng bàn phím.",
  "tr-tr": "Metni klavyenizi kullanarak yaziniz.",
  "lt-lt": "Įveskite tekstą pasinaudodami klaviatūra.",
  "zh-cn": "使用您的键盘输入文本.",
  "bg-bg": "Напишете текста посредство клавиатурата си.",
  "bs": "Type in the text using your keyboard.",
  "ar-sa": "أكتب في النص مستخدماً لوح المفاتيح الخاص بك",
};
export default { th112, tp17, tli38, tli39 };