import { ILocItem } from "rw-lib/loc";
const th114: ILocItem = {
  "en-gb": "FILLING IN FROM A MENU",
  "de-de": "EINSATZ VON OBJEKTEN AUS DEM MENÜ",
  "sp-sp": "FILLING IN FROM A MENU",
  "cs-cz": "DOPLŇOVÁNÍ POLOŽEK Z NABÍDKY",
  "sk-sk": "DIKTÁT",
  "ru-ru": "ДИКТАНТ",
  "fr-fr": "DICTÉE",
  "it-it": "DETTATO",
  "pl-pl": "DYKTANDO",
  "vi-vn": "FILLING IN FROM A MENU",
  "tr-tr": "DİKTE ETMEK",
  "lt-lt": "DIKTANTAS",
  "zh-cn": "FILLING IN FROM A MENU",
  "bg-bg": "ДИКТОВКА",
  "bs": "FILLING IN FROM A MENU",
  "ar-sa": "ملء الفراغات من لائحة",
};
const tp21: ILocItem = {
  "en-gb": "Your task is to fill in the empty boxes within the text. You are given a list of items with different properties as described below:",
  "de-de": "Gehen Sie folgendermassen vor:",
  "sp-sp": "Realizar de la manera siguiente:",
  "cs-cz": "Vaším úkolem je vyplnit prázdná okénka v textu. Máte k dispozici seznam položek, který se může chovat následovně:",
  "sk-sk": "Postupujte nasledovne:",
  "ru-ru": "Сделайте это следующим образом:",
  "fr-fr": "Comment faire :",
  "it-it": "Prosegui secondo le istruzioni:",
  "pl-pl": "Postępuj w następujący sposób:",
  "vi-vn": "Cách làm như sau:",
  "tr-tr": "Aşağıdakileri uygulayın:",
  "lt-lt": "Tęskite kaip nurodyta:",
  "zh-cn": "操作如下:",
  "bg-bg": "Действайте по следния начин:",
  "bs": "Your task is to fill in the empty boxes within the text. You are given a list of items with different properties as described below:",
  "ar-sa": "قم بما يلي :",
};
const tli45: ILocItem = {
  "en-gb": "after filling in to the text, the item in the menu is deactivated",
  "de-de": "nach dem Einsatz im Text wird das Objekt in der Liste deaktiviert",
  "sp-sp": "after filling in to the text, the item in the menu is deactivated",
  "cs-cz": "po doplnění do textu bude položka v seznamu deaktivována",
  "sk-sk": "Kliknite do prázdneho okienka - objaví sa blikajúci kurzor.",
  "ru-ru": "Кликнете в пустом окошечке - появится мигающий курсор.",
  "fr-fr": "Cliquez dans une cellule vide. Un curseur apparaît.",
  "it-it": "Clicca sulla casella vuota – verrà visualizzato il cursore lampeggiante.",
  "pl-pl": "Kliknij w puste miejsce - pojawi się migający kursor.",
  "vi-vn": "after filling in to the text, the item in the menu is deactivated",
  "tr-tr": "Boş alana tıklayın - yanıp sönen ışıklı bir gösterge ortaya çıkacaktır.",
  "lt-lt": "Paspauskite ant tuščio tarpo - atsiras mirksintis kursorius.",
  "zh-cn": "after filling in to the text, the item in the menu is deactivated",
  "bg-bg": "Кликнете в празното място в групата - появява се мигащ курсор.",
  "bs": "after filling in to the text, the item in the menu is deactivated",
  "ar-sa": "بعد ملئ الفراغات في النص سيتم إلغاء العنصر من اللائحة",
};
const tli46: ILocItem = {
  "en-gb": "after filling in, the item in the list is not deactivated and can be used again",
  "de-de": "das Objekt bleibt nach dem Einsetzen im Text aktiv und kann wiederholt verwendet werden",
  "sp-sp": "after filling in, the item in the list is not deactivated and can be used again",
  "cs-cz": "položka zůstane po doplnění do textu aktivní a bude moci být opakovaně použita",
  "sk-sk": "Doplňte text, ktorý počujete, pomocou klávesnice.",
  "ru-ru": "Дополните текст, который вы слышите, с помощью клавиатуры.",
  "fr-fr": "Saisissez le texte que vous entendez à l\u0027aide du clavier.",
  "it-it": "Attraverso la tastiera completa il testo sentito.",
  "pl-pl": "Wpisz tekst, który słyszysz.",
  "vi-vn": "after filling in, the item in the list is not deactivated and can be used again",
  "tr-tr": "Duydugunuz metini yaziniz.",
  "lt-lt": "Įveskite tekstą taip, kaip jį girdite.",
  "zh-cn": "after filling in, the item in the list is not deactivated and can be used again",
  "bg-bg": "Напишете текста, който чувате.",
  "bs": "after filling in, the item in the list is not deactivated and can be used again",
  "ar-sa": "لا تلغي العنصر من القائمة بعد ملئ الفراغات و إنما حافظ على إمكانية استخدامه مرة أخرى",
};
const tp22: ILocItem = {
  "en-gb": "Proceed as follows:",
  "de-de": "Um das Objekt von der Lücke zurück in die Liste zu geben, klicken Sie es an oder ziehen Sie ein anderes Objekt von der Lise.",
  "sp-sp": "Para editar el campo, arrastre otro objeto de la lista hacia dicho campo.",
  "cs-cz": "Postupujte následovně:",
  "sk-sk": "Pokiaľ chcete doplnenú položku zmeniť, pretiahnite na jej miesto inú.",
  "ru-ru": "Если вы хотите заполненный пункт поменять, перетяните на это место другой.",
  "fr-fr": "Si vous souhaitez modifier une réponse, déposez une nouvelle étiquette dans la cellule.",
  "it-it": "Per modificare la voce trascina al posto di quest’ultima un\u0027altra voce.",
  "pl-pl": "Aby przypomnieć swój wybór, wybierz i przeciągnij w to miejsce inny element z listy.",
  "vi-vn": "Để rút lại lựa chọn, bạn chọn và kéo một mục khác từ danh sách thay vào vị trí đó.",
  "tr-tr": "Seçimlerinizi geri çekmek için, ögeyi seçin ve listeden farkli bir ögeyi onun yerine sürükleyin.",
  "lt-lt": "Norėdami atšaukti savo pasirinkimą, pasirinkite ir tempkite kitą elementą iš sąrašo ir tempkite į tą vietą.",
  "zh-cn": "恢复您的选择, 请从列表选择并拖曳一个不同的项目至它的位置.",
  "bg-bg": "За да върнете избора си, изберете и влачете различни позиции от списъка до местата им.",
  "bs": "Proceed as follows:",
  "ar-sa": "للتراجع عن خيار أجريته قم بإختيار عنصر آخر من القائمة و اسحبه إلى مكانه",
};
const tli47: ILocItem = {
  "en-gb": "Click on the empty gap - a menu with items appears",
  "de-de": "Klicken Sie auf das leere Fenster - er erscheint ein Objektmenü.",
  "sp-sp": "Click on the empty gap - a menu with items appears",
  "cs-cz": "Klikněte do prázdného okénka - objeví se nabídka s položkami.",
  "sk-sk": "Kliknite na text, ktorý chcete zmeniť - objaví sa blikajúci kurzor.",
  "ru-ru": "Кликнете на текст, который вы хотите поменять - появится мигающий курсор.",
  "fr-fr": "Cliquez dans la cellule souhaitée.",
  "it-it": "Clicca sul testo da modificare – verrà visualizzato il cursore lampeggiante.",
  "pl-pl": "Kliknij na tekst, który chcesz zmienić - pojawi się migający kursor.",
  "vi-vn": "Click on the empty gap - a menu with items appears",
  "tr-tr": "Kaldırmak istediğiniz metni tıklayın. Metin renkli olarak vurgulanacaktır.",
  "lt-lt": "Spustelėkite tekstą, kurį norite pakeisti - atsiras mirksintis žymeklis.",
  "zh-cn": "Click on the empty gap - a menu with items appears",
  "bg-bg": "Кликнете върху текста, който искате да промените - появява се мигащ курсор.",
  "bs": "Click on the empty gap - a menu with items appears",
  "ar-sa": "أنقر على المكان الفارغ لتظهر لك لائحة من العناصر",
};
const tli48: ILocItem = {
  "en-gb": "Click a selected item. It will be filled in to the gap.",
  "de-de": "Klicken Sie auf das gewählte Objekt. Das Objekt erscheint im Fenster.",
  "sp-sp": "Click a selected item. It will be filled in to the gap.",
  "cs-cz": "Klikněte na vybranou položku. Položka se doplní do okénka.",
  "sk-sk": "Doplňte text správne.",
  "ru-ru": "Дополните правильно текст.",
  "fr-fr": "Saisissez le nouveau texte corrigé à l’aide de votre clavier.",
  "it-it": "Completa correttamente il testo.",
  "pl-pl": "Wpisz poprawny tekst.",
  "vi-vn": "Click a selected item. It will be filled in to the gap.",
  "tr-tr": "Dogru metini yaziniz.",
  "lt-lt": "Įveskite teisingą tekstą.",
  "zh-cn": "Click a selected item. It will be filled in to the gap.",
  "bg-bg": "Напишете правилния текст.",
  "bs": "Click a selected item. It will be filled in to the gap.",
  "ar-sa": "أنقر على العنصر الذي حددته ليتم ملئ الفراغ به",
};
const tp23: ILocItem = {
  "en-gb": "To change the filled in item, fill in another one into its place.",
  "de-de": "Ihre Aufgabe ist es, die leeren Lücken im Text zu füllen. Eine Liste mit Objekten mit verschiedenen Verhaltensweisen, wie unten beschrieben, ist gegeben:",
  "sp-sp": "Su tarea es rellenar los espacios vacíos en el texto. Más abajo dispone de una lista de elementos con diferentes comportamientos:",
  "cs-cz": "Pokud chcete doplněnou položku změnit, doplňte na její místo jinou.",
  "sk-sk": "Vašou úlohou je vyplniť prázdne okienka v texte. Máte k dispozícii zoznam položiek, ktorý sa môže chovať nasledovne:",
  "ru-ru": "Ваше задание - заполнить пустые окошечки в тексте. У вас есть список пунктов, который может быть использован следующим образом:",
  "fr-fr": "Vous devez ici compléter les cellules vides à l’aide des étiquettes disponibles. Après utilisation, l’étiquette est soit :",
  "it-it": "Il tuo compito è completare le caselle vuote nel testo. A disposizione c’è l’elenco delle voci con le caratteristiche diverse descritte di seguito:",
  "pl-pl": "Twoim zadaniem jest wpisanie tekstu w puste pola. Dostajesz listę elementów z różnymi właściwościami, jak opisano poniżej:",
  "vi-vn": "Điền từ vào chỗ trống trong văn bản. Bạn được cho trước một danh sách các mục với các thuộc tính khác nhau như mô tả dưới đây:",
  "tr-tr": "Göreviniz metin içindeki boş kutucuklari doldurmaktir. Aşagida açiklandigi gibi, size farkli özellikleri olan bir öge listesi verilmiştir:",
  "lt-lt": "Tavo užduotis yra užpildyti tuščius langelius. Pasinaudok duotu sąrašu ir skirtingais pasirinkimais, kurie įvardinti apačioje:",
  "zh-cn": "您的任务是在空格填写文本. 您会得到一列如以下描述的不同属性项目:",
  "bg-bg": "Вашата задача е да попълните празните кутийки в текста. Имате даден списък с думи и изрази с различни свойства, описани по-долу:",
  "bs": "To change the filled in item, fill in another one into its place.",
  "ar-sa": "مهمتك هي أن تملأ الفراغات في الصناديق الخالية ضمن النص. سيتم إعطاؤك قائمة من العناصر بخصوصيات مختلفة كما هو موضح لاحقاً:",
};
export default { th114, tp21, tli45, tli46, tp22, tli47, tli48, tp23 };