import { ILocItem } from "rw-lib/loc";
const th113: ILocItem = {
  "en-gb": "FILLING IN FROM A LIST (DRAG \u0026amp; DROP)",
  "de-de": "AUSFÜLLEN VON EINER LISTE (DRAG \u0026amp; DROP)",
  "sp-sp": "ARRASTRAR DE LA LISTA Y COMPLETAR (DRAG \u0026amp; DROP)",
  "cs-cz": "PŘETAHOVÁNÍ",
  "sk-sk": "PREŤAHOVANIE",
  "ru-ru": "ПЕРЕТЯГИВАНИЕ",
  "fr-fr": "GLISSER-DÉPOSER",
  "it-it": "TRASCINAMENTO",
  "pl-pl": "UZUPEŁNIANIE Z LISTY (PRZECIĄGNIJ I UPUŚĆ)",
  "vi-vn": "ĐIỀN VÀO CHỖ TRỐNG TỪ MỘT DANH SÁCH CHO TRƯỚC (KÉO VÀ THẢ)",
  "tr-tr": "BİR LİSTEDEN DOLDURMAK (SÜRÜKLEYİP BIRAKMAK)",
  "lt-lt": "PILDYMAS IŠ SĄRAŠO (TEMPKITE \u0026amp; PADĖKITE)",
  "zh-cn": "从清单填充 (拖放)",
  "bg-bg": "ПОПЪЛВАНЕ ОТ СПИСЪК (ТЕГЛЕНЕ И ПУСКАНЕ)",
  "bs": "FILLING IN FROM A LIST (DRAG \u0026amp; DROP)",
  "ar-sa": "ملء الفراغات من قائمة (عن الطريق السحب و الإفلات)",
};
const tp18: ILocItem = {
  "en-gb": "Your task is to fill in the empty boxes within the text. You are given a list of items with different properties as described below:",
  "de-de": "Ihre Aufgabe ist es, die leeren Lücken im Text zu füllen. Manchmal ist eine Liste von Objekten gegeben, die Ihnen helfen sollen. Gehen Sie folgendermassen vor:",
  "sp-sp": "Su tarea es rellenar los espacios vacíos en el texto. En algunos casos dispone de una lista de elementos que le servirán de ayuda. Proceda de la siguiente manera:",
  "cs-cz": "Vaším úkolem je vyplnit prázdná okénka v textu. Máte k dispozici seznam položek, který se může chovat následovně:",
  "sk-sk": "Vašou úlohou je vyplniť prázdne okienka v texte. Niekedy máte k dispozícii zoznam slovíčok, ktoré Vám pomôžu pri vyplňovaní. Postupujte nasledovne:",
  "ru-ru": "Ваше задание - заполнить пустые окошечки в тексте. Иногда у вас есть список слов, который вам поможет при заполнении. Действуйте следующим образом:",
  "fr-fr": "Vous devez ici remplir vous-même les cellules vides. Vous bénéficierez parfois d’une aide.",
  "it-it": "Il tuo compito è completare le caselle vuote nel testo. A volte c’è a disposizione l’elenco dei vocaboli utili per il tuo compito. Prosegui secondo le istruzioni:",
  "pl-pl": "Twoim zadaniem jest wpisanie tekstu w puste pola. Czasami dostajesz listę słówek, aby pomóc ci w zadaniu. Postępuj w następujący sposób:",
  "vi-vn": "Bạn hãy điền từ thích hợp vào các chỗ trống trong đoạn văn bản. Đôi khi bạn được biết trước danh sách các từ cần điền. Cách làm như sau:",
  "tr-tr": "Göreviniz metindeki boş kutucuklari doldurmaktir. Bazen görevinize yardim etmek için bir kelime listesi verilecektir. Aşagidakileri uygulayin:",
  "lt-lt": "Tavo užduotis yra užpildyti tuščius langelius tekstu. Kartais bus duotas sąrašas žodžių, kurie padės atlikti užduotį. Darykite taip:",
  "zh-cn": "您的任务是在空格填写文本. 有时您会得到一列单词来帮助您的任务. 操作如下:",
  "bg-bg": "Вашата задача е да попълните празните кутийки в текста. В някои случаи имате даден списък с думи, които да Ви помогнат с изпълнението на задачата. Действайте по следния начин:",
  "bs": "Your task is to fill in the empty boxes within the text. You are given a list of items with different properties as described below:",
  "ar-sa": "مهمتك هي أن تملأ الفراغات في الصناديق الخالية ضمن النص. أحياناً ستعطى قائمة من الكلمات لتساعدك في إتمام مهمتك . قم بما يلي:",
};
const tli40: ILocItem = {
  "en-gb": "after dragging, the item in the list will be deactivated",
  "de-de": "nach dem Ziehen ist das Objekt in der Liste deaktiviert",
  "sp-sp": "Después de arrastrar el elemento al texto, dicho elemento, aparecerá en la lista desactivado.",
  "cs-cz": "po přetažení do textu bude položka v seznamu deaktivována",
  "sk-sk": "po pretiahnutí do textu bude položka v zozname deaktivovaná",
  "ru-ru": "после перетягивания текста пункт будет в списке дезактивирован",
  "fr-fr": "Désactivée,",
  "it-it": "una volta trascinata nel testo, la voce viene disattivata nell’elenco",
  "pl-pl": "po przeciągnięciu element na liście zostanie zdezaktywowany",
  "vi-vn": "Sau khi kéo ra, mục đó sẽ bị khóa trong danh sách.",
  "tr-tr": "sürükledikten sonra, listedeki madde etkisiz hale getirilir",
  "lt-lt": "Nutempus, elementas sąraše bus išjungtas",
  "zh-cn": "拖曳后, 列表中的项目将失效",
  "bg-bg": "след влаченето, позицията в списъка ще бъде деактивирана.",
  "bs": "after dragging, the item in the list will be deactivated",
  "ar-sa": "بعد سحب العنصر سيلغى من القائمة",
};
const tli41: ILocItem = {
  "en-gb": "after dragging, the item in the list is not deactivated and can be used again",
  "de-de": "nach dem Ziehen ist das Objekt nicht deaktiviert und kann wieder gebraucht werden",
  "sp-sp": "Después de arrastrar el elemento al texto, este seguirá activado y podrá ser usado nuevamente.",
  "cs-cz": "položka zůstane po přetažení do textu aktivní a bude moci být opakovaně použita",
  "sk-sk": "položka zostane po pretiahnutí do textu aktívna a bude môcť byť opakovane použitá",
  "ru-ru": "пункт после перетягивания текста останется активным, и будет возможно его повторно использовать",
  "fr-fr": "ou toujours active et peut être déplacée de nouveau.",
  "it-it": "la voce rimane attiva anche dopo essere trascinata e potrà essere riutilizzata",
  "pl-pl": "po przeciągnięciu element na liście nie jest dezaktywowany i może być użyty ponownie",
  "vi-vn": "Sau khi kéo ra, nếu mục đó không bị khóa trong danh sách thì nó có thể được dùng lần nữa.",
  "tr-tr": "sürükledikten sonra, listedeki madde etkisiz hale getirilmez ve tekrar kullanılabilir",
  "lt-lt": "Nutempus, elementas sąraše nėra išjungiamas ir vėl gali būti naudojamas",
  "zh-cn": "拖曳后, 列表中的项目就不是失效的, 并可再次使用",
  "bg-bg": "след влаченето, позицията в списъка няма да бъде деактивирана и може да се използва отново.",
  "bs": "after dragging, the item in the list is not deactivated and can be used again",
  "ar-sa": "لا تلغي العنصر بعد سحبه من القائمة و إنما حافظ على إمكانية استخدامه مرة أخرى",
};
const tp19: ILocItem = {
  "en-gb": "Proceed as follows:",
  "de-de": "Um ein Objekt zu bearbeiten, klicken Sie es an und korrigieren Sie es.",
  "sp-sp": "Para editar un campo haga clic sobre el mismo y corríjalo.",
  "cs-cz": "Postupujte následovně:",
  "sk-sk": "Pokiaľ chcete opraviť už doplnenú položku, kliknite do okienka a položku opravte.",
  "ru-ru": "Если вы хотите исправить уже дополненный пункт, щёлкните на окошечко и исправьте пункт.",
  "fr-fr": "Si vous voulez corriger une cellule déjà complétée, cliquez dedans et saisissez votre nouvelle réponse.",
  "it-it": "Se vuoi correggere una voce già compilata, clicca nella casella e modifica la voce.",
  "pl-pl": "Aby edytować element, wybierz go i wprowadź zmianę.",
  "vi-vn": "Để chữa một mục, nhấn chuột lên nó và sửa lại.",
  "tr-tr": "Ögeyi düzenlemek için, onu seçin ve düzeltmeyi yapin.",
  "lt-lt": "Norėdami redaguoti elementą, pasirinkite jį ir atlikite pataisymą.",
  "zh-cn": "编辑该项目, 请先选择再进行订正.",
  "bg-bg": "За да редактирате позиция, изберете я и направете корекциите.",
  "bs": "Proceed as follows:",
  "ar-sa": "لتحرير العنصر قم بتحديده أولاً ثم أجري التصحيح.",
};
const tli42: ILocItem = {
  "en-gb": "Click an item in the list. It will be highlighted.",
  "de-de": "Klicken Sie einen Artikel in der Liste an. Es wird hervorgehoben.",
  "sp-sp": "Haga clic en un elemento de la lista. Este aparecerá resaltado.",
  "cs-cz": "Klikněte na položku v seznamu. Položka se zvýrazní.",
  "sk-sk": "Kliknite na položku v zozname. Položka sa zvýrazní.",
  "ru-ru": "Кликнете на пункт в списке. Пункт выделится.",
  "fr-fr": "Pour sélectionner une étiquette, cliquez dessus.",
  "it-it": "Clicca sulla voce dell’elenco. La voce viene marcata.",
  "pl-pl": "Kliknij na element znajdujący się na liście. Element zostanie wyróżniony.",
  "vi-vn": "Nhấn chuột lên một mục trong danh sách. Nó sẽ được đánh dấu.",
  "tr-tr": "Listedeki maddelerden birini tıklayın. Renkli olarak vurgulanacaktır.",
  "lt-lt": "Spustelėkite elementą sąraše. Tai bus paryškintos.",
  "zh-cn": "按一下清单中的项目. 这将会突出显示.",
  "bg-bg": "Кликнете върху позиция от списъка. Тя ще бъде засветена.",
  "bs": "Click an item in the list. It will be highlighted.",
  "ar-sa": "Click an item in the list. It will be highlighted.",
};
const tli43: ILocItem = {
  "en-gb": "Hold the left mouse button down and drag the item to the empty gap.",
  "de-de": "Halten Sie die linke Maustaste gedrückt und ziehen Sie den Artikel auf die leere Lücke.",
  "sp-sp": "Mantenga presionado el botón izquierdo del ratón y arrastre el objeto al espacio vacío.",
  "cs-cz": "Držte tlačítko myši stisknuté a přesuňte položku (pohybem myši) nad prázdné okénko.",
  "sk-sk": "Držte tlačidlo myši stlačené a presuňte položku (pohybom myši) nad prázdne okienko.",
  "ru-ru": "Держите нажатой кнопку мыши и перетащите пункт (движением мыши) на пустое окошечко.",
  "fr-fr": "Maintenez le bouton de la souris enfoncé et glissez l’étiquette dans la cellule choisie.",
  "it-it": "Tieni premuto il pulsante del mouse e trascina la voce (muovendo il mouse) nella casella vuota.",
  "pl-pl": "Przytrzymaj lewy przycisk myszki i przeciągnij element w puste miejsce.",
  "vi-vn": "Giữ chuột trái và kéo mục đó vào chỗ trống.",
  "tr-tr": "Mouse\u0027un sol tuşuna basılı tutun ve öğeyi boş alana sürükleyin.",
  "lt-lt": "Laikydami kairįjį pelės mygtuką vilkite elementą į tuščią spragą.",
  "zh-cn": "按住鼠标左键并拖曳项目至空格处.",
  "bg-bg": "Натиснете продължително левия бутон на мишката и влачете позицията до празното място.",
  "bs": "Hold the left mouse button down and drag the item to the empty gap.",
  "ar-sa": "استمر في الضغط على زر الفارة الأيسر و اسحب العنصر إلى المكان الفارغ",
};
const tli44: ILocItem = {
  "en-gb": "Release the left mouse button. The item will be moved.",
  "de-de": "Lassen Sie die linke Maustaste los. Das Artikel wird bewegt.",
  "sp-sp": "Libere el botón izquierdo del ratón. El elemento se moverá a la ventana.",
  "cs-cz": "Uvolněte kurzor myši. Položka se přesune do okénka.",
  "sk-sk": "Uvoľnite kurzor myši. Položka sa presunie do okienka.",
  "ru-ru": "Отпустите левую кнопку мыши. Пункт переместится в окошечко.",
  "fr-fr": "Relâchez le bouton de la souris pour placer l’étiquette.",
  "it-it": "Rilascia il cursore del mouse. La voce viene trascinata nella casella.",
  "pl-pl": "Puść lewy przycisk myszki. Element zostanie przeniesiony.",
  "vi-vn": "Thả chuột trái. Mục đó sẽ được di chuyển.",
  "tr-tr": "Mouse\u0027un sol tuşunu bırakın. Öğe taşınmış olacaktır.",
  "lt-lt": "atleiskite kairįjį pelės mygtuką. Elementas bus perkeltas",
  "zh-cn": "放开鼠标左键. 该项目将被移动.",
  "bg-bg": "Отпуснете левия бутон на мишката. Ще бъде преместена.",
  "bs": "Release the left mouse button. The item will be moved.",
  "ar-sa": "أفلت زر الفارة الأيسر و سيتم نقل العنصر",
};
const tp20: ILocItem = {
  "en-gb": "To recall your selection, select and drag a different item from the list into its place.",
  "de-de": "Ihre Aufgabe ist es, die leeren Lücken im Text zu füllen. Eine Liste mit Objekten mit verschiedenen Verhaltensweisen, wie unten beschrieben, ist gegeben:",
  "sp-sp": "Su tarea es rellenar los espacios vacíos en el texto. Más abajo dispone de una lista de elementos con diferentes comportamientos:",
  "cs-cz": "Pokud chcete doplněnou položku změnit, přetáhněte na její místo jinou.",
  "sk-sk": "Vašou úlohou je vyplniť prázdne okienka v texte. Máte k dispozícii zoznam položiek, ktorý sa môže chovať nasledovne:",
  "ru-ru": "Ваше задание - заполнить пустые окошечки в тексте. У вас есть список пунктов, который может быть использован следующим образом:",
  "fr-fr": "Vous devez ici compléter les cellules vides à l’aide des étiquettes disponibles. Après utilisation, l’étiquette est soit :",
  "it-it": "Il tuo compito è completare le caselle vuote nel testo. A disposizione c’è l’elenco delle voci con le caratteristiche diverse descritte di seguito:",
  "pl-pl": "Twoim zadaniem jest wpisanie tekstu w puste pola. Dostajesz listę elementów z różnymi właściwościami, jak opisano poniżej:",
  "vi-vn": "Điền từ vào chỗ trống trong văn bản. Bạn được cho trước một danh sách các mục với các thuộc tính khác nhau như mô tả dưới đây:",
  "tr-tr": "Göreviniz metin içindeki boş kutucuklari doldurmaktir. Aşagida açiklandigi gibi, size farkli özellikleri olan bir öge listesi verilmiştir:",
  "lt-lt": "Tavo užduotis yra užpildyti tuščius langelius. Pasinaudok duotu sąrašu ir skirtingais pasirinkimais, kurie įvardinti apačioje:",
  "zh-cn": "您的任务是在空格填写文本. 您会得到一列如以下描述的不同属性项目:",
  "bg-bg": "Вашата задача е да попълните празните кутийки в текста. Имате даден списък с думи и изрази с различни свойства, описани по-долу:",
  "bs": "To recall your selection, select and drag a different item from the list into its place.",
  "ar-sa": "مهمتك هي أن تملأ الفراغات في الصناديق الخالية ضمن النص. سيتم إعطاؤك قائمة من العناصر بخصوصيات مختلفة كما هو موضح لاحقاً:",
};
export default { th113, tp18, tli40, tli41, tp19, tli42, tli43, tli44, tp20 };