import { toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th125: DLoc.ILocItem = {
  'en-gb': 'LISTEN \u0026amp; TALK',
  'de-de': 'LISTEN \u0026amp; TALK',
  'sp-sp': 'LISTEN \u0026amp; TALK',
  'cs-cz': 'LISTEN \u0026amp; TALK',
  'sk-sk': 'LISTEN \u0026amp; TALK',
  'ru-ru': 'LISTEN \u0026amp; TALK',
  'fr-fr': 'LISTEN \u0026amp; TALK',
  'it-it': 'LISTEN \u0026amp; TALK',
  'pl-pl': 'LISTEN \u0026amp; TALK',
  'vi-vn': 'LISTEN \u0026amp; TALK',
  'tr-tr': 'LISTEN \u0026amp; TALK',
  'lt-lt': 'LISTEN \u0026amp; TALK',
  'zh-cn': 'LISTEN \u0026amp; TALK',
  'bg-bg': 'LISTEN \u0026amp; TALK',
  'bs': 'LISTEN \u0026amp; TALK',
  'ar-sa': 'استمع و تكلم',
};
const tp34: DLoc.ILocItem = {
  'en-gb': 'When practicing your pronunciation, proceed as follows:',
  'de-de': 'Für das Abspielen von Videos können Sie die folgenden Bedienelemente nutzen, welche Sie in der unteren Menüleiste unter dem Video vorfinden.',
  'sp-sp': 'When practicing your pronunciation, proceed as follows:',
  'cs-cz': 'Při provičování výslovnosti postupujte následovně:',
  'sk-sk': 'When practicing your pronunciation, proceed as follows:',
  'ru-ru': 'When practicing your pronunciation, proceed as follows:',
  'fr-fr': 'When practicing your pronunciation, proceed as follows:',
  'it-it': 'When practicing your pronunciation, proceed as follows:',
  'pl-pl': 'When practicing your pronunciation, proceed as follows:',
  'vi-vn': 'When practicing your pronunciation, proceed as follows:',
  'tr-tr': 'When practicing your pronunciation, proceed as follows:',
  'lt-lt': 'When practicing your pronunciation, proceed as follows:',
  'zh-cn': 'When practicing your pronunciation, proceed as follows:',
  'bg-bg': 'When practicing your pronunciation, proceed as follows:',
  'bs': 'When practicing your pronunciation, proceed as follows:',
  'ar-sa': 'لتشغيل الفيديو يمكنك استخدام أزرار التحكم التالية من لوحة التحكم :',
};
const tli74: DLoc.ILocItem = {
  'en-gb': 'Click the Play icon and listen to the original recording.',
  'de-de': 'Klicken Sie auf das Symbol Abspielen und hören Sie sich die Originalaufnahme an.',
  'sp-sp': 'Click the Play icon and listen to the original recording.',
  'cs-cz': 'Klikněte na ikonku Přehrát a poslechněte si originální nahrávku.',
  'sk-sk': 'Click the Play icon and listen to the original recording.',
  'ru-ru': 'Click the Play icon and listen to the original recording.',
  'fr-fr': 'Click the Play icon and listen to the original recording.',
  'it-it': 'Click the Play icon and listen to the original recording.',
  'pl-pl': 'Click the Play icon and listen to the original recording.',
  'vi-vn': 'Click the Play icon and listen to the original recording.',
  'tr-tr': 'Click the Play icon and listen to the original recording.',
  'lt-lt': 'Click the Play icon and listen to the original recording.',
  'zh-cn': 'Click the Play icon and listen to the original recording.',
  'bg-bg': 'Click the Play icon and listen to the original recording.',
  'bs': 'Click the Play icon and listen to the original recording.',
  'ar-sa': 'أنقر على أيقونة التشغيل لتستمع للتسجيل الصوتي الأصلي',
};
const tli75: DLoc.ILocItem = {
  'en-gb': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'de-de': 'Klicken Sie auf das Symbol Aufnehmen und nehmen Sie ihre eigene Aussprache auf.',
  'sp-sp': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'cs-cz': 'Klikněte na ikonku Nahrávat a nahrajte vlastní výslovnost. Opětovným kliknutím na ikonku nahrávání ukončíte.',
  'sk-sk': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'ru-ru': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'fr-fr': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'it-it': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'pl-pl': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'vi-vn': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'tr-tr': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'lt-lt': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'zh-cn': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'bg-bg': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'bs': 'Click the Record icon and record your own pronunciation. To stop recording, click the icon again.',
  'ar-sa': 'أنقر على أيقونة التسجيل لتقوم بتسجيل اللفظ بصوتك و لإيقاف التسجيل أنقر على الأيقونة ذاتها مرة أخرى',
};
const tli76: DLoc.ILocItem = {
  'en-gb': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'de-de': 'Klicken Sie auf das Symbol Abspielen, hören Sie sich Ihre Aufnahme an und vergleichen diese mit der Originalaufnahme.',
  'sp-sp': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'cs-cz': 'Klikněte na další ikonku Přehrát, přehrajte si svoji nahrávku a porovnejte ji s originálem.',
  'sk-sk': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'ru-ru': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'fr-fr': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'it-it': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'pl-pl': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'vi-vn': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'tr-tr': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'lt-lt': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'zh-cn': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'bg-bg': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'bs': 'Click the next Play icon, replay your recording and compare it with the original one.',
  'ar-sa': 'أنقر على أيقونة التشغيل المجاورة لإعادة تشغيل تسجيلك و قارن تسجيلك مع النسخة الأصلية.',
};
const tli77: DLoc.ILocItem = {
  'en-gb': 'Repeat the whole process until you are satisfied with the result.',
  'de-de': 'Wiederholen Sie diesen Prozess solange, bis Sie mit ihrer Aufnahme zufrieden sind.',
  'sp-sp': 'Repeat the whole process until you are satisfied with the result.',
  'cs-cz': 'Celý proces opakujte dokud nebudete se svou nahrávkou spokojeni.',
  'sk-sk': 'Repeat the whole process until you are satisfied with the result.',
  'ru-ru': 'Repeat the whole process until you are satisfied with the result.',
  'fr-fr': 'Repeat the whole process until you are satisfied with the result.',
  'it-it': 'Repeat the whole process until you are satisfied with the result.',
  'pl-pl': 'Repeat the whole process until you are satisfied with the result.',
  'vi-vn': 'Repeat the whole process until you are satisfied with the result.',
  'tr-tr': 'Repeat the whole process until you are satisfied with the result.',
  'lt-lt': 'Repeat the whole process until you are satisfied with the result.',
  'zh-cn': 'Repeat the whole process until you are satisfied with the result.',
  'bg-bg': 'Repeat the whole process until you are satisfied with the result.',
  'bs': 'Repeat the whole process until you are satisfied with the result.',
  'ar-sa': 'أعد العملية كاملة إلى أن تكون راض عن النتيجة',
};
const res = { [globId]: { th125, tp34, tli74, tli75, tli76, tli77 } };
export default res;