import { ILocItem, toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th19: ILocItem = {
  'en-gb': 'MULTIPLE CHOICE - MORE CORRECT ANSWERS',
  'de-de': 'MULTIPLE CHOICE - MEHR RICHTIGE ANTWORTEN',
  'sp-sp': 'MULTIPLE CHOICE - MÁS DE UNA RESPUESTA PUEDE SER CORRECTA',
  'cs-cz': 'VÝBĚR Z VÍCE MOŽNOSTÍ - VÍCE SPRÁVNÝCH.',
  'sk-sk': 'VÝBER Z VIACERÝCH MOŽNOSTÍ - VIAC SPRÁVNYCH.',
  'ru-ru': 'ВЫБОР ИЗ ВАРИАНТОВ - БОЛЕЕ ОДНОГО ПРАВИЛЬНОГО',
  'fr-fr': 'QCM – PLUSIEURS BONNES RÉPONSES',
  'it-it': 'SCELTA DALLE DIVERSE POSSIBILITA’ - PIÙ DI UNA POSSIBILITA’ CORRETTA',
  'pl-pl': 'WIELOKROTNY WYBÓR - WIĘCEJ POPRAWNYCH ODPOWIEDZI',
  'vi-vn': 'CHỌN NHIỀU CÂU TRẢ LỜI ĐÚNG',
  'tr-tr': 'ÇOK SEÇENEKLİ - DAHA FAZLA DOĞRU CEVAP',
  'lt-lt': 'KELI PASIRINKIMAI - DAUGIAU TEISINGŲ ATSAKYMŲ',
  'zh-cn': '多项选择 - 更多正确答案',
  'bg-bg': 'НЯКОЛКО ИЗБОРА - МНОГО ПРАВИЛНИ ОТГОВОРИ',
  'bs': 'MULTIPLE CHOICE - MORE CORRECT ANSWERS',
  'ar-sa': 'الإختيار من متعدد - عدة إجابات صحيحة',
};
const tp11: ILocItem = {
  'en-gb': 'Your task is to select (mark) correct options. None of the options are selected by default. Proceed as follows:',
  'de-de': 'Um Ihre Auswahl abzubrechen, klicken Sie noch einmal auf das gewählte Objekt.',
  'sp-sp': 'Para cancelar una selección, haga otro clic en el objeto seleccionado.',
  'cs-cz': 'Vaším úkolem je vybrat (označit) správné možnosti. Možnosti jsou na začátku neoznačené. Postupujte následovně:',
  'sk-sk': 'Opakovaným klikom označenie zrušíte.',
  'ru-ru': 'Повторным нажатием вы отмените обозначение.',
  'fr-fr': 'Pour annuler votre choix, cliquez de nouveau dans la case pour la désélectionner.',
  'it-it': 'L’indicazione viene cancellata con un clic ripetuto sulla voce.',
  'pl-pl': 'Aby anulować swój wybór, kliknij ponownie wybrany element.',
  'vi-vn': 'Để huỷ bỏ lựa chọn, nhấn chuột lên mục đã chọn một lần nữa.',
  'tr-tr': 'Seçimlerinizi iptal etmek için tekrar seçilmiş ögeyi tiklayiniz.',
  'lt-lt': 'Norėdami atšaukti pasirinkimą spauskite dar kartą ant pasirinkto elemento.',
  'zh-cn': '取消您的选择, 请再次点击选定项目.',
  'bg-bg': 'За да отмените вашия избор кликнете върху избраната позиция отново.',
  'bs': 'Your task is to select (mark) correct options. None of the options are selected by default. Proceed as follows:',
  'ar-sa': 'Your task is to select (mark) correct options. None of the options are selected by default. Proceed as follows:',
};
const tli30: ILocItem = {
  'en-gb': 'Left click the chosen item.',
  'de-de': 'Links Click auf den gewählten Artikel.',
  'sp-sp': 'Haga clic con el botón izquierdo del ratón en la opción elegida.',
  'cs-cz': 'Klikněte levým tlačítkem myši na zvolenou možnost.',
  'sk-sk': 'Kliknite ľavým tlačidlom myši na zvolenú možnosť.',
  'ru-ru': 'Кликнете левой кнопкой мыши на выбранный вариант.',
  'fr-fr': 'Cliquez dans une case quand l’affirmation correspondante vous semble correcte.',
  'it-it': 'Clicca con il tasto sinistro del mouse sull\u0027opzione scelta.',
  'pl-pl': 'Kliknij lewym przyciskiem na wybrany element.',
  'vi-vn': 'Nhấp trái chuột lên mục bạn chọn.',
  'tr-tr': 'Seçilmiş öğeyi sol tuşla tıklayın.',
  'lt-lt': 'Paspauskite kairįjį pelės mygtuką dalykui pasirinkti.',
  'zh-cn': '左键点击所选择的项目.',
  'bg-bg': 'С кликване на левия бутон тя ще бъде избрана.',
  'bs': 'Left click the chosen item.',
  'ar-sa': 'نقرة يسارية على العنصر الذي تم إختياره',
};
const tli31: ILocItem = {
  'en-gb': 'The option will be selected (marked).',
  'de-de': 'Die Option wird markiert (gewählt).',
  'sp-sp': 'The option will be selected (marked).',
  'cs-cz': 'Možnost bude vybrána (označena).',
  'sk-sk': 'Možnosť bude zvolená (označená).',
  'ru-ru': 'Вариант будет выбран (обозначен).',
  'fr-fr': 'La case est sélectionnée.',
  'it-it': 'L\u0027opzione viene marcata (contrassegnata).',
  'pl-pl': 'Opcja zostanie zaznaczona (wybrana).',
  'vi-vn': 'The option will be selected (marked).',
  'tr-tr': 'Seçenek işaretlenecektir.',
  'lt-lt': 'pasirinkimas bus pažymėtas (parinktas).',
  'zh-cn': 'The option will be selected (marked).',
  'bg-bg': 'Опцията ще бъде маркирана (избрана)',
  'bs': 'The option will be selected (marked).',
  'ar-sa': 'The option will be selected (marked).',
};
const tp12: ILocItem = {
  'en-gb': 'To cancel your selection click on selected item again.',
  'de-de': 'Ihre Aufgabe ist es, die korrekte Auswahl zu markieren. Vorgegebene Objekte sind unmarkiert. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea consiste en seleccionar (marcar) la opción correcta. Al principio los elementos están sin marcar. Proceda de la siguiente manera:',
  'cs-cz': 'Opakovaným klikem označení zrušíte.',
  'sk-sk': 'Vašou úlohou je vybrať (označiť) správne možnosti. Možnosti sú na začiatku neoznačené. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - выбрать (обозначить) правильные варианты. Варианты вначале не обозначены. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici cocher la ou les réponses correctes.',
  'it-it': 'Il tuo compito è scegliere (indicare) le opzioni corrette. Le opzioni sono all’inizio disattivate. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest wybranie (zaznaczenie) odpowiednich możliwości. Żadne z możliwości nie są wybierane domyślnie. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy lựa chọn (đánh dấu) những phương án đúng. Không có phương án nào được lựa chọn mặc định. Cách làm như sau:',
  'tr-tr': 'Göreviniz dogru seçenekleri seçmektir (işaretlemek). Hiçbir seçenek orjinalinde seçilmemiştir. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra pažymėti teisingus variantus. Nei vienas variantas nėra pasirinktas pagal nutylėjimą. Darykite taip:',
  'zh-cn': '您的任务是选择 (标记) 正确的选项. 没有选项是由系统默认值选定的. 操作如下:',
  'bg-bg': 'Вашата задача е да изберете (маркирате)правилната опция. Нито една от опциите не се избира по подразбиране. Действайте по следния начин:',
  'bs': 'To cancel your selection click on selected item again.',
  'ar-sa': 'مهمتك هي إختيار عن طريق التحديد الخيارات الصحيحة. ولا واحد من الخيارات مختار على أنه افتراضي. قم بما يلي:',
};
const res = { [globId]: { th19, tp11, tli30, tli31, tp12 } };
export default res;