import { toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th15: DLoc.ILocItem = {
  'en-gb': 'PAIRING',
  'de-de': 'PAARUNG',
  'sp-sp': 'Unir los pares',
  'cs-cz': 'PÁROVÁNÍ',
  'sk-sk': 'PÁROVANIE',
  'ru-ru': 'ПОДБОР ПАРЫ',
  'fr-fr': 'ASSOCIATION',
  'it-it': 'ACCOPPIAMENTO',
  'pl-pl': 'ŁĄCZENIE W PARY',
  'vi-vn': 'GHÉP CẶP',
  'tr-tr': 'EŞLEŞTİRME',
  'lt-lt': 'PORAVIMAS',
  'zh-cn': '配对',
  'bg-bg': 'ГРУПИРАНЕ ПО ДВОЙКИ',
  'bs': 'PAIRING',
  'ar-sa': 'توصيل الثنائيات',
};
const tp5: DLoc.ILocItem = {
  'en-gb': 'Your task is to pair the left column items with the items of the right column, so that the created pairs make sense. Proceed as follows:',
  'de-de': 'Ihre Aufgabe ist es, Artikel von der linken Kolonne, mit den Artikeln von der Rechten Kolone zu verbinden. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea es formar pares(parejas) con los elementos de las columnas izquierda y derecha. Proceda de la manera siguiente:',
  'cs-cz': 'Vaším úkolem je spojit položky z levého sloupce s položkami z pravého sloupce a vytvořit správné dvojice. Postupujte následovně:',
  'sk-sk': 'Vašou úlohou je spárovať položky z ľavého stĺpca s položkami z pravého stĺpca. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - спарить пункты из левого столбика с пунктами из правого столбика. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici relier les éléments deux par deux.',
  'it-it': 'Il tuo compito è accoppiare le voci della colonna sinistra con quelle della colonna destra. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest połączyć (ułożyć w pary) elementy znajdujące się w lewej kolumnie z elementami znajdującymi się w prawej kolumnie. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy kết nối (ghép đôi) các mục bên cột trái với các mục bên cột phải. Cách làm như sau:',
  'tr-tr': 'Sizin göreviniz sol sütundaki maddeleriyle sağ sütun maddelerini birleştirmektir (eşleştirmek). Aşağıdakileri uygulayın:',
  'lt-lt': 'Jūsų užduotis sujungti kairiojo stulpelio elementus su dešiniojo stulpelio elementais. Darykite kaip parodyta:',
  'zh-cn': '您的任务是连接 (一对) 左档项目和右档项目. 操作如下:',
  'bg-bg': 'Вие трябва да свържете (по двойки) позициите от лявата колонка с позициите от дясната колонка. Действайте по следния начин:',
  'bs': 'Your task is to pair the left column items with the items of the right column, so that the created pairs make sense. Proceed as follows:',
  'ar-sa': 'مهمتك هي أن تربط العناصر الموجودة في العمود الأيسر مع ما يقابلها في العمود الأيمن. قم بما يلي:',
};
const tli20: DLoc.ILocItem = {
  'en-gb': 'Left click an icon to select a left column item. The item will be highlighted.',
  'de-de': 'Durch Klicken auf das Symbol wählen Sie ein Objekt der linken Spalte. Das Objekt wird hervorgehoben.',
  'sp-sp': 'Left click an icon to select a left column item. The item will be highlighted.',
  'cs-cz': 'Kliknutím na ikonku vyberte položku z levého sloupce. Položka se zvýrazní.',
  'sk-sk': 'Kliknite ľavým tlačidlom myši na vybranú možnosť.',
  'ru-ru': 'Кликнете левой кнопкой мыши на выбранный вариант.',
  'fr-fr': 'Cliquez dans la case dont l’affirmation correspondante vous semble la bonne.',
  'it-it': 'Per assegnare l\u0027opzione desiderata, clicca sul tasto sinistro del mouse.',
  'pl-pl': 'Kliknij lewym przyciskiem opcję, którą chcesz wybrać.',
  'vi-vn': 'Left click an icon to select a left column item. The item will be highlighted.',
  'tr-tr': 'Seçmek istediğiniz seçeneği sol tuşla tıklayın.',
  'lt-lt': 'Paspauskite kairįjį pelės mygtuką ant pasirinkimo, kurį norite pasirinkti.',
  'zh-cn': 'Left click an icon to select a left column item. The item will be highlighted.',
  'bg-bg': 'С кликване на левия бутон избирате опция.',
  'bs': 'Left click an icon to select a left column item. The item will be highlighted.',
  'ar-sa': 'اضغط بزر الفارة الأيسر على العمود الأيسر لتحديده وسيتم تحديد العمود',
};
const tli21: DLoc.ILocItem = {
  'en-gb': 'Click on the corresponding item in the right column.',
  'de-de': 'Klicken Sie auf das entsprechende Objekt der rechten Spalte.',
  'sp-sp': 'Click on the corresponding item in the right column.',
  'cs-cz': 'Klikněte na odpovídající položku v pravém sloupci.',
  'sk-sk': 'Možnosť bude zvolená (označená).',
  'ru-ru': 'Вариант будет выбран (обозначен).',
  'fr-fr': 'La case est sélectionnée.',
  'it-it': 'L\u0027opzione viene marcata (contrassegnata).',
  'pl-pl': 'Opcja zostanie zaznaczona (wybrana).',
  'vi-vn': 'Click on the corresponding item in the right column.',
  'tr-tr': 'Seçenek işaretlenecektir.',
  'lt-lt': 'pasirinkimas bus pažymėtas (parinktas).',
  'zh-cn': 'Click on the corresponding item in the right column.',
  'bg-bg': 'Опцията ще бъде маркирана (избрана)',
  'bs': 'Click on the corresponding item in the right column.',
  'ar-sa': 'أنقر على العنصر الملائم من العمود الأيمن',
};
const tli22: DLoc.ILocItem = {
  'en-gb': 'The item from the right column will be moved next to the correspoding item from the left column.',
  'de-de': 'Das Objekt aus der rechten Spalte wird sich zum entsprechenden Objekt aus der linken Spalte verschieben.',
  'sp-sp': 'The item from the right column will be moved next to the correspoding item from the left column.',
  'cs-cz': 'Položka z pravého sloupce se přesune k dané položce z levého sloupce.',
  'sk-sk': 'Umiestnite kurzor myši na položku (časť vety, slovo, časť slova alebo slabiku), ktorú chcete označiť.',
  'ru-ru': 'Поместите курсор мыши на объект (часть предложения, слово, часть слова, слог или букву), который Вы хотите выделить.',
  'fr-fr': 'Choisissez l’endroit que vous souhaitez sélectionner.',
  'it-it': 'Posiziona il cursore del mouse sulla voce (parte della frase, parola, parte della parola, sillabe) da marcare.',
  'pl-pl': 'Umieść wskaźnik myszki nad danym elementem (częścią zdania, słowem, częścią słowa lub sylabą), który chcesz wybrać.',
  'vi-vn': 'The item from the right column will be moved next to the correspoding item from the left column.',
  'tr-tr': 'Mouse\u0027u seçmek istediğiniz öğenin (cümle parçası, kelime, kelime parçası veya hece) üzerine götürün.',
  'lt-lt': 'Pelės žymeklį nuveskite ant objekto (sakinio dalies, žodžio, žodžio dalies ar skiemens) kurį norite pasirinkti.',
  'zh-cn': 'The item from the right column will be moved next to the correspoding item from the left column.',
  'bg-bg': 'Поставете показалеца на мишката над позицията (част от изречение, дума, част от дума, сричка или буква), която искате да изберете.',
  'bs': 'The item from the right column will be moved next to the correspoding item from the left column.',
  'ar-sa': 'سيتم نقل العنصر من العمود الأيمن إلى ما يلائمه من العمود الأيسر',
};
const tli23: DLoc.ILocItem = {
  'en-gb': 'The items will be linked.',
  'de-de': 'Die Objekte werden verbunden.',
  'sp-sp': 'Los elementos se conectarán.',
  'cs-cz': 'Položky budou spojeny.',
  'sk-sk': 'Položky budú spojené.',
  'ru-ru': 'Пункты будут соединены.',
  'fr-fr': 'L’étiquette est reliée à l’élément correspondant de la colonne de gauche.',
  'it-it': 'Le voci vengono legate tra di loro.',
  'pl-pl': 'Elementy zostaną połączone.',
  'vi-vn': 'Các mục đó sẽ được kết nối.',
  'tr-tr': 'Öğeler bağlantılı olacaktır.',
  'lt-lt': 'elementai bus susieti',
  'zh-cn': '项目将被联系在一起.',
  'bg-bg': 'Двете позиции ще бъдат свързани.',
  'bs': 'The items will be linked.',
  'ar-sa': 'سيتم ربط العناصر',
};
const res = { [globId]: { th15, tp5, tli20, tli21, tli22, tli23 } };
export default res;