import { toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th14: DLoc.ILocItem = {
  'en-gb': 'PAIRING',
  'de-de': 'PAARUNG',
  'sp-sp': 'Unir los pares',
  'cs-cz': 'PÁROVÁNÍ',
  'sk-sk': 'PÁROVANIE',
  'ru-ru': 'ПОДБОР ПАРЫ',
  'fr-fr': 'ASSOCIATION',
  'it-it': 'ACCOPPIAMENTO',
  'pl-pl': 'ŁĄCZENIE W PARY',
  'vi-vn': 'GHÉP CẶP',
  'tr-tr': 'EŞLEŞTİRME',
  'lt-lt': 'PORAVIMAS',
  'zh-cn': '配对',
  'bg-bg': 'ГРУПИРАНЕ ПО ДВОЙКИ',
  'bs': 'PAIRING',
  'ar-sa': 'توصيل الثنائيات',
};
const tp4: DLoc.ILocItem = {
  'en-gb': 'It is your task to connect (pair) left column items with items of the right column. Proceed as follows:',
  'de-de': 'Ihre Aufgabe ist es, Artikel von der linken Kolonne, mit den Artikeln von der Rechten Kolone zu verbinden. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea es formar pares(parejas) con los elementos de las columnas izquierda y derecha. Proceda de la manera siguiente:',
  'cs-cz': 'Vaším úkolem je spárovat položky z levého sloupce s položkami z pravého sloupce. Postupujte následovně:',
  'sk-sk': 'Vašou úlohou je spárovať položky z ľavého stĺpca s položkami z pravého stĺpca. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - спарить пункты из левого столбика с пунктами из правого столбика. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici relier les éléments deux par deux.',
  'it-it': 'Il tuo compito è accoppiare le voci della colonna sinistra con quelle della colonna destra. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest połączyć (ułożyć w pary) elementy znajdujące się w lewej kolumnie z elementami znajdującymi się w prawej kolumnie. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy kết nối (ghép đôi) các mục bên cột trái với các mục bên cột phải. Cách làm như sau:',
  'tr-tr': 'Sizin göreviniz sol sütundaki maddeleriyle sağ sütun maddelerini birleştirmektir (eşleştirmek). Aşağıdakileri uygulayın:',
  'lt-lt': 'Jūsų užduotis sujungti kairiojo stulpelio elementus su dešiniojo stulpelio elementais. Darykite kaip parodyta:',
  'zh-cn': '您的任务是连接 (一对) 左档项目和右档项目. 操作如下:',
  'bg-bg': 'Вие трябва да свържете (по двойки) позициите от лявата колонка с позициите от дясната колонка. Действайте по следния начин:',
  'bs': 'It is your task to connect (pair) left column items with items of the right column. Proceed as follows:',
  'ar-sa': 'مهمتك هي أن تربط العناصر الموجودة في العمود الأيسر مع ما يقابلها في العمود الأيمن. قم بما يلي:',
};
const tli16: DLoc.ILocItem = {
  'en-gb': 'Click on the item in the right column that you wish to move. The item will be highlighted.',
  'de-de': 'Klicken Sie auf einen Artikel in der rechten Kolonne, den Sie bewegen möchten. Der Artikel wird hervorgehoben.',
  'sp-sp': 'Haga clic en el objeto de la columna derecha que desee mover. El objeto aparecerá resaltado.',
  'cs-cz': 'Klikněte na položku z pravého sloupce, kterou chcete přesunout. Položka se zvýrazní.',
  'sk-sk': 'Kliknite na položku z pravého stĺpca, ktorú chcete presunúť. Položka sa zvýrazní.',
  'ru-ru': 'Кликнете на пункт из правой колонки, который вы хотите переместить. Пункт выделится.',
  'fr-fr': 'Cliquez sur l’une des étiquettes de la colonne de droite pour la sélectionner.',
  'it-it': 'Clicca sulla voce da trascinare nella colonna destra. La voce viene marcata.',
  'pl-pl': 'Kliknij na element znajdujący się w prawej kolumnie, który chcesz przesunąć. Element zostanie wyróżniony.',
  'vi-vn': 'Nhấn chuột vào mục ở cột phải mà bạn muốn di chuyển. Mục đó sẽ được đánh dấu.',
  'tr-tr': 'Sağ kolonda kaldırmak istediğiniz maddeyi tıklayınç Madde renkli olarak vurgulanacaktır.',
  'lt-lt': 'Dešiniajame stulpelyje paspauskite ant elemento, kurį norite perkelti. Elementas bus paryškintas.',
  'zh-cn': '点击右栏中您想要移动的项目. 项目将被突出显示.',
  'bg-bg': 'Кликнете върху позицията в дясната колонка, която искате да преместите. Тя ще бъде засветена.',
  'bs': 'Click on the item in the right column that you wish to move. The item will be highlighted.',
  'ar-sa': 'أنقر على العنصر الذي تشاء في العمود الأيمن للإنتقال إليه. سيتم تحديد العنصر',
};
const tli17: DLoc.ILocItem = {
  'en-gb': 'Hold the left mouse button down and drag the right column item next to the corresponding left column item.',
  'de-de': 'Halten Sie die linke Maustaste gedrückt und ziehen Sie das Artikel von der rechten Kolonne neben dem korrespondierenden Artikel von der linken Kolonne.',
  'sp-sp': 'Mantenga presionado el botón izquierdo del ratón y arrastre el objeto de la columna izquierda a su correspondiente en la columna derecha.',
  'cs-cz': 'Držte tlačítko myši stisknuté a přesuňte položku (pohybem myši) na pravou stranu řádku, na kterém se nachází odpovídající položka z levého sloupce.',
  'sk-sk': 'Držte tlačidlo myši stlačené a presuňte položku (pohybom myši) na pravú stranu riadku, na ktorom sa nachádza zodpovedajúca položka z ľavého stĺpca.',
  'ru-ru': 'Держите кнопку мыши нажатой и переместите пункт (движением мыши) на правую сторону ряда, на котором находится соответствующий пункт из левой колонки.',
  'fr-fr': 'Faites-la glisser verticalement pour la placer face à l’élément de la colonne de gauche choisi.',
  'it-it': 'Tieni premuto il pulsante del mouse e trascina la voce (muovendo il mouse) sulla parte destra della riga dove si trova la relativa voce della colonna sinistra.',
  'pl-pl': 'Przytrzymaj lewy przycisk myszki i przeciągnij element z prawej kolumny obok odpowiadającego elementu w lewej kolumnie.',
  'vi-vn': 'Nhấn, giữ chuột trái và kéo mục ở cột bên phải tới cạnh mục phù hợp ở cột trái.',
  'tr-tr': 'Mouse\u0027un sol tuşuna basılı tutun ve sağ sütundaki öğeyi sol sütundaki karşılığı olan yere sürükleyin.',
  'lt-lt': 'Laikydami kairįjį pelės mygtuką vilkite dešinio stulpelio elementą šalia atitinkamo kairiojo stulpelio elemento.',
  'zh-cn': '按住鼠标左键并拖曳右档项目至相应的左档项目旁边.',
  'bg-bg': 'Натиснете продължително левия бутон на мишката и влачете позицията от дясната колонка до съответсващата позиция в лявата колонка.',
  'bs': 'Hold the left mouse button down and drag the right column item next to the corresponding left column item.',
  'ar-sa': 'استمر في الضغط على الزر الأيسر للفارة و اسحب العنصر من العمود الأيمن إلى ما يلائمه في العمود الأيسر',
};
const tli18: DLoc.ILocItem = {
  'en-gb': 'Release the left mouse button.',
  'de-de': 'Lassen Sie die linke Maustaste los.',
  'sp-sp': 'Libere el botón izquierdo del ratón',
  'cs-cz': 'Uvolněte kurzor myši.',
  'sk-sk': 'Uvoľnite kurzor myši.',
  'ru-ru': 'Отпустите левую кнопку мыши.',
  'fr-fr': 'Relâchez le bouton de la souris pour placer l’étiquette.',
  'it-it': 'Rilascia il cursore del mouse.',
  'pl-pl': 'Puść lewy przycisk myszki.',
  'vi-vn': 'Thả chuột trái.',
  'tr-tr': 'Mouse\u0027un sol tuşunu bırakın.',
  'lt-lt': 'atleiskite kairįjį pelės mygtuką.',
  'zh-cn': '放开鼠标左键.',
  'bg-bg': 'Отпуснете левия бутон на мишката.',
  'bs': 'Release the left mouse button.',
  'ar-sa': 'أفلت زر الفارة الأيسر',
};
const tli19: DLoc.ILocItem = {
  'en-gb': 'The items will be linked.',
  'de-de': 'Die Objekte werden verbunden.',
  'sp-sp': 'Los elementos se conectarán.',
  'cs-cz': 'Položky budou spojeny.',
  'sk-sk': 'Položky budú spojené.',
  'ru-ru': 'Пункты будут соединены.',
  'fr-fr': 'L’étiquette est reliée à l’élément correspondant de la colonne de gauche.',
  'it-it': 'Le voci vengono legate tra di loro.',
  'pl-pl': 'Elementy zostaną połączone.',
  'vi-vn': 'Các mục đó sẽ được kết nối.',
  'tr-tr': 'Öğeler bağlantılı olacaktır.',
  'lt-lt': 'elementai bus susieti',
  'zh-cn': '项目将被联系在一起.',
  'bg-bg': 'Двете позиции ще бъдат свързани.',
  'bs': 'The items will be linked.',
  'ar-sa': 'سيتم ربط العناصر',
};
const res = { [globId]: { th14, tp4, tli16, tli17, tli18, tli19 } };
export default res;