import { toGlobId } from 'rw-lib/index'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th11: DLoc.ILocItem = {
  'en-gb': 'PICTURE SEQUENCING',
  'de-de': 'BILDER SEQUENTIALISIEREN',
  'sp-sp': 'SECUENCIA DE IMÁGENES',
  'cs-cz': 'ŘAZENÍ OBRÁZKŮ',
  'sk-sk': 'RADENIE OBRÁZKOV',
  'ru-ru': 'ПОРЯДОК ИЗОБРАЖЕНИЙ',
  'fr-fr': 'CLASSEMENT D’IMAGES',
  'it-it': 'SEQUENZA DELLE FIGURE',
  'pl-pl': 'UKŁADANIE ZDJĘĆ',
  'vi-vn': 'SẮP XẾP TRANH',
  'tr-tr': 'RESİM SIRALAMA',
  'lt-lt': 'PAVEIKSLĖLIŲ EILĖS NUSTATYMAS',
  'zh-cn': '图片排序',
  'bg-bg': 'ПОСЛЕДОВАТЕЛНОСТ НА КАРТИНИТЕ',
  'bs': 'PICTURE SEQUENCING',
  'ar-sa': 'ترتيب صور',
};
const tp1: DLoc.ILocItem = {
  'en-gb': 'Your task is to put the pictures into correct order. Proceed as follows:',
  'de-de': 'Ihre Aufgabe ist es, die Bilder in die richtige Reihenfolge zu setzen. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea es poner las imágenes en orden. Proceda de la siguiente manera:',
  'cs-cz': 'Vaším úkolem je seřadit obrázky do správného pořadí. Postupujte následovně:',
  'sk-sk': 'Vašou úlohou je zoradiť obrázky do správneho poradia. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - расставить картинки в правильном порядке. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici placer les images dans le bon ordre.',
  'it-it': 'Il tuo compito è mettere le figure nell\u0027ordine corretto. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest ułożenie obrazków w odpowiedniej kolejności. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy sắp xếp các bức tranh theo đúng thứ tự. Cách làm như sau:',
  'tr-tr': 'Göreviniz resimleri dogru siraya sokmaktir. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra sudėti nuotraukas teisinga tvarka. Darykite taip:',
  'zh-cn': '您的任务是将图片排列为正确的顺序. 操作如下:',
  'bg-bg': 'Вашата задача е да подредите картинките в правилния ред. Действайте по следния начин:',
  'bs': 'Your task is to put the pictures into correct order. Proceed as follows:',
  'ar-sa': 'مهمتك هي وضع الصور بالترتيب الصحيح. قم بمايلي:',
};
const tli4: DLoc.ILocItem = {
  'en-gb': 'Click on the picture you wish to move. The picture will be highlighted.',
  'de-de': 'Klicken Sie auf das Bild, das Sie bewegen möchten. Das Bild wird hervorgehoben.',
  'sp-sp': 'Haga clic en la imagen que desea mover. La imagen aparecerá resaltada',
  'cs-cz': 'Klikněte na obrázek, který chcete přesunout. Obrázek se zvýrazní.',
  'sk-sk': 'Kliknite na obrázok, ktorý chcete presunúť. Obrázok sa zvýrazní.',
  'ru-ru': 'Нажмите на картинку, которую хотите перенести. Изображение будет выделено.',
  'fr-fr': 'Cliquez sur l’image que vous voulez déplacer.',
  'it-it': 'Clicca sulla figura da trascinare. La figura viene marcata.',
  'pl-pl': 'Kliknij obrazek, który chcesz przesunąć. Obrazek zostanie wyróżniony.',
  'vi-vn': 'Nhấn chuột lên bức tranh mà bạn muốn di chuyển. Bức tranh sẽ được đánh dấu.',
  'tr-tr': 'Kaldırmak istediğiniz resmi tıklayın. Resim renkli olarak vurgulanacaktır.',
  'lt-lt': 'Spauskite ant paveikslėlio, kurį norite perkelti. Nuotraukos bus paryškintos.',
  'zh-cn': '点击您想要移动的图片. 图片将被突出显示.',
  'bg-bg': 'Кликнете върху картината, която искате да преместите. Тя ще бъде засветена.',
  'bs': 'Click on the picture you wish to move. The picture will be highlighted.',
  'ar-sa': 'أنقر على الصورة التي ترغب في نقلها , سيتم تحديد الصورة',
};
const tli5: DLoc.ILocItem = {
  'en-gb': 'Hold the left mouse button down and drag the picture to the right place.',
  'de-de': 'Halten Sie die linke Maustaste gedrückt und ziehen Sie das Bild auf die richtige Stelle.',
  'sp-sp': 'Mantenga presionado el botón izquierdo del ratón y arrastre la imagen a su posición correcta.',
  'cs-cz': 'Držte tlačítko myši stisknuté a přesuňte obrázek (pohybem myši) na nové místo.',
  'sk-sk': 'Držte tlačidlo myši stlačené a presuňte obrázok (pohybom myši) na nové miesto.',
  'ru-ru': 'Держите нажатой кнопку мыши и переместите картинку (движением мыши) на новое место.',
  'fr-fr': 'Maintenez le bouton de la souris enfoncé et glissez l’image à l’endroit souhaité.',
  'it-it': 'Tieni premuto il pulsante del mouse e trascina la frase (muovendo il mouse) al posto nuovo.',
  'pl-pl': 'Przytrzymaj lewy przycisk myszki i przeciągnij obrazek w odpowiednie miejsce.',
  'vi-vn': 'Nhấn, giữ chuột trái và kéo bức tranh vào đúng vị trí.',
  'tr-tr': 'Mouse\u0027un sol tuşuna basılı tutun ve resmi doğru yere sürükleyin.',
  'lt-lt': 'Laikydami kairįjį pelės mygtuką vilkite paveikslėlį į tinkamą vietą.',
  'zh-cn': '按住鼠标左键并拖曳图片至正确位置.',
  'bg-bg': 'Натиснете продължително левия бутон на мишката и влачете картинката до правилното място.',
  'bs': 'Hold the left mouse button down and drag the picture to the right place.',
  'ar-sa': 'استمر في الضغط على زر الفارة الأيسر لتسحب الصورة إلى المكان الصحيح',
};
const tli6: DLoc.ILocItem = {
  'en-gb': 'When the mouse arrow points to the right place, release the left mouse button.',
  'de-de': 'Wenn der Pfeil auf die richtige Stelle zeigt, lassen Sie die linke Maustaste los.',
  'sp-sp': 'Cuando el puntero señale el lugar correcto, suelte el botón izquierdo del ratón.',
  'cs-cz': 'Až bude kurzor myši nad místem, na které chcete obrázek přesunout, uvolněte kurzor myši.',
  'sk-sk': 'Keď bude kurzor myši nad miestom, na ktoré chcete obrázok presunúť, uvoľnite kurzor myši.',
  'ru-ru': 'Когда курсор мыши будет на том месте, куда вы хотите картинку переместить, отпустите кнопку мыши.',
  'fr-fr': 'Relâchez le bouton pour placer l’image.',
  'it-it': 'Nel momento in cui il cursore del mouse sarà impostato sul posto dove si desidera impostare la figura, rilascia il cursore del mouse.',
  'pl-pl': 'Jeżeli strzałka wskazuje na odpowiednie miejsce, puść przycisk myszki.',
  'vi-vn': 'Khi mũi tên con trỏ chuột chỉ đúng vị trí, hãy thả nút trái chuột.',
  'tr-tr': 'Mouse oku dogru yeri gösterdiginde, sol mouse tuşunu birakin.',
  'lt-lt': 'Kai pelės strelytė bus reikiamoje vietoje, atleiskite kairįjį pelės mygtuką.',
  'zh-cn': '当鼠标箭头指向正确的位置, 即放开鼠标左键.',
  'bg-bg': 'Когато стрелката на мишката покаже правилното място, отпуснете левия бутон на мишката.',
  'bs': 'When the mouse arrow points to the right place, release the left mouse button.',
  'ar-sa': 'عندما يصبح مؤشر الفارة في المكان الصحيح أفلت زر الفارة الأيسر',
};
const tli7: DLoc.ILocItem = {
  'en-gb': 'The picture will be moved.',
  'de-de': 'Das Bild wird verschoben.',
  'sp-sp': 'La imagen será movida.',
  'cs-cz': 'Obrázek bude přesunut.',
  'sk-sk': 'Obrázok bude presunutý.',
  'ru-ru': 'Картинка будет перемещена.',
  'fr-fr': 'L’image sera déplacée.',
  'it-it': 'La figura sarà trascinata.',
  'pl-pl': 'Obrazek zostanie przeniesiony.',
  'vi-vn': 'Bức tranh sẽ được di chuyển.',
  'tr-tr': 'Resim kaldırılacaktır.',
  'lt-lt': 'paveiksliukas bus perkeltas',
  'zh-cn': '照片将被移动.',
  'bg-bg': 'Картинката ще бъде преместена.',
  'bs': 'The picture will be moved.',
  'ar-sa': 'سيتم نقل الصورة',
};
const res = { [globId]: { th11, tp1, tli4, tli5, tli6, tli7 } };
export default res;