import { toGlobId } from 'rw-lib/index'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th1: DLoc.ILocItem = {
  'en-gb': 'SENTENCE SEQUENCING',
  'de-de': 'SÄTZE SEQUENTIALISIEREN',
  'sp-sp': 'SECUENCIA DE ORACIONES',
  'cs-cz': 'ŘAZENÍ VĚT',
  'sk-sk': 'RADENIE VIET',
  'ru-ru': 'ПОРЯДОК ПРЕДЛОЖЕНИЙ',
  'fr-fr': 'CLASSEMENT DE PHRASES',
  'it-it': 'SEQUENZA DELLE FRASI',
  'pl-pl': 'UKŁADANIE ZDAŃ',
  'vi-vn': 'SẮP XẾP CÂU',
  'tr-tr': 'CÜMLE SIRALAMA',
  'lt-lt': 'sakinio eiliškumas',
  'zh-cn': '句子排序',
  'bg-bg': 'ПОСЛЕДОВАТЕЛНОСТ НА ИЗРЕЧЕНИЯТА',
  'bs': 'SENTENCE SEQUENCING',
  'ar-sa': 'ترتيب جمل',
};
const tp: DLoc.ILocItem = {
  'en-gb': 'Your task is to put the sentences into correct order. Proceed as follows:',
  'de-de': 'Ihre Aufgabe ist es, die Sätze in die richtige Reihenfolge zu setzen. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea es poner las oraciones en el orden correcto. Proceda de la siguiente manera:',
  'cs-cz': 'Vaším úkolem je seřadit věty do správného pořadí. Postupujte následovně:',
  'sk-sk': 'Vašou úlohou je zoradiť vety do správneho poradia. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - расставить предложения в правильном порядке. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici reclasser les mots ou phrases dans le bon ordre.',
  'it-it': 'Il tuo compito è mettere le frasi nell\u0027ordine corretto. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest ułożenie zdań w odpowiedniej kolejności. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy sắp xếp lại các câu cho đúng thứ tự. Cách làm như sau:',
  'tr-tr': 'Göreviniz cümleleri dogru siraya sokmaktir. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra sudėti sakinius teisinga tvarka. Darykite taip:',
  'zh-cn': '您的任务是将句子排列为正确的顺序. 操作如下:',
  'bg-bg': 'Вашата задача е да подредите изреченията в правилния ред. Действайте по следния начин:',
  'bs': 'Your task is to put the sentences into correct order. Proceed as follows:',
  'ar-sa': 'مهمتك هي وضع الجمل بالترتيب الصحيح. قم بمايلي:',
};
const tli: DLoc.ILocItem = {
  'en-gb': 'Click on the sentence you wish to move. The sentence will be highlighted.',
  'de-de': 'Klicken Sie auf den Satz, den Sie bewegen möchten. Der Satz wird hervorgehoben.',
  'sp-sp': 'Haga clic en la oración que desea mover. La oración aparecerá resaltada.',
  'cs-cz': 'Klikněte na větu, kterou chcete přesunout. Věta se zvýrazní.',
  'sk-sk': 'Kliknite na vetu, ktorú chcete presunúť. Veta sa zvýrazní.',
  'ru-ru': 'Щелкните предложение, которое хотите переместить. Предложение будет выделено.',
  'fr-fr': 'Cliquez sur l’étiquette que vous voulez déplacer.',
  'it-it': 'Clicca sulla frase da trascinare. La frase viene marcata.',
  'pl-pl': 'Kliknij na zdanie, które chcesz przesunąć. Zdanie zostanie wyróżnione.',
  'vi-vn': 'Nhấn chuột lên câu bạn muốn di chuyển. Câu đó sẽ được đánh dấu.',
  'tr-tr': 'Kaldırmak istediğiniz cümleyi tıklayın. Cümle renkli olarak vurgulanacaktır.',
  'lt-lt': 'Paspauskite ant sakinio, kurį norite perkelti. Sakinys bus paryškintas.',
  'zh-cn': '点击您想要移动的句子. 句子将被突出显示.',
  'bg-bg': 'Кликнете върху изречението, което искате да преместите. Изречението ще се засвети.',
  'bs': 'Click on the sentence you wish to move. The sentence will be highlighted.',
  'ar-sa': 'إضغط على الجملة التي تشاء للإنتقال إليها. سيتم تحديد الجملة.',
};
const tli1: DLoc.ILocItem = {
  'en-gb': 'Hold the left mouse button down and drag the sentence to the right place.',
  'de-de': 'Halten Sie die linke Maustaste gedrückt und ziehen Sie den Satz auf die richtige Stelle.',
  'sp-sp': 'Mantenga presionado el botón izquierdo del ratón y arrastre la oración a su posición correcta.',
  'cs-cz': 'Držte tlačítko myši stisknuté a přesuňte větu (pohybem myši) na nové místo.',
  'sk-sk': 'Držte tlačidlo myši stlačené a presuňte vetu (pohybom myši) na nové miesto.',
  'ru-ru': 'Держите нажатой кнопку мыши и перетяните предложение (движением мыши) на новое место.',
  'fr-fr': 'Maintenez le bouton de la souris enfoncé et glissez l’étiquette à l’endroit souhaité.',
  'it-it': 'Tieni premuto il pulsante del mouse e trascina la frase (muovendo il mouse) al posto nuovo.',
  'pl-pl': 'Przytrzymaj lewy przycisk myszki i przeciągnij zdanie w odpowiednie miejsce.',
  'vi-vn': 'Nhấn, giữ chuột trái và kéo câu đó vào đúng vị trí.',
  'tr-tr': 'Mouse\u0027un sol tuşuna basılı tutun ve cümleyi doğru yere sürükleyin.',
  'lt-lt': 'Laikydami kairįjį pelės mygtuką, sakinį vilkite į tinkamą vietą.',
  'zh-cn': '按住鼠标左键并拖曳句子至正确位置.',
  'bg-bg': 'Натиснете продължително левия бутон на мишката и влачете изречението до правилното място.',
  'bs': 'Hold the left mouse button down and drag the sentence to the right place.',
  'ar-sa': 'استمر في الضغط على الزر الأيسر للفارة و اسحب الجملة إلى المكان الصحيح',
};
const tli2: DLoc.ILocItem = {
  'en-gb': 'When the mouse arrow points to the right place, release the left mouse button.',
  'de-de': 'Wenn der Pfeil auf die richtige Stelle zeigt, lassen Sie die linke Maustaste los.',
  'sp-sp': 'Cuando el puntero señale el lugar correcto, suelte el botón izquierdo del ratón.',
  'cs-cz': 'Až bude kurzor myši nad místem, na které chcete větu přesunout, uvolněte kurzor myši.',
  'sk-sk': 'Keď bude kurzor myši nad miestom, na ktoré chcete vetu presunúť, uvoľnite kurzor myši.',
  'ru-ru': 'Когда курсор мыши будет на том месте, куда вы хотите переместить предложение, отпустите курсор мыши.',
  'fr-fr': 'Relâchez le bouton pour placer l’étiquette.',
  'it-it': 'Nel momento in cui il cursore del mouse sarà impostato sul posto dove desideri impostare la frase, rilascia il cursore del mouse.',
  'pl-pl': 'Jeżeli strzałka wskazuje na odpowiednie miejsce, puść przycisk myszki.',
  'vi-vn': 'Khi mũi tên con trỏ chuột chỉ đúng vị trí, hãy thả nút trái chuột.',
  'tr-tr': 'Mouse oku dogru yeri gösterdiginde, sol mouse tuşunu birakin.',
  'lt-lt': 'Kai pelės strelytė bus reikiamoje vietoje, atleiskite kairįjį pelės mygtuką.',
  'zh-cn': '当鼠标箭头指向正确的位置, 即放开鼠标左键.',
  'bg-bg': 'Когато стрелката на мишката покаже правилното място, отпуснете левия бутон на мишката.',
  'bs': 'When the mouse arrow points to the right place, release the left mouse button.',
  'ar-sa': 'عندما يصبح مؤشر الفارة في المكان الصحيح أفلت زر الفارة الأيسر',
};
const tli3: DLoc.ILocItem = {
  'en-gb': 'The sentence will be moved.',
  'de-de': 'Der Satz wird verschoben.',
  'sp-sp': 'La oración se moverá.',
  'cs-cz': 'Věta bude přesunuta.',
  'sk-sk': 'Veta bude presunutá.',
  'ru-ru': 'Предложение будет перемещено.',
  'fr-fr': 'La phrase sera déplacée.',
  'it-it': 'La frase sarà trascinata.',
  'pl-pl': 'Zdanie zostanie przeniesione.',
  'vi-vn': 'Câu đó sẽ được chuyển đi.',
  'tr-tr': 'Cümle kaldırılacaktır.',
  'lt-lt': 'Sakinys bus perkeltas.',
  'zh-cn': '句子将被移动.',
  'bg-bg': 'изречението ще бъде преместено.',
  'bs': 'The sentence will be moved.',
  'ar-sa': 'سيتم نقل الجملة',
};
const res = { [globId]: { th1, tp, tli, tli1, tli2, tli3 } };
export default res;