import { ILocItem } from "rw-lib/loc";
const th16: ILocItem = {
  "en-gb": "SINGLE CHOICE - ONE CORRECT ANSWER",
  "de-de": "EINZIGE WAHL - EINE KORREKTE ANTWORT",
  "sp-sp": "MULTIPLE CHOICE - SOLO UNA RESPUESTA ES CORRECTA",
  "cs-cz": "VÝBĚR Z VÍCE MOŽNOSTÍ - PRÁVĚ JEDNA SPRÁVNÁ",
  "sk-sk": "VÝBER Z VIACERÝCH MOŽNOSTÍ - IBA JEDNA SPRÁVNA",
  "ru-ru": "ВЫБОР ИЗ ВАРИАНТОВ - РОВНО ОДИН ПРАВИЛЬНЫЙ",
  "fr-fr": "QCM – UNE SEULE BONNE RÉPONSE",
  "it-it": "SCELTA DALLE DIVERSE POSSIBILITA’ – UNA POSSIBILITA’ CORRETTA",
  "pl-pl": "JEDNOKROTNY WYBÓR - JEDNA POPRAWNA ODPOWIEDŹ",
  "vi-vn": "CHỌN MỘT CÂU TRẢ LỜI ĐÚNG",
  "tr-tr": "TEK TERCİH - BİR DOĞRU CEVAP",
  "lt-lt": "VIENAS PASIRINKIMAS - VIENAS TEISINGAS ATSAKYMAS",
  "zh-cn": "单项选择 - 一个正确的答案",
  "bg-bg": "ЕДИНСТВЕН ИЗБОР - ЕДИН ПРАВИЛЕН ОТГОВОР",
  "bs": "SINGLE CHOICE - ONE CORRECT ANSWER",
  "ar-sa": "خيار وحيد - اجابة واحدة فقط صحيحة",
};
const tp6: ILocItem = {
  "en-gb": "Your task is to select the correct one out of several offered options. Proceed as follows:",
  "de-de": "Ihre Aufgabe ist es, eine von mehreren Auswahlen (Antworten) zu markieren. Die Auswahl (Antwort) kann durch Ikonen angezeigt werden. Gehen Sie folgendermassen vor:",
  "sp-sp": "Su tarea consiste en seleccionar una de las opciones (respuestas). Las opciones (respuestas) pueden representarse por íconos. Proceda de la siguiente manera:",
  "cs-cz": "Vaším úkolem je z nabízených možností vybrat jednu správnou. Postupujte následovně:",
  "sk-sk": "Vašou úlohou je vybrať jednu z viacerých možností (odpovedí). Možnosti (odpovede) môžu byť označené ikonkami. Postupujte nasledovne:",
  "ru-ru": "Ваше задание - выбрать из более одного варианта (ответов). Варианты (ответов) могут быть обозначены иконками. Действуйте следующим образом:",
  "fr-fr": "Vous devez ici cocher la bonne réponse.",
  "it-it": "Il tuo compito è scegliere una delle più opzioni (risposte). Le opzioni (risposte) possono essere contrassegnate dalle icone. Prosegui secondo le istruzioni:",
  "pl-pl": "Twoim zadaniem jest wybranie tylko jednej opcji z wielu (odpowiedzi). Opcje (odpowiedzi) mogą być oznaczone poprzez ikonki. Postępuj w następujący sposób:",
  "vi-vn": "Bạn hãy lựa chọn một phương án từ nhiều phương án (các câu trả lời). Các phương án (câu trả lời) có thể được ký hiệu bằng các biểu tượng. Cách làm như sau:",
  "tr-tr": "Göreviniz birkaç seçenek (cevap) arasindan bir tane seçmektir. Seçenekler (cevaplar) simgelerle belirtilir. Aşagidakileri uygulayin:",
  "lt-lt": "Tavo užduotis yra pasirinkti tik vieną variantą iš kelių galimų. Atsakymai gali būti pažymėti simboliais. Darykite taip:",
  "zh-cn": "您的任务是从数个选项 (答案) 中选择唯一选项. 选项 (答案) 可用图标指出. 操作如下:",
  "bg-bg": "Вашата задача е да изберете само една възможност от няколко опции (отговори). Опциите (отговорите) могат да бъдат посочени с иконки. Действайте по следния начин: Действайте по следния начин:",
  "bs": "Your task is to select the correct one out of several offered options. Proceed as follows:",
  "ar-sa": "مهمتك هي إختيار إجابة واحدة فقط من ضمن الخيارات المتعددة. قد تكون هذه الخيارات محددة بأيقونات. قم بما يلي",
};
const tli24: ILocItem = {
  "en-gb": "Left click the chosen item.",
  "de-de": "Links Click auf die Option die Sie wählen möchten.",
  "sp-sp": "Haga clic con el botón izquierdo del ratón en la opción elegida.",
  "cs-cz": "Klikněte levým tlačítkem myši na možnost, kterou jste vybrali.",
  "sk-sk": "Kliknite ľavým tlačidlom myši na vybranú možnosť.",
  "ru-ru": "Кликнете левой кнопкой мыши на выбранный вариант.",
  "fr-fr": "Cliquez dans la case dont l’affirmation correspondante vous semble la bonne.",
  "it-it": "Per assegnare l\u0027opzione desiderata, clicca sul tasto sinistro del mouse.",
  "pl-pl": "Kliknij lewym przyciskiem opcję, którą chcesz wybrać.",
  "vi-vn": "Nhấp trái chuột lên mục bạn chọn.",
  "tr-tr": "Seçmek istediğiniz seçeneği sol tuşla tıklayın.",
  "lt-lt": "Paspauskite kairįjį pelės mygtuką ant pasirinkimo, kurį norite pasirinkti.",
  "zh-cn": "左键点击所选择的项目.",
  "bg-bg": "С кликване на левия бутон избирате опция.",
  "bs": "Left click the chosen item.",
  "ar-sa": "Left click the chosen item.",
};
const tli25: ILocItem = {
  "en-gb": "If you wish to change your selection, click another option.",
  "de-de": "Die Option wird markiert (gewählt).",
  "sp-sp": "If you wish to change your selection, click another option.",
  "cs-cz": "Chcete-li svoji volbu změnit, klikněte na nově vybranou možnost.",
  "sk-sk": "Možnosť bude zvolená (označená).",
  "ru-ru": "Вариант будет выбран (обозначен).",
  "fr-fr": "La case est sélectionnée.",
  "it-it": "L\u0027opzione viene marcata (contrassegnata).",
  "pl-pl": "Opcja zostanie zaznaczona (wybrana).",
  "vi-vn": "If you wish to change your selection, click another option.",
  "tr-tr": "Seçenek işaretlenecektir.",
  "lt-lt": "pasirinkimas bus pažymėtas (parinktas).",
  "zh-cn": "If you wish to change your selection, click another option.",
  "bg-bg": "Опцията ще бъде маркирана (избрана)",
  "bs": "If you wish to change your selection, click another option.",
  "ar-sa": "If you wish to change your selection, click another option.",
};
export default { th16, tp6, tli24, tli25 };