import { ILocItem } from "rw-lib/loc";
const th111: ILocItem = {
  "en-gb": "SORTING INTO GROUPS (DRAG AND DROP)",
  "de-de": "IN GRUPPEN SORTIEREN (ZIEHEN UND LOS LASSEN)",
  "sp-sp": "ORDENE EN GRUPOS (ARRASTRAR Y SOLTAR)",
  "cs-cz": "TŘÍDĚNÍ DO SKUPIN",
  "sk-sk": "TRIEDENIE DO SKUPÍN",
  "ru-ru": "РАЗДЕЛЕНИЕ НА ГРУППЫ",
  "fr-fr": "CLASSEMENT PAR CATÉGORIE (GLISSER-DÉPOSER)",
  "it-it": "SUDDIVISIONE PER GRUPPI",
  "pl-pl": "SORTOWANIE DO GRUP (PRZECIĄGNIJ I UPUŚĆ)",
  "vi-vn": "PHÂN LOẠI VÀO CÁC NHÓM (KÉO VÀ THẢ)",
  "tr-tr": "GRUPLARA AYIRMAK (SÜRÜKLE VE BIRAK)",
  "lt-lt": "rūšiavimas į grupes (vilkti ir numesti)",
  "zh-cn": "分选为群组 (拖放)",
  "bg-bg": "СОРТИРАНЕ ПО ГРУПИ (ТЕГЛЕНЕ И ПУСКАНЕ)",
  "bs": "SORTING INTO GROUPS (DRAG AND DROP)",
  "ar-sa": "تصنيف في مجموعات (عن طريق السحب و الإفلات)",
};
const tp15: ILocItem = {
  "en-gb": "Your task is to sort the items from the list into several groups. Proceed as follows:",
  "de-de": "Um ein Objekt zu bearbeiten, klicken Sie es an und korrigieren Sie es.",
  "sp-sp": "Para editar un campo haga clic sobre el mismo y corríjalo.",
  "cs-cz": "Vaším úkolem je roztřídit položky ze seznamu do několika skupin. Postupujte následovně:",
  "sk-sk": "Pokiaľ chcete opraviť už doplnenú položku, kliknite do okienka a položku opravte.",
  "ru-ru": "Если вы хотите исправить уже дополненный пункт, щёлкните на окошечко и исправьте пункт.",
  "fr-fr": "Si vous voulez corriger une cellule déjà complétée, cliquez dedans et saisissez votre nouvelle réponse.",
  "it-it": "Se vuoi correggere una voce già compilata, clicca nella casella e modifica la voce.",
  "pl-pl": "Aby edytować element, wybierz go i wprowadź zmianę.",
  "vi-vn": "Để chữa một mục, nhấn chuột lên nó và sửa lại.",
  "tr-tr": "Ögeyi düzenlemek için, onu seçin ve düzeltmeyi yapin.",
  "lt-lt": "Norėdami redaguoti elementą, pasirinkite jį ir atlikite pataisymą.",
  "zh-cn": "编辑该项目, 请先选择再进行订正.",
  "bg-bg": "За да редактирате позиция, изберете я и направете корекциите.",
  "bs": "Your task is to sort the items from the list into several groups. Proceed as follows:",
  "ar-sa": "لتحرير العنصر قم بتحديده أولاً ثم أجري التصحيح.",
};
const tli34: ILocItem = {
  "en-gb": "Click an item in the list. It will be highlighted.",
  "de-de": "Klicken Sie einen Artikel in der Liste an. Es wird hervorgehoben.",
  "sp-sp": "Haga clic en un elemento de la lista. Este aparecerá resaltado.",
  "cs-cz": "Klikněte na položku v seznamu. Položka se zvýrazní.",
  "sk-sk": "Kliknite na položku v zozname. Položka sa zvýrazní.",
  "ru-ru": "Кликнете на пункт в списке. Пункт выделится.",
  "fr-fr": "Pour sélectionner une étiquette, cliquez dessus.",
  "it-it": "Clicca sulla voce dell’elenco. La voce viene marcata.",
  "pl-pl": "Kliknij na element znajdujący się na liście. Element zostanie wyróżniony.",
  "vi-vn": "Nhấn chuột lên một mục trong danh sách. Nó sẽ được đánh dấu.",
  "tr-tr": "Listedeki maddelerden birini tıklayın. Renkli olarak vurgulanacaktır.",
  "lt-lt": "Spustelėkite elementą sąraše. Tai bus paryškintos.",
  "zh-cn": "按一下清单中的项目. 这将会突出显示.",
  "bg-bg": "Кликнете върху позиция от списъка. Тя ще бъде засветена.",
  "bs": "Click an item in the list. It will be highlighted.",
  "ar-sa": "Click an item in the list. It will be highlighted.",
};
const tli35: ILocItem = {
  "en-gb": "Hold your left mouse button down and drag the item to an empty space in the correct group.",
  "de-de": "Halten Sie die linke Maustaste gedrückt und ziehen Sie den Artikel auf die leere Lücke in der richtigen Gruppe.",
  "sp-sp": "Mantenga presionado el botón izquierdo del ratón y arrastre el objeto al espacio vacío en el grupo correcto.",
  "cs-cz": "Držte tlačítko myši stisknuté a přesuňte položku (pohybem myši) nad volné místo ve vybrané skupině.",
  "sk-sk": "Držte tlačidlo myši stlačené a presuňte položku (pohybom myši) nad voľné miesto vo zvolenej skupine.",
  "ru-ru": "Держите нажатой кнопку мыши и переставьте пункт (движением мыши) на свободное место в выбранной группе.",
  "fr-fr": "Maintenez le bouton de la souris enfoncé et glissez l’étiquette dans la cellule choisie.",
  "it-it": "Tieni premuto il pulsante del mouse e trascina la voce (muovendo il mouse) al posto libero del gruppo scelto.",
  "pl-pl": "Przytrzymaj lewy przycisk myszki i przeciągnij element w puste miejsce do odpowiedniej grupy.",
  "vi-vn": "Nhấn, giữ chuột trái và kéo mục đó tới chỗ trống trong nhóm thích hợp.",
  "tr-tr": "Mouse\u0027un sol tuşuna basılı tutun ve öğeyi doğru grup içindeki boş bir alana sürükleyin.",
  "lt-lt": "Laikykite paspaustą kairįjį pelės mygtuką ir perkelkite daiktą į tuščią vietą teisingoje grupėje.",
  "zh-cn": "按住鼠标左键并拖曳项目至正确的群组空白处.",
  "bg-bg": "Натиснете продължително левия бутон на мишката и влачете позицията до празното място в правилната група.",
  "bs": "Hold your left mouse button down and drag the item to an empty space in the correct group.",
  "ar-sa": "استمر في الضغط على الزر الأيسر للفارة و اسحب العنصر إلى المكان الفارغ في المجموعة الصحيحة",
};
const tli36: ILocItem = {
  "en-gb": "Release the left mouse button.",
  "de-de": "Lassen Sie die linke Maustaste los.",
  "sp-sp": "Libere el botón izquierdo del ratón",
  "cs-cz": "Uvolněte kurzor myši.",
  "sk-sk": "Uvoľnite kurzor myši.",
  "ru-ru": "Отпустите левую кнопку мыши.",
  "fr-fr": "Relâchez le bouton de la souris pour placer l’étiquette.",
  "it-it": "Rilascia il cursore del mouse.",
  "pl-pl": "Puść lewy przycisk myszki.",
  "vi-vn": "Thả chuột trái.",
  "tr-tr": "Mouse\u0027un sol tuşunu bırakın.",
  "lt-lt": "atleiskite kairįjį pelės mygtuką.",
  "zh-cn": "放开鼠标左键.",
  "bg-bg": "Отпуснете левия бутон на мишката.",
  "bs": "Release the left mouse button.",
  "ar-sa": "أفلت زر الفارة الأيسر",
};
const tli37: ILocItem = {
  "en-gb": "The item will be moved into the chosen group and will be deactivated in the list.",
  "de-de": "Das Objekt wird in die gewählte Gruppe verschoben und von der Liste deaktiviert.",
  "sp-sp": "El elemento se moverá al grupo seleccionado y se desactivará de la lista.",
  "cs-cz": "Položka se přesune do správné skupiny a v seznamu bude deaktivována.",
  "sk-sk": "Položka sa presunie do správnej skupiny a v zozname bude deaktivovaná.",
  "ru-ru": "Пункт переместится в правильную группу и в списке будет дезактивирован.",
  "fr-fr": "L’étiquette n’est plus disponible dans la liste.",
  "it-it": "La voce verrà trascinata nel gruppo corretto e verrà disattivata nell’elenco.",
  "pl-pl": "Element zostanie przeniesiony do wybranej grupy i zdezaktywowany na liście.",
  "vi-vn": "Mục đó sẽ được chuyển vào trong nhóm đã chọn và nó sẽ bị khóa trong danh sách.",
  "tr-tr": "Öğe seçilen gruba taşınacaktır ve listede etkinliği kalkacaktır.",
  "lt-lt": "elementas bus perkeltas į pasirinktą grupę ir bus pašalintas iš sąrašo.",
  "zh-cn": "该项目将被移动放入所选择的群组并在列表中停用.",
  "bg-bg": "Позицията ще бъде преместена в избраната група и ще бъде деактивирана в списъка.",
  "bs": "The item will be moved into the chosen group and will be deactivated in the list.",
  "ar-sa": "ستم نقل العنصر إلى المجموعة التي تم إختيارها و بالتالي ستم إلغاؤه من القائمة",
};
const tp16: ILocItem = {
  "en-gb": "To recall the item from the group back to list, click on it.",
  "de-de": "Ihre Aufgabe ist es, die Objekte von der Liste in mehrere Gruppen zu sortieren. Gehen Sie folgendermassen vor:",
  "sp-sp": "Su tarea consiste en ordenar los elementos de la lista en varios grupos. Proceda de la siguiente manera:",
  "cs-cz": "Pokud chcete položku vrátit ze skupiny do seznamu, klikněte na ni.",
  "sk-sk": "Vašou úlohou je roztriediť položky zo zoznamu do niekoľkých skupín. Postupujte nasledovne:",
  "ru-ru": "Ваше задание - расставить пункты в правильном порядке. Действуйте следующим образом:",
  "fr-fr": "Votre travail consiste à classer les termes de la liste en plusieurs catégories.",
  "it-it": "Il tuo compito è suddividere le voci dell’elenco in più gruppi. Prosegui secondo le istruzioni:",
  "pl-pl": "Twoim zadaniem jest posortowanie elementów z listy do kilku grup. Postępuj w następujący sposób:",
  "vi-vn": "Bạn hãy xếp các mục từ danh sách vào các nhóm khác nhau. Cách làm như sau:",
  "tr-tr": "Göreviniz listedeki ögeleri birkaç grupta siralamaktir. Aşagidakileri uygulayin:",
  "lt-lt": "Tavo užduotis yra sugrupuoti žodžius iš sąrašo į skirtingas grupes. Darykite taip:",
  "zh-cn": "您的任务是从列表中将选项分类为数个群组. 操作如下:",
  "bg-bg": "Вашата задача е да сортирате позициите от списъка в няколко групи. Действайте по следния начин:",
  "bs": "To recall the item from the group back to list, click on it.",
  "ar-sa": "مهمتك تصنيف العناصر من القائمة في عدة مجموعات. قم بما يلي:",
};
export default { th111, tp15, tli34, tli35, tli36, tli37, tp16 };