import { ILocItem } from "rw-lib/loc";
const th110: ILocItem = {
  "en-gb": "SORTING INTO GROUPS (WRITING)",
  "de-de": "IN GRUPPEN SORTIEREN (SCHREIBEN)",
  "sp-sp": "ORDENE EN GRUPOS (ESCRIBIR)",
  "cs-cz": "TŘÍDĚNÍ DO SKUPIN (PSANÍ)",
  "sk-sk": "TRIEDENIE DO SKUPÍN (PÍSANIE)",
  "ru-ru": "РАСПРЕДЕЛЕНИЕ ПО ГРУППАМ (ПИСЬМЕННО)",
  "fr-fr": "CLASSEMENT PAR CATÉGORIE (ÉCRITURE)",
  "it-it": "SUDDIVISIONE PER GRUPPI (SCRITTURA)",
  "pl-pl": "SORTOWANIE DO GRUP (PISANIE)",
  "vi-vn": "PHÂN LOẠI VÀO CÁC NHÓM (VIẾT)",
  "tr-tr": "GRUPLARA AYIRMAK (YAZI)",
  "lt-lt": "rūšiavimas į grupes (rašymas)",
  "zh-cn": "分选为群组 (写作)",
  "bg-bg": "СОРТИРАНЕ ПО ГРУПИ (ПИСАНЕ)",
  "bs": "SORTING INTO GROUPS (WRITING)",
  "ar-sa": "تصنيف في مجموعات (كتابةً)",
};
const tp13: ILocItem = {
  "en-gb": "Your task is to write down the items into several groups. Proceed as follows:",
  "de-de": "Um Ihre Auswahl abzubrechen, klicken Sie noch einmal auf das gewählte Objekt.",
  "sp-sp": "Para cancelar una selección, haga otro clic en el objeto seleccionado.",
  "cs-cz": "Vaším úkolem je rozepsat položky do několika skupin. Postupujte následovně:",
  "sk-sk": "Opakovaným klikom označenie zrušíte.",
  "ru-ru": "Повторным нажатием вы отмените обозначение.",
  "fr-fr": "Pour annuler votre choix, cliquez de nouveau dans la case pour la désélectionner.",
  "it-it": "L’indicazione viene cancellata con un clic ripetuto sulla voce.",
  "pl-pl": "Aby anulować swój wybór, kliknij ponownie wybrany element.",
  "vi-vn": "Để huỷ bỏ lựa chọn, nhấn chuột lên mục đã chọn một lần nữa.",
  "tr-tr": "Seçimlerinizi iptal etmek için tekrar seçilmiş ögeyi tiklayiniz.",
  "lt-lt": "Norėdami atšaukti pasirinkimą spauskite dar kartą ant pasirinkto elemento.",
  "zh-cn": "取消您的选择, 请再次点击选定项目.",
  "bg-bg": "За да отмените вашия избор кликнете върху избраната позиция отново.",
  "bs": "Your task is to write down the items into several groups. Proceed as follows:",
  "ar-sa": "Your task is to write down the items into several groups. Proceed as follows:",
};
const tli32: ILocItem = {
  "en-gb": "Click on the empty space in the group - a blinking cursor appears.",
  "de-de": "Klicken Sie auf die leere Stelle in der Gruppe - ein blinkender Cursor kommt zum Vorschein.",
  "sp-sp": "Haga clic en el espacio vacío del grupo - un cursor parpadeante aparecerá",
  "cs-cz": "Klikněte do prázdného okénka ve skupině - objeví se blikající kurzor.",
  "sk-sk": "Kliknite do prázdneho okienka v skupine - objaví sa blikajúci kurzor.",
  "ru-ru": "Кликнете в пустом окошке в группе: появится мигающий курсор.",
  "fr-fr": "Cliquez dans une cellule vide.",
  "it-it": "Clicca sulla casella vuota nel gruppo – verrà visualizzato il cursore lampeggiante.",
  "pl-pl": "Kliknij puste miejsce w grupie - pojawi się migający kursor.",
  "vi-vn": "Nhấn chuột lên chỗ trống trong nhóm - con trỏ sẽ nhấp nháy.",
  "tr-tr": "Grubun içindeki boş alana tıklayın - yanıp sönen ışıklı bir gösterge ortaya çıkar.",
  "lt-lt": "Paspauskite ant tuščios vietos grupėje - pasirodo mirksintis žymeklis.",
  "zh-cn": "点击群组中的空格 - 一个闪烁的光标将会出现.",
  "bg-bg": "Кликнете в празното място в групата - появява се мигащ курсор.",
  "bs": "Click on the empty space in the group - a blinking cursor appears.",
  "ar-sa": "أنقر على المكان الفارغ في المجموعة - سيظهر مؤشر وامض",
};
const tli33: ILocItem = {
  "en-gb": "Type in the item using your keyboard.",
  "de-de": "Schreiben Sie den Artikel mit Hilfe der Tastatur ein.",
  "sp-sp": "Complete el campo con la ayuda del teclado.",
  "cs-cz": "Doplňte položku pomocí klávesnice.",
  "sk-sk": "Doplňte položku pomocou klávesnice.",
  "ru-ru": "Дополните пункт с помощью клавиатуры.",
  "fr-fr": "Saisissez le terme choisi.",
  "it-it": "Completa la voce attraverso la tastiera.",
  "pl-pl": "Wpisz nazwę elementu, używając klawiatury.",
  "vi-vn": "Gõ vào mục đó bằng bàn phím.",
  "tr-tr": "Ögeyi klavyenizi kullanarak yaziniz.",
  "lt-lt": "Įveskite pasinaudodami klaviatūra.",
  "zh-cn": "使用您的键盘输入项目.",
  "bg-bg": "Напишете вярното посредством клавиатурата си.",
  "bs": "Type in the item using your keyboard.",
  "ar-sa": "أكتب في العنصر مستخدماً لوح المفاتيح الخاص بك",
};
const tp14: ILocItem = {
  "en-gb": "To edit the item, select it and make correction.",
  "de-de": "Ihre Aufgabe ist es, die Objekte in mehrere Gruppen zu schreiben. Gehen Sie folgendermassen vor:",
  "sp-sp": "Su tarea consiste en transcribir los elementos en diferentes grupos. Proceda de la siguiente manera:",
  "cs-cz": "Pokud chcete opravit již doplněnou položku, klikněte do okénka a položku opravte.",
  "sk-sk": "Vašou úlohou je rozpísať položky do niekoľkých skupín. Postupujte nasledovne:",
  "ru-ru": "Ваше задание - расписать пункты в несколько групп. Действуйте следующим образом:",
  "fr-fr": "Vous devez ici remplir la colonne de chaque catégorie avec les termes trouvés dans le texte.",
  "it-it": "Il tuo compito è suddividere le voci in più gruppi. Prosegui secondo le istruzioni:",
  "pl-pl": "Twoim zadaniem jest zapisanie elementów w kilku grupach. Postępuj w następujący sposób:",
  "vi-vn": "Bạn hãy viết các mục vào các nhóm khác nhau. Cách làm như sau:",
  "tr-tr": "Göreviniz ögeleri birkaç gruba yazmaktir. Aşagidakileri uygulayin:",
  "lt-lt": "Tavo užduotis yra surašyti daiktus į kelias grupes. Darykite taip:",
  "zh-cn": "您的任务是将项目写为数个群组. 操作如下:",
  "bg-bg": "Вашата задача е да подредите позициите в няколко групи. Действайте по следния начин:",
  "bs": "To edit the item, select it and make correction.",
  "ar-sa": "مهمتك هي كتابة العناصر في مجموعات متعددة. قم بما يلي:",
};
export default { th110, tp13, tli32, tli33, tp14 };