import { ILocItem } from "rw-lib/loc";
const th122: ILocItem = {
  "en-gb": "SOUND PLAYBACK",
  "de-de": "TON PLAYBACK",
  "sp-sp": "REPRODUCCIÓN DE SONIDO",
  "cs-cz": "PŘEHRÁVÁNÍ ZVUKU",
  "sk-sk": "PREHRÁVANIE ZVUKU",
  "ru-ru": "ПРОСЛУШИВАНИЕ АУДИОЗАПИСИ",
  "fr-fr": "EXTRAITS AUDIO",
  "it-it": "RIPRODUZIONE DELL’AUDIO",
  "pl-pl": "ODTWARZANIE DŹWIĘKU",
  "vi-vn": "NGHE LẠI ÂM THANH",
  "tr-tr": "SES KAYDI ÇALARKEN",
  "lt-lt": "garso atsukimas atgal",
  "zh-cn": "声音播放",
  "bg-bg": "ЗВУКОВО ВЪЗПРОИЗВЕЖДАНЕ",
  "bs": "SOUND PLAYBACK",
  "ar-sa": "تشغيل الصوت",
};
const tp31: ILocItem = {
  "en-gb": "Exercises with a sound-track can be recognized by their “sound mark”. There are two types of sound mark:",
  "de-de": "Ihre Aufgabe ist es, Wörter oder Texte in den Lücken zu korrigieren oder umzugestallten. Gehen Sie folgendermassen vor:",
  "sp-sp": "Exercises with a sound-track can be recognized by their “sound mark”. There are two types of sound mark:",
  "cs-cz": "Cvičení se zvukovou nahrávkou poznáte podle \"zvukových značek\". Existují dvě různé zvukové značky:",
  "sk-sk": "Vašou úlohou je upraviť (resp. opraviť) slová alebo výrazy v okienkach. Postupujte nasledovne:",
  "ru-ru": "Ваше задание - обработать (или же исправить) слова или выражения в окошечках. Действуйте следующим образом:",
  "fr-fr": "Vous devez ici corriger le texte inscrit dans les cellules.",
  "it-it": "Il tuo compito è modificare (ovvero correggere) le parole o termini nelle caselle. Prosegui secondo le istruzioni:",
  "pl-pl": "Twoim zadaniem jest zmodyfikowanie lub poprawienie wszystkich słów lub tekstu w polach. Postępuj w następujący sposób:",
  "vi-vn": "Exercises with a sound-track can be recognized by their “sound mark”. There are two types of sound mark:",
  "tr-tr": "Göreviniz tüm kelimeleri veya kutucuklardaki metinleri degiştirmek veya düzeltmektir. Aşagidakileri uygulayin:",
  "lt-lt": "Tavo užduotis yra pakeisti arba ištaisyti visus žodžius ar tekstą langeliuose. Darykite taip:",
  "zh-cn": "Exercises with a sound-track can be recognized by their “sound mark”. There are two types of sound mark:",
  "bg-bg": "Вашата задача е да промените или коригирате думите или текста в празните кутийки. Действайте по следния начин:",
  "bs": "Exercises with a sound-track can be recognized by their “sound mark”. There are two types of sound mark:",
  "ar-sa": "Exercises with a sound-track can be recognized by their “sound mark”. There are two types of sound mark:",
};
const tli61: ILocItem = {
  "en-gb": "A big sound mark is used to replay longer recordings (articles, dialogues). In this case you cannot see the text, you can only hear it.",
  "de-de": "Eine grosse akustische Zeichen wird bei Wiedergabe von längeren Aufnahmen (Artikeln, Dialogen) verwendet. In diesem Fall können Sie den Text nicht sehen, Sie können ihn nur hören.",
  "sp-sp": "Ícono grande de sonido . Se utiliza para reproducir grabaciones de larga duración (artículos, diálogos). En este caso, usted no puede ver el texto, sólo puede escucharlo.",
  "cs-cz": "Velká zvuková značka. Používá se pro přehrávání dlouhých nahrávek (článků, dialogů). Text v tomto případě nevidíte, jen ho slyšíte.",
  "sk-sk": "Veľká zvuková značka. Používa sa pre prehrávanie dlhých nahrávok (článkov, dialógov). Text v tomto prípade nevidíte, len ho počujete.",
  "ru-ru": "Большой звуковой значок. Используется для проигрывания длинных записей (статей, диалогов). Текст в этом случае вы не видите, а только слышите.",
  "fr-fr": "Le petit haut-parleur indique la lecture d’un mot ou d’une phrase. Le texte lu est simultanément surligné en jaune à l’écran.",
  "it-it": "Il simbolo dell’audio grande. Viene utilizzato per la riproduzione dell’audio lungo (articoli, dialoghi). Il testo in questo caso non viene visualizzato, è disponibile solo come un suono.",
  "pl-pl": "Duży znak dźwiękowy używany jest, aby odtworzyć dłuższe nagrania (artykuły, dialogi). W tym przypadku nie widzisz tekstu, możesz go tylko usłyszeć.",
  "vi-vn": "Một ký hiệu âm thanh lớn dùng để bật lại những bài nghe dài hơn (các bài báo, các đoạn hội thoại). Trong trường hợp này bạn sẽ không nhìn thấy văn bản, bạn chỉ có thể nghe thấy thôi.",
  "tr-tr": "Uzun ses kayıtlarını tekrar dinlemek için büyük bir ses butonu kullanılır. Bu durumda metini göremezsiniz, sadece dinleyebilirsiniz.",
  "lt-lt": "Didelis garso ženklas skirtas ilgesnių įrašų (straipsnių, dialogų) pakartojimui. Šiuo atveju teksto matyti jūs negalite, galite tik jį girdėti.",
  "zh-cn": "一个大的声音标记是用来重播较长的录音 (文章, 对话). 在这种情况下您看不到文本, 您只能听到它.",
  "bg-bg": "За да пуснете отново по-дълги записи (статии, диалози) се използва големия знак за звук. В този случай Вие не можете да виждате текста, може само да го чувате.",
  "bs": "A big sound mark is used to replay longer recordings (articles, dialogues). In this case you cannot see the text, you can only hear it.",
  "ar-sa": "يتم استخدام علامة صوتية كبيرة لإعادة تشغيل التسجيلات الصوتية الطويلة (كالمقالات و المحادثات) في هذه الحالة لا يمكن عرض النص بل يمكنك فقط الاستماع إليه",
};
const tli62: ILocItem = {
  "en-gb": "A small sound mark is used to replay words or sentences. You can see the text and listen to it at the same time.",
  "de-de": "Eine kleine akustische Zeichen wird bei Wiedergabe von Wörtern oder Sätzen verwendet. Sie können den Text zur gleichen Zeit sehen und hören.",
  "sp-sp": "El ícono de sonido pequeño se utiliza para reproducir palabras, oraciones o frases. Puede ver el texto y escucharlo al mismo tiempo.",
  "cs-cz": "Malá zvuková značka se používá pro přehrávání slov, vět nebo jejich částí. Text v tomto případě zároveň vidíte na obrazovce.",
  "sk-sk": "Malá zvuková značka sa používa na prehrávanie slov, viet alebo ich častí. Text v tomto prípade zároveň vidíte na obrazovke.",
  "ru-ru": "Маленький звуковой значок используется для проигрывания слов, предложений или их частей. Текст в этом случае вы видите на экране.",
  "fr-fr": "Le grand haut-parleur indique la lecture d‘une suite de mots. Le texte lu n’est pas surligné à l’écran.",
  "it-it": "Il simbolo dell‘audio piccolo viene utilizzato per la riproduzione audio delle parole, frasi o loro parti. In questo caso il testo viene visualizzato sullo schermo.",
  "pl-pl": "Mały znak dźwiękowy używany jest, aby odtworzyć wyrazy lub zdania. Widzisz tekst i wysłuchujesz go w tym samym czasie.",
  "vi-vn": "Một ký hiệu âm thanh nhỏ được dùng để nghe lại các từ hay các câu. Bạn có thể nhìn thấy và nghe văn bản cùng lúc.",
  "tr-tr": "Kelimeleri ve cümleleri tekrar dinleyebilmek için küçük bir ses işareti. Metni görüp aynı zamanda dinleyebilirsiniz.",
  "lt-lt": "Nedidelis garso ženkliukas skirtas žodžių ir sakinių pakartojimui. Tuo pačiu metu Jūs galite tiek skaityti, tiek ir girdėti tą patį tekstą.",
  "zh-cn": "一个小的声音标记是用来重播单词或句子. 您可以同时看见文本并聆听它.",
  "bg-bg": "За да пуснете отново думи или изречения се използва малкия знак за звук. Можете да виждате текста и да го чувате едновременно.",
  "bs": "A small sound mark is used to replay words or sentences. You can see the text and listen to it at the same time.",
  "ar-sa": "يتم استخدام علامة صوتية صغيرة لإعادة تشغيل الكلمات و الجمل في هذه الحالة يمكن عرض النص أثناء الاستماع إليه",
};
const tli63: ILocItem = {
  "en-gb": "To play the sound, click the sound mark. To stop replaying, click elsewhere on the screen.",
  "de-de": "Um die Wiedergabe zu starten, klicken Sie die Ton Markierung an. Um die Wiedergabe zu beenden, klicken Sie auf eine andere Stelle auf dem Bildschirm.",
  "sp-sp": "Para reproducir el sonido haga clic sobre el ícono de sonido. Para detener la reproducción, haga clic en cualquier otro sitio de la pantalla.",
  "cs-cz": "Přehrávání zvuku spustíte kliknutím na zvukovou značku. Kliknutím mimo zvukovou značku přehrávání zvuku ukončíte.",
  "sk-sk": "Prehrávanie zvuku spustíte kliknutím na zvukovú značku. Kliknutím mimo zvukovej značky prehrávanie zvuku ukončíte.",
  "ru-ru": "Чтобы прослушать аудиозапись, нажмите на звуковой значок. Щёлкните рядом, чтобы остановить проигрывание.",
  "fr-fr": "Pour lancer la lecture, cliquez sur le logo. Pour stopper la lecture, cliquez n’importe où à côté.",
  "it-it": "La riproduzione dell\u0027audio viene avviata cliccando sul simbolo audio. Cliccando fuori dal simbolo audio, la riproduzione dell\u0027audio viene terminata.",
  "pl-pl": "Aby uruchomić dźwięk, kliknij znak dźwiękowy. Aby zatrzymać odtwarzanie, kliknij dowolne miejsce na ekranie.",
  "vi-vn": "Để bắt đầu nghe, bạn nhấn chuột lên ký hiệu âm thanh. Để dừng nghe, bạn nhấn chuột lên bất kỳ một vị trí nào khác trên màn hình.",
  "tr-tr": "Ses kaydini çalmak için, ses işaretini tiklayin. Tekrar çalmasini durdurmak için, ekranda başka bir blgeye tiklayin.",
  "lt-lt": "Tam, kad pasigirstų garsas, paspauskite ant garso simbolio. Grojimą sustabdyti galite spustelėję bet kur ant ekrano.",
  "zh-cn": "播放声音, 请点击声音标记. 停止重播, 请在屏幕上点击别处.",
  "bg-bg": "За да пуснете звука, кликнете върху знака за звук. За да спрете повтарянето, кликнете някъде другаде върху екрана.",
  "bs": "To play the sound, click the sound mark. To stop replaying, click elsewhere on the screen.",
  "ar-sa": "لتشغيل الصوت أنقر على علامة الصوت. لإيقاف إعادة التشغيل أنقر في أي مكان من الشاشة.",
};
export default { th122, tp31, tli61, tli62, tli63 };