import { ILocItem, toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th17: ILocItem = {
  'en-gb': 'TEXT SELECTION (MARKING) - ONE CORRECT ANSWER',
  'de-de': 'TEXTAUSWAHL (MARKIERUNG) - EINE RICHTIGE ANTWORT',
  'sp-sp': 'SELECCIÓN DE TEXTOS (MARCANDO) - UNA SOLA RESPUESTA ES CORRECTA',
  'cs-cz': 'VÝBĚR ( OZNAČOVÁNÍ )TEXTU - PRÁVĚ JEDNA SPRÁVNÁ MOŽNOST',
  'sk-sk': 'VÝBER ( OZNAČOVANIE )TEXTU - IBA JEDNA SPRÁVNA MOŽNOSŤ',
  'ru-ru': 'ВЫБОР (ОБОЗНАЧЕНИЕ) ТЕКСТА - ТОЛЬКО ОДНА ПРАВИЛЬНАЯ ВОЗМОЖНОСТЬ',
  'fr-fr': 'SÉLECTION DE TEXTE - UNE SEULE BONNE RÉPONSE',
  'it-it': 'SCELTA (INDICAZIONE) DEL TESTO – UNA POSSIBILITA’ CORRETTA',
  'pl-pl': 'WYBÓR TEKSTU (ZAZNACZANIE) - JEDNA POPRAWNA ODPOWIEDŹ',
  'vi-vn': 'LỰA CHỌN VĂN BẢN (ĐÁNH DẤU) - MỘT CÂU TRẢ LỜI ĐÚNG',
  'tr-tr': 'METİN SEÇENEKLERİ (İŞARETLEME) - BİR DOĞRU CEVAP',
  'lt-lt': 'TEKSTO PASIRINKIMAS (ŽYMĖJIMAS) - VIENAS TEISINGAS ATSAKYMAS',
  'zh-cn': '文本选择 (标记) - 一个正确答案',
  'bg-bg': 'ИЗБОР НА ТЕКСТ (МАРКИРАНЕ) - ЕДИН ПРАВИЛЕН ОТГОВОР',
  'bs': 'TEXT SELECTION (MARKING) - ONE CORRECT ANSWER',
  'ar-sa': 'الإختيار من النص (وضع علامة) - إجابة واحدة فقط صحيحة',
};
const tp7: ILocItem = {
  'en-gb': 'Your task is to mark sentence parts, words, word parts or syllables while you may choose from several items but only one choice is correct. Proceed as follows:',
  'de-de': 'Um Ihre Auswahl zu ändern, klicken Sie auf ein anderes Objekt.',
  'sp-sp': 'Para cambiar su selección haga clic sobre otro elemento.',
  'cs-cz': 'Vaším úkolem je označit části vět, slova, části slov nebo slabiky, přičemž vybíráte z více možností a pouze jedna možnost je správná. Postupujte následovně:',
  'sk-sk': 'Ak chcete svoju voľbu zmeniť, kliknite na inú možnosť.',
  'ru-ru': 'Если вы хотите выбор сменить, щёлкните на другой вариант.',
  'fr-fr': 'Si vous voulez modifier votre choix, cliquez dans une autre case.',
  'it-it': 'Per cambiare la tua scelta, clicca su un\u0027altra voce.',
  'pl-pl': 'Aby zmienić swój wybór, wybierz inny element.',
  'vi-vn': 'Để thay đổi lựa chọn, bạn nhấn chuột lên mục khác.',
  'tr-tr': 'Seçimlerinizi degiştirmek için başka bir ögeyi seçin.',
  'lt-lt': 'Pakeisti pasirinkimą galite pasirinkę kitą elementą.',
  'zh-cn': '改变您的选择, 请挑选一个不同的项目.',
  'bg-bg': 'За да промените вашия избор, изберете друга позиция.',
  'bs': 'Your task is to mark sentence parts, words, word parts or syllables while you may choose from several items but only one choice is correct. Proceed as follows:',
  'ar-sa': 'لتغيير خيارك فقط اضغط على عنصر آخر',
};
const tli26: ILocItem = {
  'en-gb': 'Place the mouse cursor over the item (sentence part, word, word part or syllable) you wish to select.',
  'de-de': 'Platzieren Sie den Mauszeiger über das (Satzteil, Wort, Wortteil oder Silbe), was Sie wählen möchten.',
  'sp-sp': 'Place the mouse cursor over the item (sentence part, word, word part or syllable) you wish to select.',
  'cs-cz': 'Umístěte kurzor myši na položku (část věty, slovo, část slova nebo slabiku), kterou chcete označit.',
  'sk-sk': 'Umiestnite kurzor myši na položku (časť vety, slovo, časť slova alebo slabiku), ktorú chcete označiť.',
  'ru-ru': 'Поместите курсор мыши на объект (часть предложения, слово, часть слова, слог или букву), который Вы хотите выделить.',
  'fr-fr': 'Choisissez l’endroit que vous souhaitez sélectionner.',
  'it-it': 'Posiziona il cursore del mouse sulla voce (parte della frase, parola, parte della parola, sillabe) da marcare.',
  'pl-pl': 'Umieść wskaźnik myszki nad danym elementem (częścią zdania, słowem, częścią słowa lub sylabą), który chcesz wybrać.',
  'vi-vn': 'Place the mouse cursor over the item (sentence part, word, word part or syllable) you wish to select.',
  'tr-tr': 'Mouse\u0027u seçmek istediğiniz öğenin (cümle parçası, kelime, kelime parçası veya hece) üzerine götürün.',
  'lt-lt': 'Pelės žymeklį nuveskite ant objekto (sakinio dalies, žodžio, žodžio dalies ar skiemens) kurį norite pasirinkti.',
  'zh-cn': 'Place the mouse cursor over the item (sentence part, word, word part or syllable) you wish to select.',
  'bg-bg': 'Поставете показалеца на мишката над позицията (част от изречение, дума, част от дума, сричка или буква), която искате да изберете.',
  'bs': 'Place the mouse cursor over the item (sentence part, word, word part or syllable) you wish to select.',
  'ar-sa': 'Place the mouse cursor over the item (sentence part, word, word part or syllable) you wish to select.',
};
const tli27: ILocItem = {
  'en-gb': 'Left click the item, it will be marked (selected).',
  'de-de': 'Links Click auf den Artikel, es wird markiert (gewählt).',
  'sp-sp': 'Haga clic con el objeto con el botón izquierdo del ratón, el elemento será seleccionado.',
  'cs-cz': 'Klikněte na položku levým tlačítkem myši - položka bude označena.',
  'sk-sk': 'Kliknite na položku ľavým tlačidlom myši - položka bude označená.',
  'ru-ru': 'Кликнете на пункт левой кнопкой мыши - пункт будет обозначен.',
  'fr-fr': 'Cliquez desssus.',
  'it-it': 'Clicca con il tasto sinistro del mouse sulla voce – quest’ultima verrà marcata.',
  'pl-pl': 'Kliknij na element lewym przyciskiem, zostanie on zaznaczony (wybrany).',
  'vi-vn': 'Nhấp trái chuột lên mục đó để đánh dấu (đã chọn).',
  'tr-tr': 'Öğeyi sol tuşla tıklayın, işaretlenecektir (seçilecektir).',
  'lt-lt': 'Paspauskite kairįjį pelės mygtuką ant dalyko, jis bus pažymėtas (pasirinktas).',
  'zh-cn': '左键点击项目, 它将被标记 (选定).',
  'bg-bg': 'С кликване на левия бутон тя ще бъде маркирана (избрана).',
  'bs': 'Left click the item, it will be marked (selected).',
  'ar-sa': 'نقرة يسارية على العنصر و سيتم تحديده',
};
const tp8: ILocItem = {
  'en-gb': 'To change your selection select a different item.',
  'de-de': 'Ihre Aufgabe ist es, Satzteile, Wörter, Wortteile oder Silben zu markieren, während Sie von mehreren Begriffen wählen, wobei nur eine Wahl richtig ist. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea es marcar las partes de las oraciones, palabras, partes de la palabra o sílabas. Aunque la elección se realice entre varias opciones, sólo una es correcta. Proceda de la siguiente manera:',
  'cs-cz': 'Chcete-li svoji volbu změnit, klikněte na jinou možnost.',
  'sk-sk': 'Vašou úlohou je označiť časti viet, slová, časti slov alebo slabiky, pričom vyberáte z viacerých možností a len jedna možnosť je správna. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - отметить части предложения, слова, части слов или слоги, при этом вы выбираете из вариантов, и только один вариант правильный. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici sélectionner parmi les différents choix la syllabe, le mot ou morceau de phrase correspondant à la bonne réponse.',
  'it-it': 'Il tuo compito è contrassegnare le parti delle frasi, parole, parti delle parole o sillabe scegliendo dalle più opzioni solo una corretta. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest zaznaczenie części zdań, wyrazów, części wyrazów lub sylab, mając możliwość wyboru z wielu elementów, lecz tylko jeden jest poprawny. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy đánh dấu các bộ phận của câu, các từ, các bộ phận của từ hay các âm tiết. Bạn có thể lựa chọn từ nhiều mục nhưng chỉ có duy nhất 1 lựa chọn đúng. Cách làm như sau:',
  'tr-tr': 'Göreviniz cümle parçalarini, kelimeleri, kelime parçalarini veya heceleri işaretlemektir, birkaç öge arasindan seçmek zorunda kalabilirsiniz fakat tek seçenek dogrudur. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra pažymėti sakinių dalis, žodžius, žodžių dalis ar skiemenis. Galite pasirinkti iš skirtingų variantų, tačiau tik vienas pasirinkimas yra teisingas. Darykite taip:',
  'zh-cn': '当您可从几个项目选择, 但只有一个选择是正确的, 您的任务则为标记句子部分, 单词, 单词部分或音节. 操作如下:',
  'bg-bg': 'Вашата задача е да маркирате части от изречение, цели думи, части от думи или срички, които можете да избирате от различни позиции, но само един избор е правилният. Действайте по следния начин:',
  'bs': 'To change your selection select a different item.',
  'ar-sa': 'مهمتك هي تحديد أجزاء الجملة , كلمات , أجزاء الكلمة أو مقاطع صوتية . قد يكون لديك عدة عناصر لتختار منها ولكن خياراً واحداً هو الصحيح . قم بما يلي :',
};
const res = { [globId]: { th17, tp7, tli26, tli27, tp8 } };
export default res;