import { toGlobId } from 'rw-lib/index'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th18: DLoc.ILocItem = {
  'en-gb': 'TEXT SELECTION (MARKING) - MULTIPLE CORRECT ANSWERS',
  'de-de': 'TEXTAUSWAHL (MARKIERUNG) - MEHR RICHTIGE ANTWORTEN',
  'sp-sp': 'SELECCIÓN DE TEXTOS (MARCANDO) -MÁS DE UNA RESPUESTA PUEDE SER CORRECTA',
  'cs-cz': 'VÝBĚR ( OZNAČOVÁNÍ ) TEXTU - VÍCE SPRÁVNÝCH MOŽNOSTÍ',
  'sk-sk': 'VÝBER ( OZNAČOVANIE ) TEXTU - VIAC SPRÁVNYCH MOŽNOSTÍ',
  'ru-ru': 'ВЫБОР (ВЫДЕЛЕНИЕ) ТЕКСТА – НЕСКОЛЬКО ПРАВИЛЬНЫХ ОТВЕТОВ',
  'fr-fr': 'SÉLECTION DE TEXTE - PLUSIEURS BONNES RÉPONSES',
  'it-it': 'SCELTA (INDICAZIONE) DEL TESTO – PIÙ DI UNA POSSIBILITA’ CORRETTA',
  'pl-pl': 'WYBÓR TEKSTU (ZAZNACZANIE) - WIELE POPRAWNYCH ODPOWIEDZI',
  'vi-vn': 'LỰA CHỌN VĂN BẢN (ĐÁNH DẤU) - NHIỀU CÂU TRẢ LỜI ĐÚNG',
  'tr-tr': 'METİN SEÇENEKLERİ (İŞARETLEME) - BİRDEN ÇOK DOĞRU CEVAP',
  'lt-lt': 'TEKSTO PASIRINKIMAS (ŽYMĖJIMAS) - KELI TEISINGI ATSAKYMAI',
  'zh-cn': '文本选择 (标记) - 多个正确答案',
  'bg-bg': 'ИЗБОР НА ТЕКСТ (МАРКИРАНЕ) - МНОГО ПРАВИЛНИ ОТГОВОРИ',
  'bs': 'TEXT SELECTION (MARKING) - MULTIPLE CORRECT ANSWERS',
  'ar-sa': 'الإختيار من النص (وضع علامة) - عدة إجابات صحيحة',
};
const tp9: DLoc.ILocItem = {
  'en-gb': 'Your task is to select sentence parts, words, word parts, syllables or characters. Proceed as follows:',
  'de-de': 'Um Ihre Auswahl zu ändern, klicken Sie auf ein anderes Objekt.',
  'sp-sp': 'Para cambiar su selección haga clic sobre otro elemento.',
  'cs-cz': 'Vaším úkolem je označit části vět, slova, části slov, slabiky nebo písmena. Postupujte následovně:',
  'sk-sk': 'Ak chcete svoju voľbu zmeniť, kliknite na inú možnosť.',
  'ru-ru': 'Если вы хотите выбор сменить, щёлкните на другой вариант.',
  'fr-fr': 'Si vous voulez modifier votre choix, cliquez dans une autre case.',
  'it-it': 'Per cambiare la tua scelta, clicca su un\u0027altra voce.',
  'pl-pl': 'Aby zmienić swój wybór, wybierz inny element.',
  'vi-vn': 'Để thay đổi lựa chọn, bạn nhấn chuột lên mục khác.',
  'tr-tr': 'Seçimlerinizi degiştirmek için başka bir ögeyi seçin.',
  'lt-lt': 'Pakeisti pasirinkimą galite pasirinkę kitą elementą.',
  'zh-cn': '改变您的选择, 请挑选一个不同的项目.',
  'bg-bg': 'За да промените вашия избор, изберете друга позиция.',
  'bs': 'Your task is to select sentence parts, words, word parts, syllables or characters. Proceed as follows:',
  'ar-sa': 'لتغيير خيارك فقط اضغط على عنصر آخر',
};
const tli28: DLoc.ILocItem = {
  'en-gb': 'Place the mouse cursor over the item (sentence part, word, word part, syllable or character) you wish to select.',
  'de-de': 'Platzieren Sie den Mauscursor über das (Satzteil, Wort, Wortteil, Silbe oder Charakter), was Sie wählen möchten.',
  'sp-sp': 'Coloque el puntero del ratón sobre el objeto (parte de la oración, palabra, parte de la palabra, sílaba o letra ) que desea seleccionar',
  'cs-cz': 'Umístěte kurzor myši na položku (část věty, slovo, část slova, slabiku nebo písmeno), kterou chcete označit.',
  'sk-sk': 'Umiestnite kurzor myši na položku (časť vety, slovo, časť slova, slabika alebo písmeno), ktoré chcete označiť.',
  'ru-ru': 'Поместите курсор мыши на объект (часть предложения, слово, часть слова, слог или букву), который Вы хотите выделить.',
  'fr-fr': 'Choisissez l’endroit que vous souhaitez sélectionner.',
  'it-it': 'Posiziona il cursore del mouse sulla voce (parte della frase, parola, parte della parola, sillabe oppure lettera) da marcare.',
  'pl-pl': 'Umieść kursor myszki nad danym elementem (częścią zdania, słowem, częścią słowa lub sylabą), który chcesz wybrać.',
  'vi-vn': 'Đặt con trỏ chuột lên các mục (bộ phận câu, từ, bộ phận từ, âm tiết hay ký tự) mà bạn muốn lựa chọn.',
  'tr-tr': 'Mouse\u0027u seçmek istediğiniz öğenin (cümle parçası, kelime, kelime parçası, hece veya karakter) üzerine götürün.',
  'lt-lt': 'Pelės žymeklį nuveskite ant objekto (sakinio dalies, žodžio, žodžio dalies, skiemens ar raidės) kurį norite pasirinkti.',
  'zh-cn': '将鼠标光标置于您想选择的项目上 (句子部分, 单词, 单词部分, 音节或字符) .',
  'bg-bg': 'Поставете курсора на мишката над позицията (част от изречение, дума, част от дума, сричка или буква), която искате да изберете.',
  'bs': 'Place the mouse cursor over the item (sentence part, word, word part, syllable or character) you wish to select.',
  'ar-sa': 'ضع مؤشر الفارة فوق العنصر الذي ترغب في تحديده (جزء من الجملة , كلمة ,جزء من الكلمة أو مقطع صوتي)',
};
const tli29: DLoc.ILocItem = {
  'en-gb': 'Left click the item, it will be marked (selected).',
  'de-de': 'Links Click auf den Artikel, es wird markiert (gewählt).',
  'sp-sp': 'Haga clic con el objeto con el botón izquierdo del ratón, el elemento será seleccionado.',
  'cs-cz': 'Klikněte na položku levým tlačítkem myši - položka bude označena.',
  'sk-sk': 'Kliknite na položku ľavým tlačidlom myši - položka bude označená.',
  'ru-ru': 'Кликнете на пункт левой кнопкой мыши - пункт будет обозначен.',
  'fr-fr': 'Cliquez desssus.',
  'it-it': 'Clicca con il tasto sinistro del mouse sulla voce – quest’ultima verrà marcata.',
  'pl-pl': 'Kliknij na element lewym przyciskiem, zostanie on zaznaczony (wybrany).',
  'vi-vn': 'Nhấp trái chuột lên mục đó để đánh dấu (đã chọn).',
  'tr-tr': 'Öğeyi sol tuşla tıklayın, işaretlenecektir (seçilecektir).',
  'lt-lt': 'Paspauskite kairįjį pelės mygtuką ant dalyko, jis bus pažymėtas (pasirinktas).',
  'zh-cn': '左键点击项目, 它将被标记 (选定).',
  'bg-bg': 'С кликване на левия бутон тя ще бъде маркирана (избрана).',
  'bs': 'Left click the item, it will be marked (selected).',
  'ar-sa': 'نقرة يسارية على العنصر و سيتم تحديده',
};
const tp10: DLoc.ILocItem = {
  'en-gb': 'To cancel your selection click on selected item again.',
  'de-de': 'Ihre Aufgabe ist es, Satzteile, Wörter, Wortteile, Silben oder Schriftzeichen auszuwählen. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Es su tarea marcar partes de las oraciones, palabras, parte de las palabras, sílabas o letras. Proceda de la manera siguiente:',
  'cs-cz': 'Opakovaným klikem označení zrušíte.',
  'sk-sk': 'Vašou úlohou je označiť časti viet, slová, časti slov, slabiky alebo písmená. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - отметить части предложения, слова, части слов, слоги или буквы. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici sélectionner parmi les différents choix les lettres, syllabes, mots ou morceaux de phrase correspondants aux bonnes réponses.',
  'it-it': 'Il tuo compito è contrassegnare la parte delle frasi, parole, parti di parole, sillabe oppure lettere. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest wybór części zdań, słów, części słów, sylab lub liter. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy đánh dấu các bộ phận của câu, các từ, các bộ phận của từ, các âm tiết hay các ký tự. Cách làm như sau:',
  'tr-tr': 'Göreviniz cümle parçaciklarini, kelimeleri, kelime parçaciklarini, heceleri veya bölümleri seçmektir. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra pasirinkti sakinio dalis, žodžius, žodžių dalis, skiemenis ar simbolius. Darykite taip:',
  'zh-cn': '您的任务是选择句子部分, 单词, 单词部分, 音节或字符. 操作如下:',
  'bg-bg': 'Вашата задача е да изберете части от изречение, цели думи, части от думи, срички или букви. Действайте по следния начин:',
  'bs': 'To cancel your selection click on selected item again.',
  'ar-sa': 'مهمتك هي اختيار جزء من جملة , كلمة , جزء من كلمة , مقاطع صوتية أو حروف. قم بما يلي:',
};
const res = { [globId]: { th18, tp9, tli28, tli29, tp10 } };
export default res;