import { toGlobId } from 'rw-lib/index'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th115: DLoc.ILocItem = {
  'en-gb': 'TRUE/FALSE SENTENCES',
  'de-de': 'RICHTIGE/FALSCHE SÄTZE',
  'sp-sp': 'VERDADERO O FALSO',
  'cs-cz': 'PRAVDIVÉ/NEPRAVDIVÉ VĚTY',
  'sk-sk': 'PRAVDIVÉ/NEPRAVDIVÉ VETY',
  'ru-ru': 'ПРАВДИВЫЕ/ЛОЖНЫЕ ПРЕДЛОЖЕНИЯ',
  'fr-fr': 'VRAI ou FAUX',
  'it-it': 'FRASI VERE / FALSE',
  'pl-pl': 'ZDANIA PRAWDZIWE/FAŁSZYWE',
  'vi-vn': 'CÁC CÂU ĐÚNG/SAI',
  'tr-tr': 'DOGRU/YANLIŞ CÜMLELERI',
  'lt-lt': 'NEKLAIDINGI/KLAIDINGI SAKINIAI',
  'zh-cn': '真实的/不真实的句子',
  'bg-bg': 'ВЕРНИ/НЕВЕРНИ ИЗРЕЧЕНИЯ',
  'bs': 'TRUE/FALSE SENTENCES',
  'ar-sa': 'جمل صح أو خطأ',
};
const tp24: DLoc.ILocItem = {
  'en-gb': 'Your task is to decide whether the sentences are true or false. Every sentence is marked with an icon. Proceed as follows:',
  'de-de': 'Gehen Sie folgendermassen vor:',
  'sp-sp': 'Realizar de la manera siguiente:',
  'cs-cz': 'Vaším úkolem je rozhodnout, jestli jsou věty pravdivé nebo nepravdivé. Věty jsou označeny ikonou. Postupujte následovně:',
  'sk-sk': 'Postupujte nasledovne:',
  'ru-ru': 'Сделайте это следующим образом:',
  'fr-fr': 'Comment faire :',
  'it-it': 'Prosegui secondo le istruzioni:',
  'pl-pl': 'Postępuj w następujący sposób:',
  'vi-vn': 'Cách làm như sau:',
  'tr-tr': 'Aşağıdakileri uygulayın:',
  'lt-lt': 'Tęskite kaip nurodyta:',
  'zh-cn': '操作如下:',
  'bg-bg': 'Действайте по следния начин:',
  'bs': 'Your task is to decide whether the sentences are true or false. Every sentence is marked with an icon. Proceed as follows:',
  'ar-sa': 'قم بما يلي :',
};
const tli49: DLoc.ILocItem = {
  'en-gb': 'If the sentence is false, skip it.',
  'de-de': 'Wenn der Satz falsch ist, überspringen.',
  'sp-sp': 'Si la oración es falsa, ignórela.',
  'cs-cz': 'Pokud je věta nepravdivá, přeskočte ji.',
  'sk-sk': 'Pokiaľ je veta nepravdivá, preskočte ju.',
  'ru-ru': 'Если предложение ложно, пропустите его.',
  'fr-fr': 'Si la phrase est fausse, passez-la.',
  'it-it': 'Salta la frase nel caso quest’ultima non sia vera.',
  'pl-pl': 'Jeżeli zdanie jest fałszywe, pomiń je.',
  'vi-vn': 'Nếu câu đó sai thì bỏ qua.',
  'tr-tr': 'Cümle yanlışsa, atlayıp geçin.',
  'lt-lt': 'Jei sakinys yra klaidingas, praleiskite jį.',
  'zh-cn': '如果句子是不真实的, 跳过它.',
  'bg-bg': 'Ако изречението не е вярно, пропуснете го.',
  'bs': 'If the sentence is false, skip it.',
  'ar-sa': 'تخطي الجملة في حال كانت خاطئة',
};
const tli50: DLoc.ILocItem = {
  'en-gb': 'If the sentence is true, click on it. It will be selected (marked).',
  'de-de': 'Wenn der Satz richtig ist, anklicken. Es wirt ausgewählt (markiert).',
  'sp-sp': 'Si la oración es verdadera, haga clic en ella. Será seleccionada (marcada).',
  'cs-cz': 'Pokud je věta pravdivá, klikněte na ni. Bude vybrána (označena).',
  'sk-sk': 'Pokiaľ je veta pravdivá, kliknite na ňu. Bude zvolená (označená).',
  'ru-ru': 'Если предложение правдиво, нажмите на него. Оно будет выбрано (обозначено).',
  'fr-fr': 'Si la phrase est vraie, cliquez dessus. Elle sera sélectionnée.',
  'it-it': 'Clicca sulla frase nel caso che quest’ultima sia vera. La frase verrà marcata (contrassegnata).',
  'pl-pl': 'Jeżeli zdanie jest prawdziwe, kliknij na nie. Zostanie ono wybrane (zaznaczone).',
  'vi-vn': 'Nếu câu đó đúng, nhấn chuột lên đó để chọn (được đánh dấu).',
  'tr-tr': 'Cümle doğruysa, üstüne tıklayın. Seçilmiş olacaktır (işaretlenecektir).',
  'lt-lt': 'Jei sakinyje yra tiesingas, paspauskite ant jo. Jis bus pasirinktas (pažymėtas).',
  'zh-cn': '如果句子是真实的, 点击它. 它将被挑选出来 (标记).',
  'bg-bg': 'Ако изречението е вярно, кликнете върху него. Ще бъде избрано (маркирано).',
  'bs': 'If the sentence is true, click on it. It will be selected (marked).',
  'ar-sa': 'أنقر على الجملة إذا كانت صحيحة و سيتم إختيارها',
};
const tli51: DLoc.ILocItem = {
  'en-gb': 'To cancel your selection click on selected item again.',
  'de-de': 'Um Ihre Auswahl abzubrechen, klicken Sie noch einmal auf das gewählte Objekt.',
  'sp-sp': 'Para cancelar una selección, haga otro clic en el objeto seleccionado.',
  'cs-cz': 'Opakovaným klikem označení zrušíte.',
  'sk-sk': 'Opakovaným klikom označenie zrušíte.',
  'ru-ru': 'Повторным нажатием вы отмените обозначение.',
  'fr-fr': 'Pour annuler votre choix, cliquez de nouveau dans la case pour la désélectionner.',
  'it-it': 'L’indicazione viene cancellata con un clic ripetuto sulla voce.',
  'pl-pl': 'Aby anulować swój wybór, kliknij ponownie wybrany element.',
  'vi-vn': 'Để huỷ bỏ lựa chọn, nhấn chuột lên mục đã chọn một lần nữa.',
  'tr-tr': 'Seçimlerinizi iptal etmek için tekrar seçilmiş ögeyi tiklayiniz.',
  'lt-lt': 'Norėdami atšaukti pasirinkimą spauskite dar kartą ant pasirinkto elemento.',
  'zh-cn': '取消您的选择, 请再次点击选定项目.',
  'bg-bg': 'За да отмените вашия избор кликнете върху избраната позиция отново.',
  'bs': 'To cancel your selection click on selected item again.',
  'ar-sa': 'To cancel your selection click on selected item again.',
};
const res = { [globId]: { th115, tp24, tli49, tli50, tli51 } };
export default res;