import { toGlobId } from 'rw-lib/index'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th116: DLoc.ILocItem = {
  'en-gb': 'TRUE/FALSE SENTENCES',
  'de-de': 'RICHTIGE/FALSCHE SÄTZE',
  'sp-sp': 'VERDADERO O FALSO',
  'cs-cz': 'PRAVDIVÉ/NEPRAVDIVÉ VĚTY',
  'sk-sk': 'PRAVDIVÉ/NEPRAVDIVÉ VETY',
  'ru-ru': 'ПРАВДИВЫЕ/ЛОЖНЫЕ ПРЕДЛОЖЕНИЯ',
  'fr-fr': 'VRAI ou FAUX',
  'it-it': 'FRASI VERE / FALSE',
  'pl-pl': 'ZDANIA PRAWDZIWE/FAŁSZYWE',
  'vi-vn': 'CÁC CÂU ĐÚNG/SAI',
  'tr-tr': 'DOGRU/YANLIŞ CÜMLELERI',
  'lt-lt': 'NEKLAIDINGI/KLAIDINGI SAKINIAI',
  'zh-cn': '真实的/不真实的句子',
  'bg-bg': 'ВЕРНИ/НЕВЕРНИ ИЗРЕЧЕНИЯ',
  'bs': 'TRUE/FALSE SENTENCES',
  'ar-sa': 'جمل صح أو خطأ',
};
const tp25: DLoc.ILocItem = {
  'en-gb': 'Your task is to decide whether the sentences are true or false. Proceed as follows:',
  'de-de': 'Falls Sie das gewählte Objekt ändern möchten, ersetzen Sie diese durch ein anderes.',
  'sp-sp': 'Your task is to decide whether the sentences are true or false. Proceed as follows:',
  'cs-cz': 'Vaším úkolem je rozhodnout, jestli jsou věty pravdivé nebo nepravdivé. Postupujte následovně:',
  'sk-sk': 'Vašou úlohou je upraviť (resp. opraviť) slová alebo výrazy v okienkach. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - обработать (или же исправить) слова или выражения в окошечках. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici corriger le texte inscrit dans les cellules.',
  'it-it': 'Il tuo compito è modificare (ovvero correggere) le parole o termini nelle caselle. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest zmodyfikowanie lub poprawienie wszystkich słów lub tekstu w polach. Postępuj w następujący sposób:',
  'vi-vn': 'Your task is to decide whether the sentences are true or false. Proceed as follows:',
  'tr-tr': 'Göreviniz tüm kelimeleri veya kutucuklardaki metinleri degiştirmek veya düzeltmektir. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra pakeisti arba ištaisyti visus žodžius ar tekstą langeliuose. Darykite taip:',
  'zh-cn': 'Your task is to decide whether the sentences are true or false. Proceed as follows:',
  'bg-bg': 'Вашата задача е да промените или коригирате думите или текста в празните кутийки. Действайте по следния начин:',
  'bs': 'Your task is to decide whether the sentences are true or false. Proceed as follows:',
  'ar-sa': 'لتغيير العنصر الذي استخدمته لملأ الفراغ إملأ الفراغ بعنصر آخر في مكانه.',
};
const tli52: DLoc.ILocItem = {
  'en-gb': 'If the sentence is true, click on True.',
  'de-de': 'Falls der Satz wahr ist, klicken Sie auf Richtig.',
  'sp-sp': 'If the sentence is true, click on True.',
  'cs-cz': 'Pokud je věta pravdivá, klikněte na Správně.',
  'sk-sk': 'If the sentence is true, click on True.',
  'ru-ru': 'If the sentence is true, click on True.',
  'fr-fr': 'If the sentence is true, click on True.',
  'it-it': 'If the sentence is true, click on True.',
  'pl-pl': 'If the sentence is true, click on True.',
  'vi-vn': 'If the sentence is true, click on True.',
  'tr-tr': 'If the sentence is true, click on True.',
  'lt-lt': 'If the sentence is true, click on True.',
  'zh-cn': 'If the sentence is true, click on True.',
  'bg-bg': 'If the sentence is true, click on True.',
  'bs': 'If the sentence is true, click on True.',
  'ar-sa': 'إذا كانت الجملة صحيحة أنقر على الخيار صح',
};
const tli53: DLoc.ILocItem = {
  'en-gb': 'If the sentence is false, click on False.',
  'de-de': 'Falls der Satz unwahr ist, klicken Sie auf Falsch.',
  'sp-sp': 'If the sentence is false, click on False.',
  'cs-cz': 'Pokud je věta nepravdivá, klikněte na Nesprávně.',
  'sk-sk': 'If the sentence is false, click on False.',
  'ru-ru': 'If the sentence is false, click on False.',
  'fr-fr': 'If the sentence is false, click on False.',
  'it-it': 'If the sentence is false, click on False.',
  'pl-pl': 'If the sentence is false, click on False.',
  'vi-vn': 'If the sentence is false, click on False.',
  'tr-tr': 'If the sentence is false, click on False.',
  'lt-lt': 'If the sentence is false, click on False.',
  'zh-cn': 'If the sentence is false, click on False.',
  'bg-bg': 'If the sentence is false, click on False.',
  'bs': 'If the sentence is false, click on False.',
  'ar-sa': 'إذا كانت الجملة خاطئة أنقر على الخيار خطأ',
};
const res = { [globId]: { th116, tp25, tli52, tli53 } };
export default res;