import { toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th123: DLoc.ILocItem = {
  'en-gb': 'VIDEO PLAYBACK',
  'de-de': 'ABSPIELEN VON VIDEOS',
  'sp-sp': 'VIDEO PLAYBACK',
  'cs-cz': 'PŘEHRÁVÁNÍ VIDEA',
  'sk-sk': 'PREHRÁVANIE VIDEA',
  'ru-ru': 'VIDEO PLAYBACK',
  'fr-fr': 'VIDEO PLAYBACK',
  'it-it': 'VIDEO PLAYBACK',
  'pl-pl': 'VIDEO PLAYBACK',
  'vi-vn': 'VIDEO PLAYBACK',
  'tr-tr': 'VİDEO OYNATMAK',
  'lt-lt': 'VAIZDO ATKŪRIMAS',
  'zh-cn': '视频重放',
  'bg-bg': 'ВИДЕО ВЪЗПРОИЗВЕЖДАНЕ',
  'bs': 'VIDEO PLAYBACK',
  'ar-sa': 'تشغيل الفيديو',
};
const tp32: DLoc.ILocItem = {
  'en-gb': 'To play the video you can use the following controls from the bottom control bar.',
  'de-de': 'Übung mit verstecktem Text. Zur Aufdeckung des Textes klicken Sie auf das \"Auge\" Symbol.',
  'sp-sp': 'Ejercicio con texto oculto. Para descubrirlo, haga clic en el ícono del \"ojo\"',
  'cs-cz': 'Pro přehrávání videa můžete používat následující ovládací prvky, které naleznete ve spodní ovládací liště pod videem.',
  'sk-sk': 'Niektorý text v cvičení môže byť skrytý. Ak ho chcete zobraziť, kliknite na ikonku \"oko\".',
  'ru-ru': 'Некоторый текст в упражнении может быть скрытым. Если вы хотите его отобразить, щёлкните на иконку \"глаз\".',
  'fr-fr': 'Pour lire les phrases que vous entendez, cliquez sur l’icône de l’œil.',
  'it-it': 'Alcuni testi negli esercizi possono essere nascosti. Per visualizzare il testo clicca sull’icona dell’”occhio”.',
  'pl-pl': 'Ćwiczenie z ukrytym tekstem. Aby pokazać go, kliknij ikonkę \"oka\".',
  'vi-vn': 'Bài tập với đoạn văn bản ẩn. Để xem văn bản, bạn nhấn chuột lên biểu tượng \"con mắt\".',
  'tr-tr': 'Gizli metinli egzersiz. Metni ortaya çıkarmak içim \"göz\" ikonunu tıklayın.',
  'lt-lt': 'Pratimai su paslėptu tekstu. Norėdami vėl matyti paslėptą tekstą, spustelėkite piktogramą \"akis\".',
  'zh-cn': '隐藏文本的练习. 取消隐藏, 请点击\"眼睛\"图符.',
  'bg-bg': 'Упражнение със скрит текст. За да го отворите, кликнете върху иконката \"око\".',
  'bs': 'To play the video you can use the following controls from the bottom control bar.',
  'ar-sa': 'تمرين النص المخفي . لإظهار النص أنقر فوق أيقونة العين.',
};
const tli64: DLoc.ILocItem = {
  'en-gb': 'To start playing the video, click Play (\u0026gt;).',
  'de-de': 'Sie spielen das Video durch einen Klick auf das Symbol Abspielen (\u0026gt;) ab.',
  'sp-sp': 'To start playing the video, click Play (\u0026gt;).',
  'cs-cz': 'Přehrávání videa spustíte klikem na ikonku Přehrát (\u0026gt;).',
  'sk-sk': 'To start playing the video, click Play (\u0026gt;).',
  'ru-ru': 'To start playing the video, click Play (\u0026gt;).',
  'fr-fr': 'To start playing the video, click Play (\u0026gt;).',
  'it-it': 'To start playing the video, click Play (\u0026gt;).',
  'pl-pl': 'To start playing the video, click Play (\u0026gt;).',
  'vi-vn': 'To start playing the video, click Play (\u0026gt;).',
  'tr-tr': 'To start playing the video, click Play (\u0026gt;).',
  'lt-lt': 'To start playing the video, click Play (\u0026gt;).',
  'zh-cn': 'To start playing the video, click Play (\u0026gt;).',
  'bg-bg': 'To start playing the video, click Play (\u0026gt;).',
  'bs': 'To start playing the video, click Play (\u0026gt;).',
  'ar-sa': 'للبدء بتشغيل الفيديو أنقر على زر التشغيل ( $lt; ).',
};
const tli65: DLoc.ILocItem = {
  'en-gb': 'To stop playing, click Pause (||).',
  'de-de': 'Sie stoppen das Video durch einen Klick auf das Symbol Pause (||).',
  'sp-sp': 'To stop playing, click Pause (||).',
  'cs-cz': 'Přehrávání zastavíte klikem na ikonku pauza (||).',
  'sk-sk': 'To stop playing, click Pause (||).',
  'ru-ru': 'To stop playing, click Pause (||).',
  'fr-fr': 'To stop playing, click Pause (||).',
  'it-it': 'To stop playing, click Pause (||).',
  'pl-pl': 'To stop playing, click Pause (||).',
  'vi-vn': 'To stop playing, click Pause (||).',
  'tr-tr': 'To stop playing, click Pause (||).',
  'lt-lt': 'To stop playing, click Pause (||).',
  'zh-cn': 'To stop playing, click Pause (||).',
  'bg-bg': 'To stop playing, click Pause (||).',
  'bs': 'To stop playing, click Pause (||).',
  'ar-sa': 'لإيقاف تشغيل الفيديو أنقر على زر الإيقاف (||).',
};
const tli66: DLoc.ILocItem = {
  'en-gb': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'de-de': 'Durch Klicken auf das Symbol |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;| verschieben Sie sich um eine Replik vorwärts oder zurück.',
  'sp-sp': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'cs-cz': 'Pomoci šipeček: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;| se přesunete o jednu repliku zpět nebo dopředu.',
  'sk-sk': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'ru-ru': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'fr-fr': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'it-it': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'pl-pl': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'vi-vn': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'tr-tr': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'lt-lt': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'zh-cn': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'bg-bg': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'bs': 'Use the arrows: |\u0026lt;\u0026lt;, \u0026gt;\u0026gt;|, to move one replica back or forward.',
  'ar-sa': 'استخدم الأسهم |$gt;$gt;, $lt;$lt;| للإنتقال نسخة واحدة إلى الأمام أو إلى الخلف',
};
const tli67: DLoc.ILocItem = {
  'en-gb': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'de-de': 'Durch Klicken auf das Symbol \u0026lt;\u0026lt;, \u0026gt;\u0026gt; verschieben Sie sich um einen Satz (einen Teil der Replik) vorwärts oder zurück.',
  'sp-sp': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'cs-cz': 'Pomoci šipeček: \u0026lt;\u0026lt;, \u0026gt;\u0026gt; se přesunete o jednu větu (část repliky) zpět nebo dopředu.',
  'sk-sk': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'ru-ru': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'fr-fr': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'it-it': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'pl-pl': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'vi-vn': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'tr-tr': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'lt-lt': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'zh-cn': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'bg-bg': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'bs': 'Use the arrows: \u0026lt;\u0026lt;, \u0026gt;\u0026gt;, to move one sentence (part of the replica) back or forward.',
  'ar-sa': 'استخدم الأسهم |$gt;$gt;, $lt;$lt;|للإنتقال جملة واحدة إلى الأمام أو إلى الخلف (أي جزء من النسخة الكاملة)',
};
const tli68: DLoc.ILocItem = {
  'en-gb': 'Use T (icon) to display or hide the subtitles.',
  'de-de': 'Durch Klicken auf das Symbol können Sie Untertitel ein- oder ausblenden.',
  'sp-sp': 'Use T (icon) to display or hide the subtitles.',
  'cs-cz': 'Pomoci ikonky T si zobrazíte resp. zakryjete titulky.',
  'sk-sk': 'Use T (icon) to display or hide the subtitles.',
  'ru-ru': 'Use T (icon) to display or hide the subtitles.',
  'fr-fr': 'Use T (icon) to display or hide the subtitles.',
  'it-it': 'Use T (icon) to display or hide the subtitles.',
  'pl-pl': 'Use T (icon) to display or hide the subtitles.',
  'vi-vn': 'Use T (icon) to display or hide the subtitles.',
  'tr-tr': 'Use T (icon) to display or hide the subtitles.',
  'lt-lt': 'Use T (icon) to display or hide the subtitles.',
  'zh-cn': 'Use T (icon) to display or hide the subtitles.',
  'bg-bg': 'Use T (icon) to display or hide the subtitles.',
  'bs': 'Use T (icon) to display or hide the subtitles.',
  'ar-sa': 'استخدم الأيقونة T لإظهار أو إخفاء الحاشية النصية',
};
const tli69: DLoc.ILocItem = {
  'en-gb': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'de-de': 'Durch Klicken auf das Mikrofon-Symbol starten Sie die Anwendung Listen\u0026amp;Talk für den aktuellen Satz.',
  'sp-sp': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'cs-cz': 'Pomocí ikonky mikrofonu si spustíte aplikaci Listen\u0026amp;Talk pro aktuální větu.',
  'sk-sk': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'ru-ru': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'fr-fr': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'it-it': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'pl-pl': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'vi-vn': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'tr-tr': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'lt-lt': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'zh-cn': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'bg-bg': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'bs': 'Use the microphone icon, to run the Listen\u0026amp;Talk application for the current sentence.',
  'ar-sa': 'استخدم أيقونة الميكروفون لتشغيل -تطبيق استمع و تكلم- للجملة الحالية',
};
const tli70: DLoc.ILocItem = {
  'en-gb': 'Use the speaker icon to turn the sound on/off.',
  'de-de': 'Durch Klicken auf das Lautsprecher-Symbol können Sie den Ton ein- oder ausschalten.',
  'sp-sp': 'Use the speaker icon to turn the sound on/off.',
  'cs-cz': 'Pomocí ikonky reproduktoru můžete zapnout/vypnout zvuk',
  'sk-sk': 'Use the speaker icon to turn the sound on/off.',
  'ru-ru': 'Use the speaker icon to turn the sound on/off.',
  'fr-fr': 'Use the speaker icon to turn the sound on/off.',
  'it-it': 'Use the speaker icon to turn the sound on/off.',
  'pl-pl': 'Use the speaker icon to turn the sound on/off.',
  'vi-vn': 'Use the speaker icon to turn the sound on/off.',
  'tr-tr': 'Use the speaker icon to turn the sound on/off.',
  'lt-lt': 'Use the speaker icon to turn the sound on/off.',
  'zh-cn': 'Use the speaker icon to turn the sound on/off.',
  'bg-bg': 'Use the speaker icon to turn the sound on/off.',
  'bs': 'Use the speaker icon to turn the sound on/off.',
  'ar-sa': 'استخدم أيقونة مكبر الصوت لشغيل الصوت و إطفائه',
};
const res = { [globId]: { th123, tp32, tli64, tli65, tli66, tli67, tli68, tli69, tli70 } };
export default res;