import { toGlobId } from 'rw-lib/index'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th124: DLoc.ILocItem = {
  'en-gb': 'VOCABULARY',
  'de-de': 'WORTSCHATZ',
  'sp-sp': 'VOCABULARY',
  'cs-cz': 'SLOVNÍ ZÁSOBA',
  'sk-sk': 'VOCABULARY',
  'ru-ru': 'VOCABULARY',
  'fr-fr': 'VOCABULARY',
  'it-it': 'VOCABULARY',
  'pl-pl': 'VOCABULARY',
  'vi-vn': 'VOCABULARY',
  'tr-tr': 'VOCABULARY',
  'lt-lt': 'VOCABULARY',
  'zh-cn': 'VOCABULARY',
  'bg-bg': 'VOCABULARY',
  'bs': 'VOCABULARY',
  'ar-sa': 'مفردات',
};
const tp33: DLoc.ILocItem = {
  'en-gb': 'When learning new vocabulary, proceed as follows:',
  'de-de': 'Übungen mit Ton können anhand ihrer \"akustische Zeichen\" unterschieden werden. Es gibt zwei Typen von \"akustische Zeichen\":',
  'sp-sp': 'When learning new vocabulary, proceed as follows:',
  'cs-cz': 'Při učení slovní zásoby postupujte následovně:',
  'sk-sk': 'Cvičenie so zvukovou nahrávkou poznáte podľa \"zvukových značiek\". Existujú dve rôzne zvukové značky:',
  'ru-ru': 'Упражнения с аудиозаписью можно узнать по \"звуковым значкам\". Существуют два разных звуковых значка:',
  'fr-fr': 'Vous reconnaîtrez les exercices avec extraits audio grâce aux haut-parleurs :',
  'it-it': 'Gli esercizi con l’audio sono riconoscibili attraverso il „simbolo dell\u0027audio“. Esistono i due simboli dell’audio:',
  'pl-pl': 'Ćwiczenia ze ścieżką dźwiękową mogą być rozpoznane poprzez ich \"znak dźwiękowy\". Istnieją dwa rodzaje \"znaków dźwiękowych\":',
  'vi-vn': 'When learning new vocabulary, proceed as follows:',
  'tr-tr': 'Ses kayıtlı egzersizler \"ses işaretleriyle\" tanınır. İki tip \"ses işareti\" vardır:',
  'lt-lt': 'Pratimai su garso takeliu gali būti atskirti pagal \"garso ženklus\". \"Garso ženklai\" yra dviejų tipų:',
  'zh-cn': 'When learning new vocabulary, proceed as follows:',
  'bg-bg': 'Упражнения, придружени със звук, могат да бъдат разпознати чрез \"знака за звук\". Има два вида \"знак за звук\".',
  'bs': 'When learning new vocabulary, proceed as follows:',
  'ar-sa': 'When learning new vocabulary, proceed as follows:',
};
const tli71: DLoc.ILocItem = {
  'en-gb': 'Read the new word (phrase) and the corresponding translation.',
  'de-de': 'Lesen Sie das deutsche Wort (Phrase) und die entsprechende Übersetzung.',
  'sp-sp': 'Read the new word (phrase) and the corresponding translation.',
  'cs-cz': 'Přečtěte si nové slovíčko (frázi) a odpovídající překlad.',
  'sk-sk': 'Read the new word (phrase) and the corresponding translation.',
  'ru-ru': 'Read the new word (phrase) and the corresponding translation.',
  'fr-fr': 'Read the new word (phrase) and the corresponding translation.',
  'it-it': 'Read the new word (phrase) and the corresponding translation.',
  'pl-pl': 'Read the new word (phrase) and the corresponding translation.',
  'vi-vn': 'Read the new word (phrase) and the corresponding translation.',
  'tr-tr': 'Read the new word (phrase) and the corresponding translation.',
  'lt-lt': 'Read the new word (phrase) and the corresponding translation.',
  'zh-cn': 'Read the new word (phrase) and the corresponding translation.',
  'bg-bg': 'Read the new word (phrase) and the corresponding translation.',
  'bs': 'Read the new word (phrase) and the corresponding translation.',
  'ar-sa': 'إقرأ الكلمة أو العبارة الجديدة و الترجمة المرسلة',
};
const tli72: DLoc.ILocItem = {
  'en-gb': 'Click the speaker icon and listen to the correct pronunciation.',
  'de-de': 'Klicken Sie auf das Lautsprecher-Symbol und hören Sie sich die richtige Aussprache an.',
  'sp-sp': 'Click the speaker icon and listen to the correct pronunciation.',
  'cs-cz': 'Klikněte na ikonku reproduktoru a poslechněte si výslovnost.',
  'sk-sk': 'Click the speaker icon and listen to the correct pronunciation.',
  'ru-ru': 'Click the speaker icon and listen to the correct pronunciation.',
  'fr-fr': 'Click the speaker icon and listen to the correct pronunciation.',
  'it-it': 'Click the speaker icon and listen to the correct pronunciation.',
  'pl-pl': 'Click the speaker icon and listen to the correct pronunciation.',
  'vi-vn': 'Click the speaker icon and listen to the correct pronunciation.',
  'tr-tr': 'Click the speaker icon and listen to the correct pronunciation.',
  'lt-lt': 'Click the speaker icon and listen to the correct pronunciation.',
  'zh-cn': 'Click the speaker icon and listen to the correct pronunciation.',
  'bg-bg': 'Click the speaker icon and listen to the correct pronunciation.',
  'bs': 'Click the speaker icon and listen to the correct pronunciation.',
  'ar-sa': 'أنقر على أيقونة مكبر الصوت لتستمع إلى اللفظ الحالي',
};
const tli73: DLoc.ILocItem = {
  'en-gb': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'de-de': 'Klicken Sie auf das Mikrofon-Symbol und üben Sie die Aussprache dank der Anwendung Listen\u0026amp;Talk.',
  'sp-sp': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'cs-cz': 'Klikněte na ikonku mikrofonu a procvičujte si výslovnost pomocí nástroje Listen\u0026amp;Talk.',
  'sk-sk': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'ru-ru': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'fr-fr': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'it-it': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'pl-pl': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'vi-vn': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'tr-tr': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'lt-lt': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'zh-cn': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'bg-bg': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'bs': 'Click the microphone icon and practice correct pronunciation using Listen\u0026amp;Talk application.',
  'ar-sa': 'أنقر على أيقونة المكريفون و تدرب على اللفظ مستخدماً -تطبيق استمع و تكلم-',
};
const res = { [globId]: { th124, tp33, tli71, tli72, tli73 } };
export default res;