import { ILocItem, toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th12: ILocItem = {
  'en-gb': 'WORD SEQUENCING',
  'de-de': 'WORTE SEQUENTIALISIEREN',
  'sp-sp': 'SECUENCIA DE PALABRAS',
  'cs-cz': 'ŘAZENÍ SLOV',
  'sk-sk': 'RADENIE SLOV',
  'ru-ru': 'ПОРЯДОК СЛОВ',
  'fr-fr': 'CLASSEMENT DE MOTS',
  'it-it': 'SEQUENZA DELLE PAROLE',
  'pl-pl': 'UKŁADANIE SŁÓW',
  'vi-vn': 'SẮP XẾP TỪ',
  'tr-tr': 'KELIME SIRALAMA',
  'lt-lt': 'ŽODŽIŲ EILĖS NUSTATYMAS',
  'zh-cn': '单词排序',
  'bg-bg': 'ПОСЛЕДОВАТЕЛНОСТ НА ДУМИТЕ',
  'bs': 'WORD SEQUENCING',
  'ar-sa': 'ترتيب كلمات',
};
const tp2: ILocItem = {
  'en-gb': 'Your task is to put the words into correct order. Proceed as follows:',
  'de-de': 'Ihre Aufgabe ist es, die Wörter in die richtige Reihenfolge zu setzen. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea es poner las palabras en el orden correcto para formar las oraciones. Proceda de la siguiente manera:',
  'cs-cz': 'Vaším úkolem je seřadit slova do správného pořadí, aby tvořila větu. Postupujte následovně:',
  'sk-sk': 'Vašou úlohou je zoradiť slová do správneho poradia, aby tvorili vetu. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - расставить слова в правильном порядке, чтобы получилось предложение. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici placer les mots dans le bon ordre afin de former une phrase.',
  'it-it': 'Il tuo compito è mettere le parole nell\u0027ordine corretto in modo da formare una frase. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest ułożenie wyrazów w odpowiedniej kolejności. Postępuj w następujący sposób:',
  'vi-vn': 'Sắp xếp các từ theo đúng thứ tự. Cách làm như sau:',
  'tr-tr': 'Göreviniz kelimeleri dogru siraya sokmaktir. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra sudėti žodžius teisinga tvarka. Darykite taip:',
  'zh-cn': '您的任务是将单词排列为正确的顺序. 操作如下:',
  'bg-bg': 'Вашата задача е да подредите думите в правилния ред. Действайте по следния начин:',
  'bs': 'Your task is to put the words into correct order. Proceed as follows:',
  'ar-sa': 'مهمتك هي أن تضع الكلمات بترتيب صحيح. قم بما يلي:',
};
const tli8: ILocItem = {
  'en-gb': 'Click on the word you wish to move. The word will be highlighted.',
  'de-de': 'Klicken Sie auf das Wort, das Sie bewegen möchten. Das Wort wird hervorgehoben.',
  'sp-sp': 'Haga clic en la palabra que desea mover. La palabra aparecerá resaltada',
  'cs-cz': 'Klikněte na slovo, které chcete přesunout. Slovo se zvýrazní.',
  'sk-sk': 'Kliknite na slovo, ktoré chcete presunúť. Slovo sa zvýrazní.',
  'ru-ru': 'Щелкните слово, которое хотите переместить. Слово будет выделено.',
  'fr-fr': 'Cliquez sur l’étiquette que vous voulez déplacer.',
  'it-it': 'Clicca sulla parola da trascinare. La parola viene marcata.',
  'pl-pl': 'Kliknij wyraz, który chcesz przesunąć. Wyraz zostanie wyróżniony.',
  'vi-vn': 'Nhấn chuột lên từ mà bạn muốn di chuyển. Từ đó sẽ được đánh dấu.',
  'tr-tr': 'Kaldırmak istediğiniz kelimeyi tıklayın. Kelime renkli olarak vurgulanacaktır.',
  'lt-lt': 'Paspauskite ant žodžio, kurį norite perkelti. Šis žodis bus paryškintas.',
  'zh-cn': '点击您想要移动的单词. 单词将被突出显示.',
  'bg-bg': 'Кликнете върху думата, която искате да преместите. Думата ще бъде засветена.',
  'bs': 'Click on the word you wish to move. The word will be highlighted.',
  'ar-sa': 'إضغط على الكلمة التي تشاء للإنتقال إليها. سيتم تحديد الكلمة.',
};
const tli9: ILocItem = {
  'en-gb': 'Hold the left mouse button down and drag the word to the right place.',
  'de-de': 'Halten Sie die linke Maustaste gedrückt und ziehen Sie das Wort auf die richtige Stelle.',
  'sp-sp': 'Mantenga presionado el botón izquierdo del ratón y arrastre la palabra a su posición correcta.',
  'cs-cz': 'Držte tlačítko myši stisknuté a přesuňte slovo (pohybem myši) na nové místo.',
  'sk-sk': 'Držte tlačidlo myši stlačené a presuňte slovo (pohybom myši) na nové miesto.',
  'ru-ru': 'Держите кнопку мыши нажатой и переместите слово (движение мыши) на новое место.',
  'fr-fr': 'Maintenez le bouton de la souris enfoncé et glissez l’étiquette à l’endroit souhaité.',
  'it-it': 'Tieni premuto il pulsante del mouse e trascina la parola (muovendo il mouse) al posto nuovo.',
  'pl-pl': 'Przytrzymaj lewy przycisk myszki i przeciągnij wyraz w odpowiednie miejsce.',
  'vi-vn': 'Nhấn, giữ chuột trái và kéo từ đó vào đúng vị trí.',
  'tr-tr': 'Mouse\u0027un sol tuşuna basılı tutun ve kelimeyi doğru yere sürükleyin.',
  'lt-lt': 'Laikydami kairįjį pelės mygtuką vilkite žodį į tinkamą vietą.',
  'zh-cn': '按住鼠标左键并拖曳單詞至正确位置.',
  'bg-bg': 'Натиснете продължително левия бутон на мишката и влачете думата до правилното място.',
  'bs': 'Hold the left mouse button down and drag the word to the right place.',
  'ar-sa': 'استمر في الضغط على الزر الأيسر للفارة و اسحب الكلمة إلى المكان الصحيح',
};
const tli10: ILocItem = {
  'en-gb': 'When the mouse arrow points to the right place, release the left mouse button.',
  'de-de': 'Wenn der Pfeil auf die richtige Stelle zeigt, lassen Sie die linke Maustaste los.',
  'sp-sp': 'Cuando el puntero señale el lugar correcto, suelte el botón izquierdo del ratón.',
  'cs-cz': 'Až bude kurzor myši nad místem, na které chcete slovo přesunout, uvolněte kurzor myši.',
  'sk-sk': 'Keď bude kurzor myši nad miestom, na ktoré chcete slovo presunúť, uvoľnite kurzor myši.',
  'ru-ru': 'Когда курсор мыши будет на том месте, куда вы хотите слово переместить, отпустите кнопку мыши.',
  'fr-fr': 'Relâchez le bouton pour placer l’étiquette.',
  'it-it': 'Nel momento in cui il cursore del mouse sarà impostato sul posto dove desideri impostare la parola, rilascia il cursore del mouse.',
  'pl-pl': 'Jeżeli strzałka wskazuje na odpowiednie miejsce, puść przycisk myszki.',
  'vi-vn': 'Khi mũi tên con trỏ chuột chỉ đúng vị trí, hãy thả nút trái chuột.',
  'tr-tr': 'Mouse oku dogru yeri gösterdiginde, sol mouse tuşunu birakin.',
  'lt-lt': 'Kai pelės strelytė bus reikiamoje vietoje, atleiskite kairįjį pelės mygtuką.',
  'zh-cn': '当鼠标箭头指向正确的位置, 即放开鼠标左键.',
  'bg-bg': 'Когато стрелката на мишката покаже правилното място, отпуснете левия бутон на мишката.',
  'bs': 'When the mouse arrow points to the right place, release the left mouse button.',
  'ar-sa': 'عندما يصبح مؤشر الفارة في المكان الصحيح أفلت زر الفارة الأيسر',
};
const tli11: ILocItem = {
  'en-gb': 'The word will be moved.',
  'de-de': 'Das Wort wird verschoben.',
  'sp-sp': 'La palabra se moverá',
  'cs-cz': 'Slovo bude přesunuto.',
  'sk-sk': 'Slovo bude presunuté.',
  'ru-ru': 'Слово будет перемещено.',
  'fr-fr': 'Le mot sera déplacé.',
  'it-it': 'La parola sarà trascinata.',
  'pl-pl': 'Słowo zostanie przeniesione.',
  'vi-vn': 'Từ sẽ được chuyển chỗ.',
  'tr-tr': 'Kelime kaldırılacaktır.',
  'lt-lt': 'žodis bus perkeltas',
  'zh-cn': '单词将被移动.',
  'bg-bg': 'Думата ще се премести.',
  'bs': 'The word will be moved.',
  'ar-sa': 'سيتم نقل الكلمة',
};
const res = { [globId]: { th12, tp2, tli8, tli9, tli10, tli11 } };
export default res;