import { ILocItem, toGlobId } from 'rw-lib/loc'; declare const __moduleName: string; const globId = toGlobId(__moduleName);
const th117: ILocItem = {
  'en-gb': 'YES/NO QUESTIONS',
  'de-de': 'JA/NEIN FRAGEN',
  'sp-sp': 'YES/NO QUESTIONS',
  'cs-cz': 'ANO/NE OTÁZKY',
  'sk-sk': 'ZOBRAZENIE SKRYTÉHO TEXTU',
  'ru-ru': 'ОТОБРАЖЕНИЕ СКРЫТОГО ТЕКСТА',
  'fr-fr': 'AFFICHAGE DU TEXTE',
  'it-it': 'VISUALIZZAZIONE DEL TESTO NASCOSTO',
  'pl-pl': 'WYŚWIETLANIE UKRYTEGO TEKSTU',
  'vi-vn': 'YES/NO QUESTIONS',
  'tr-tr': 'GİZLİ METNİ GÖRÜNTÜLEMEK',
  'lt-lt': 'PASLĖPTO TEKSTO RODYMAS',
  'zh-cn': 'YES/NO QUESTIONS',
  'bg-bg': 'ПОКАЗВАНЕ НА СКРИТ ТЕКСТ',
  'bs': 'YES/NO QUESTIONS',
  'ar-sa': 'أسئلة بنعم أو لا',
};
const tp26: ILocItem = {
  'en-gb': 'Your task is to decide whether the answers to the questions are Yes or No.',
  'de-de': 'Ihre Aufgabe ist es, sich zu entscheiden, ob die Sätze richtig oder falsch sind. Jeder Satz ist mit einer Ikone bezeichnet. Gehen Sie folgendermassen vor:',
  'sp-sp': 'Su tarea es decidir, si las frases son verdaderas o falsas. Cada frase está marcada con un ícono. Proceda de la siguiente manera:',
  'cs-cz': 'Vaším úkolem je rozhodnout, jestli odpověď na otázku je Ano nebo Ne. Postupujte následovně:',
  'sk-sk': 'Vašou úlohou je rozhodnúť, či sú vety pravdivé alebo nepravdivé. Vety sú označené ikonou. Postupujte nasledovne:',
  'ru-ru': 'Ваше задание - решить, являются ли предложения правдивыми или ложными. Предложения обозначены иконкой. Действуйте следующим образом:',
  'fr-fr': 'Vous devez ici choisir si la phrase marquée est vraie ou fausse.',
  'it-it': 'Il tuo compito è decidere se le frasi sono vere o false. Le frasi sono contrassegnate dall’icona. Prosegui secondo le istruzioni:',
  'pl-pl': 'Twoim zadaniem jest zadecydowanie, czy zdania są prawdziwe lub fałszywe. Każde zdanie oznaczone jest ikonką. Postępuj w następujący sposób:',
  'vi-vn': 'Bạn hãy xác định các câu đúng hay sai. Mỗi câu đều được đánh dấu bằng một biểu tượng. Cách làm như sau:',
  'tr-tr': 'Göreviniz cümlelerin dogru veya yanliş olduguna karar vermektir. Her cümle bir ikonla işaretlenmiştir. Aşagidakileri uygulayin:',
  'lt-lt': 'Tavo užduotis yra nuspręsti ar sakiniai yra teisingi ar klaidingi. Kiekvienas sakinys yra pažymėtas simboliu. Darykite taip:',
  'zh-cn': '您的任务是决定句子为真或假. 每个句子都以图符标记. 操作如下:',
  'bg-bg': 'Вашата задача е да решите дали изреченията са верни или неверни. Всяко изречение е отбелязано с иконка. Действайте по следния начин:',
  'bs': 'Your task is to decide whether the answers to the questions are Yes or No.',
  'ar-sa': 'مهمتك أن تقرر فيما إذا كانت الجمل صحيحة أم خاطئة. ستجد بجانب كل جملة أيقونة تحديد. قم بما يلي :',
};
const tli54: ILocItem = {
  'en-gb': 'If the correct answer is Yes, click on YES.',
  'de-de': 'Falls die richtige Antwort Ja heißt, klicken Sie auf JA.',
  'sp-sp': 'If the correct answer is Yes, click on YES.',
  'cs-cz': 'Pokud je správná odpověď Ano, klikněte na ANO.',
  'sk-sk': 'If the correct answer is Yes, click on YES.',
  'ru-ru': 'If the correct answer is Yes, click on YES.',
  'fr-fr': 'If the correct answer is Yes, click on YES.',
  'it-it': 'If the correct answer is Yes, click on YES.',
  'pl-pl': 'If the correct answer is Yes, click on YES.',
  'vi-vn': 'If the correct answer is Yes, click on YES.',
  'tr-tr': 'If the correct answer is Yes, click on YES.',
  'lt-lt': 'If the correct answer is Yes, click on YES.',
  'zh-cn': 'If the correct answer is Yes, click on YES.',
  'bg-bg': 'If the correct answer is Yes, click on YES.',
  'bs': 'If the correct answer is Yes, click on YES.',
  'ar-sa': 'إذا كان الجواب الصحيح نعم , أنقر على الخيار نعم',
};
const tli55: ILocItem = {
  'en-gb': 'If the correct answer is No, click on NO.',
  'de-de': 'Falls die richtige Antwort Nein heißt, klicken Sie auf NEIN.',
  'sp-sp': 'If the correct answer is No, click on NO.',
  'cs-cz': 'Pokud je správná odpověď Ne, klikněte na NE.',
  'sk-sk': 'If the correct answer is No, click on NO.',
  'ru-ru': 'If the correct answer is No, click on NO.',
  'fr-fr': 'If the correct answer is No, click on NO.',
  'it-it': 'If the correct answer is No, click on NO.',
  'pl-pl': 'If the correct answer is No, click on NO.',
  'vi-vn': 'If the correct answer is No, click on NO.',
  'tr-tr': 'If the correct answer is No, click on NO.',
  'lt-lt': 'If the correct answer is No, click on NO.',
  'zh-cn': 'If the correct answer is No, click on NO.',
  'bg-bg': 'If the correct answer is No, click on NO.',
  'bs': 'If the correct answer is No, click on NO.',
  'ar-sa': 'إذا كان الجواب الصحيح لا , أنقر على الخيار لا',
};
const res = { [globId]: { th117, tp26, tli54, tli55 } };
export default res;